[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --no-frozen-lockfile && NODE_ENV=production BASE_PATH=/ NODE_OPTIONS=--max-old-space-size=4096 pnpm run build:production"
nixpacksPlan = { phases = { install = { cmds = ["pnpm install --no-frozen-lockfile"] } } }

[deploy]
preDeployCommand = "pnpm run db:push"
startCommand = "pnpm start"
healthCheckPath = "/api/healthz"
