[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --no-frozen-lockfile && pnpm run build:production"
nixpacksPlan = { phases = { install = { cmds = ["pnpm install --no-frozen-lockfile"] } } }

[deploy]
startCommand = "pnpm start"
