/** Word-level Albanian → English fallback for long paragraphs. */
export const AL_WORDS = [
  ["është", "is"],
  ["janë", "are"],
  ["për", "for"],
  ["dhe", "and"],
  ["në", "in"],
  ["të", "to"],
  ["me", "with"],
  ["nga", "from"],
  ["ose", "or"],
  ["një", "a"],
  ["nuk", "not"],
  ["ju", "you"],
  ["ne", "we"],
  ["nëse", "if"],
  ["kur", "when"],
  ["që", "that"],
  ["si", "as"],
  ["duhet", "must"],
  ["mund", "can"],
  ["pas", "after"],
  ["para", "before"],
  ["çdo", "every"],
  ["vetëm", "only"],
  ["gjithë", "all"],
  ["përdoruesit", "users"],
  ["përdorues", "user"],
  ["njoftim", "listing"],
  ["njoftime", "listings"],
  ["shpallje", "listing"],
  ["postim", "post"],
  ["postoni", "post"],
  ["kategori", "category"],
  ["kategorinë", "category"],
  ["nënkategori", "subcategory"],
  ["nënkategorinë", "subcategory"],
  ["shitës", "seller"],
  ["blerës", "buyer"],
  ["platforma", "platform"],
  ["platformës", "platform"],
  ["falas", "free"],
  ["Operatori", "Operator"],
  ["ligjor", "legal"],
  ["Misioni", "Mission"],
  ["Rregullat", "Rules"],
  ["Politika", "Policy"],
  ["Kontakt", "Contact"],
  ["Pyetje", "Questions"],
  ["Siguria", "Security"],
  ["thjesht", "simply"],
  ["transparent", "transparent"],
  ["mbledhim", "collect"],
  ["përdorim", "use"],
  ["ruhen", "stored"],
  ["enkriptuara", "encrypted"],
  ["shesim", "sell"],
  ["marketing", "marketing"],
  ["kërkoni", "request"],
  ["fshirje", "deletion"],
  ["korrigjim", "correction"],
  ["verifikim", "verification"],
  ["autentifikim", "authentication"],
  ["mbështetje", "support"],
  ["parandalim", "prevention"],
  ["mashtrimesh", "fraud"],
  ["abuzimit", "abuse"],
  ["përmirësim", "improvement"],
  ["statistika", "statistics"],
  ["shërbimit", "service"],
  ["plotësoni", "fill in"],
  ["dërgo", "send"],
  ["mesazhin", "message"],
  ["subjektin", "subject"],
  ["emri", "name"],
  ["email-i", "email"],
  ["telefonit", "phone"],
  ["adresa", "address"],
  ["ligjore", "legal"],
  ["operatorit", "operator"],
  ["pranoni", "accept"],
  ["termat", "terms"],
  ["kushtet", "conditions"],
  ["përgjegjësi", "responsibility"],
  ["vërtetësinë", "accuracy"],
  ["postimit", "listing"],
  ["tuaj", "your"],
  ["tonë", "our"],
  ["zyrtare", "official"],
  ["diaspora", "diaspora"],
  ["shqiptare", "Albanian"],
  ["tregje", "markets"],
  ["tregun", "market"],
  ["lokal", "local"],
  ["shpejt", "quickly"],
  ["sigurt", "safely"],
  ["komisione", "fees"],
  ["fshehura", "hidden"],
  ["bazë", "basic"],
  ["hapësirë", "space"],
  ["ndërmjetëse", "intermediary"],
  ["marrëveshja", "agreement"],
  ["çmimit", "price"],
  ["dorëzimit", "delivery"],
  ["drejt", "direct"],
  ["palëve", "parties"],
  ["mes", "between"],
  ["palë", "party"],
  ["zgjidh", "choose"],
  ["zgjidhni", "choose"],
  ["punë", "work"],
  ["kurse", "courses"],
  ["mësime", "lessons"],
  ["arsimore", "educational"],
  ["gjuhë", "language"],
  ["fëmijë", "children"],
  ["pjesë", "parts"],
  ["përdorur", "used"],
  ["markën", "brand"],
  ["modelin", "model"],
  ["vitin", "year"],
];

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function wordTranslateSqToEn(text, applyPhrases) {
  let s = applyPhrases(text);
  for (const [sq, en] of AL_WORDS) {
    s = s.replace(new RegExp(`\\b${escapeRegExp(sq)}\\b`, "gi"), en);
  }
  return s;
}
