/** English category labels → Italian (listing + subcategories). */
import { CAT_EN_EXACT } from "./category-en-from-ks.mjs";
import { applyItalianPhrases } from "./italian-phrases.mjs";
import { CATEGORY_EN_FR_EXTRA } from "./category-en-fr-extra.mjs";

/** Full-phrase overrides — avoid word-chop (e.g. Home → Home). */
const MANUAL_IT = {
  "Electronics & Home Appliances": "Elettronica & elettrodomestici",
  "Large Home Appliances": "Grandi elettrodomestici",
  "Homes & Apartments": "Case & appartamenti",
  "Furniture & Decor": "Mobili & arredamento",
  "Clothing & Shoes": "Abbigliamento & scarpe",
  "Children": "Bambini",
  "Sport & Outdoor": "Sport & outdoor",
  "Jobs & Services": "Lavoro & servizi",
  "Construction & Installations": "Costruzioni & installazioni",
  "Construction & Masonry": "Costruzioni & muratura",
  "Plaster & Finishing": "Intonaco & finiture",
  "Tiling & Mosaic": "Piastrelle & mosaico",
  "Painting & Decor": "Pittura & decorazione",
  "Roof repair & insulation": "Riparazione tetti & isolamento",
  "Floor repair & parquet": "Riparazione pavimenti & parquet",
  "Window & door repair": "Riparazione finestre & porte",
  "Heating & A/C installation": "Installazione riscaldamento & climatizzazione",
  "Camera & alarm installation": "Installazione telecamere & allarmi",
  "Solar panel installation": "Installazione pannelli solari",
  "Furniture moving & transport": "Trasloco mobili & trasporto",
  "General maintenance & repairs": "Manutenzione & riparazioni generali",
  "Agriculture & Livestock": "Agricoltura & allevamento",
  "Education & Courses": "Istruzione & corsi",
  "Music & Hobbies": "Musica & hobby",
  "Pets & Animals": "Animali domestici",
  "Wanted to Buy": "Cerco da acquistare",
  "Looking for something? Post here and find it":
    "Cerchi qualcosa? Pubblica qui e trova",
  "Free Gifts & Giveaways": "Regali gratuiti & omaggi — Da persone gentili!",
  "Free Gifts & Giveaways — From kind people!": "Regali gratuiti & omaggi — Da persone gentili!",
  "Cars": "Auto",
  "Motorcycles & Scooters": "Moto & scooter",
  "Trucks & Vans": "Camion & furgoni",
  "Auto Parts": "Ricambi auto",
  "Commercial & Office Space": "Locali commerciali & uffici",
  "Phones": "Telefoni",
  "Computers & Laptops": "Computer & portatili",
  "Motorcycles": "Moto",
  "Scooters": "Scooter",
  "Trucks": "Camion",
  "Vans": "Furgoni",
  "Buses": "Autobus",
  "Tyres & Wheels": "Pneumatici & cerchi",
  "Body & Glass": "Carrozzeria & vetri",
  "Accessories": "Accessori",
  "Apartments & Flats": "Appartamenti",
  "Houses": "Case",
  "Apartments for Rent": "Appartamenti in affitto",
  "Apartments for Sale": "Appartamenti in vendita",
  "Houses & Villas": "Case & ville",
  "Land & Plots": "Terreni & lotti",
  "Garages": "Garage",
  "Rooms for Rent": "Stanze in affitto",
  "Commercial Units for Rent": "Locali commerciali in affitto",
  "Commercial Units for Sale": "Locali commerciali in vendita",
  "Offices": "Uffici",
  "Warehouses & Storage": "Magazzini & depositi",
  "Industrial Buildings": "Edifici industriali",
  "Other Phones": "Altri telefoni",
  "Phone Accessories": "Accessori telefono",
  "Laptops": "Portatili",
  "Desktop PCs": "PC desktop",
  "Tablets": "Tablet",
  "Gaming & Consoles": "Gaming & console",
  "Drones": "Droni",
  "HVAC & Heating": "Riscaldamento & climatizzazione",
  "TVs & Projectors": "TV & proiettori",
  "Audio & Sound Equipment": "Audio & attrezzatura sonora",
  "Cameras, Photo & Smartwatches": "Fotocamere & smartwatch",
  "Televisions": "Televisori",
  "Fridges & Washing Machines": "Frigoriferi & lavatrici",
  "Air Conditioners": "Condizionatori",
  "Cookers & Ovens": "Fornelli & forni",
  "Audio & Cameras": "Audio & fotocamere",
  "Bedroom": "Camera da letto",
  "Living Room": "Soggiorno",
  "Kitchen": "Cucina",
  "Bathroom & Sanitary": "Bagno & sanitari",
  "Decor": "Decorazione",
  "Building Materials": "Materiali da costruzione",
  "Women's Clothing": "Abbigliamento donna",
  "Men's Clothing": "Abbigliamento uomo",
  "Shoes": "Scarpe",
  "Bags & Accessories": "Borse & accessori",
  "Jewellery & Watches": "Gioielli & orologi",
  "Perfumes": "Profumi",
  "Toys": "Giocattoli",
  "Children's Clothing": "Abbigliamento bambini",
  "Strollers & Cribs": "Passeggini & culle",
  "School Books": "Libri scolastici",
  "Maternity Products": "Prodotti per la maternità",
  "Sports Equipment": "Attrezzatura sportiva",
  "Bicycles & E-bikes": "Biciclette & e-bike",
  "Hunting & Fishing": "Caccia & pesca",
  "Camping & Outdoors": "Campeggio & outdoor",
  "Musical Instruments": "Strumenti musicali",
  "Job Offers": "Offerte di lavoro",
  "Looking for Work": "Cerco lavoro",
  "Professional Services": "Servizi professionali",
  "Cleaning & Maintenance": "Pulizia & manutenzione",
  "Construction & Renovation": "Costruzione & ristrutturazione",
  "Farm Animals": "Animali da fattoria",
  "Farm Machinery": "Macchinari agricoli",
  "Seeds & Seedlings": "Semi & piantine",
  "Farm Produce": "Prodotti agricoli",
  "Private Tutoring": "Lezioni private",
  "Language Courses": "Corsi di lingua",
  "IT Courses": "Corsi informatici",
  "Books & Materials": "Libri & materiali",
  "Instruments": "Strumenti",
  "Books & Magazines": "Libri & riviste",
  "Collectibles": "Collezionismo",
  "Games & Toys": "Giochi & giocattoli",
  "Dogs": "Cani",
  "Cats": "Gatti",
  "Birds": "Uccelli",
  "Other Animals": "Altri animali",
  "Pet Accessories": "Accessori per animali",
  "Homework Help": "Aiuto compiti",
  "Help with Applications": "Aiuto con le candidature",
  "Preschool education": "Educazione prescolare",
  "Arts & creativity": "Arte & creatività",
  "Professional training": "Formazione professionale",
  "Educational music": "Musica educativa",
  "Children's clothing & shoes": "Abbigliamento & scarpe bambini",
  "Baby clothing (0-12 months)": "Abbigliamento neonato (0–12 mesi)",
  "Toddler clothing (1-5 years)": "Abbigliamento bambini piccoli (1–5 anni)",
  "School clothing (6-14 years)": "Abbigliamento scolastico (6–14 anni)",
  "Furniture (wardrobes, changing tables, toy shelves)":
    "Mobili (armadi, fasciatoi, scaffali giocattoli)",
  "Nurseries & kindergartens": "Asili nido & scuole materne",
  "Bags & maternity accessories": "Borse & accessori maternità",
  "Human resources": "Risorse umane",
  "Baby handbag": "Borsa per neonati",
  "School bag": "Zaino scolastico",
  "Baby backpack (diaper bag)": "Zaino neonato (borsa fasciatoio)",
  "Certificates & diplomas": "Certificati & diplomi",
  "Financial certificates": "Certificati finanziari",
  "IT certificates": "Certificati informatici",
  "Decor & night lights": "Decorazione & luci notturne",
  "Design & media": "Design & media",
  "Graphic design": "Graphic design",
  "Art education": "Educazione artistica",
  "Health education": "Educazione sanitaria",
  "Sun hats & UV protection": "Cappelli da sole & protezione UV",
  "Baby chairs & seats": "Sedie & seggiolini per neonati",
  "Car seats (group 0+, 1, 2/3)": "Seggiolini auto (gruppo 0+, 1, 2/3)",
  "Car seat group 0+ (0-13 kg)": "Seggiolino auto gruppo 0+ (0–13 kg)",
  "Car seat group 1 (9-18 kg)": "Seggiolino auto gruppo 1 (9–18 kg)",
  "Car seat group 2/3 (15-36 kg)": "Seggiolino auto gruppo 2/3 (15–36 kg)",
  "Portable high chairs": "Seggioloni portatili",
  "Strollers & transport": "Passeggini & trasporto",
  "Classic strollers": "Passeggini classici",
  "Twin strollers": "Passeggini gemellari",
  "Costumes & play clothing": "Costumi & abbigliamento da gioco",
  "Sports costumes": "Costumi sportivi",
  "Bed & children's room": "Letto & camera dei bambini",
  "Acting course": "Corso di recitazione",
  "Ballet course": "Corso di balletto",
  "First aid course": "Corso di primo soccorso",
  "Painting course": "Corso di pittura",
  "Professional courses": "Corsi professionali",
  "Standard courses": "Corsi standard",
  "Technical courses": "Corsi tecnici",
  "Books & school supplies": "Libri & materiale scolastico",
  "Educational toys": "Giocattoli educativi",
  "Classic toys (dolls, figures, cars, trains)": "Giocattoli classici (bambole, figurine, auto, treni)",
  "Montessori toys": "Giocattoli Montessori",
  "Musical toys": "Giocattoli musicali",
  "Sand & beach toys": "Giocattoli da sabbia & spiaggia",
  "Logic games & educational puzzles": "Giochi di logica & puzzle educativi",
  "Board games (table games, puzzles, cards)": "Giochi da tavolo (giochi, puzzle, carte)",
  "Master's & doctorate": "Master & dottorato",
  "Baby carriers (kangaroo, wrap, sling)": "Marsupi (kangaroo, fascia, sling)",
  "Bottle holders": "Portabiberon",
  "Financial support": "Sostegno finanziario",
  "Corner & table edge protectors": "Protezioni angoli & bordi tavolo",
  "Electrical outlet covers": "Copriprese elettriche",
  "Rain & sun covers for strollers": "Coperture pioggia & sole per passeggino",
  "Project management": "Gestione progetti",
  "Critical thinking for children": "Pensiero critico per bambini",
  "Homeschooling": "Istruzione domiciliare",
  "Private lessons": "Lezioni private",
  "Drawing & painting supplies": "Materiale per disegno & pittura",
  "Baby audio monitor": "Baby monitor audio",
  "Baby video monitor (camera)": "Baby monitor video (telecamera)",
  "Diploma recognition": "Riconoscimento diplomi",
  "Online learning": "Apprendimento online",
  "Stroller organisers": "Organizer per passeggino",
  "Maternity trousers & tops": "Pantaloni & top premaman",
  "Disposable diapers": "Pannolini monouso",
  "Reusable diapers": "Pannolini riutilizzabili",
  "Goethe exam preparation": "Preparazione esame Goethe",
  "IELTS preparation": "Preparazione IELTS",
  "Exam preparation": "Preparazione agli esami",
  "TOEFL preparation": "Preparazione TOEFL",
  "Inflatable pools": "Piscine gonfiabili",
  "Pool & beach for children": "Piscina & spiaggia per bambini",
  "Breast pumps (electric & manual)": "Tiralatte (elettrici & manuali)",
  "Safety gates (stairs & rooms)": "Cancelletti di sicurezza (scale & stanze)",
  "Care products (stretch mark cream)": "Prodotti cura (crema smagliature)",
  "Skincare products (cream, shampoo, massage oil)": "Prodotti per la pelle (crema, shampoo, olio massaggio)",
  "JavaScript programming": "Programmazione JavaScript",
  "Python programming": "Programmazione Python",
  "International exams": "Esami internazionali",
  "Development centre": "Centro di sviluppo",
  "Health & wellness": "Salute & benessere",
  "Bottles & feeding": "Biberon & alimentazione",
  "Practical skills": "Competenze pratiche",
  "Private primary school": "Scuola primaria privata",
  "Primary education": "Istruzione primaria",
  "Scooters & skates": "Monopattini & pattini",
  "Child safety": "Sicurezza dei bambini",
  "Travel systems (stroller + car seat)": "Sistemi da viaggio (passeggino + seggiolino)",
  "Sterilisers & bottle warmers": "Sterilizzatori & scaldabiberon",
  "Nursing bras & breastfeeding clothing": "Reggiseni & abbigliamento allattamento",
  "Play mats & sensory stimulation": "Tappetini gioco & stimolazione sensoriale",
  "Music theory": "Teoria musicale",
  "Thermometer & health devices": "Termometro & dispositivi sanitari",
  "Balls & sports equipment": "Palloni & attrezzatura sportiva",
  "IT training": "Formazione informatica",
  "Scooters & skis": "Monopattini & sci",
  "Academic tutoring": "Ripetizioni accademiche",
  "Booster seats": "Rialzi per seggiolino",
  "University & scholarships": "Università & borse di studio",
  "Baby food & snacks": "Alimenti & snack per neonati",
  "Feeding & nutrition": "Alimentazione & nutrizione",
  "Baby bath tub": "Vaschetta per neonati",
  "Swimwear & swimming": "Costumi da bagno & nuoto",
  "Winter clothing (coats, jackets, costumes)": "Abbigliamento invernale (cappotti, giacche, costumi)",
  "Maternity clothing": "Abbigliamento premaman",
  "Summer clothing": "Abbigliamento estivo",
  "Video editing": "Montaggio video",
  "Cognitive development": "Sviluppo cognitivo",
  "Personal development": "Sviluppo personale",
  "Software development": "Sviluppo software",
  "Study scholarships": "Borse di studio",
  "Children's dishes & spoons": "Stoviglie & cucchiaini per bambini",
  "Notebooks & school supplies": "Quaderni & materiale scolastico",
  "Toys & games": "Giocattoli & giochi",
  "Bath & pool toys": "Giocattoli da bagno & piscina",
  "Electronic toys (battery-powered, children's tablets)": "Giocattoli elettronici (a batteria, tablet per bambini)",
  "Children's Activity & Sport": "Attività & sport per bambini",
  "Children's bicycles": "Biciclette per bambini",
  "Children's swim vests": "Giubbotti da nuoto per bambini",
  "Children's life jackets": "Giubbotti di salvataggio per bambini",
  "Children's shoes (sports, boots, sandals)": "Scarpe bambini (sport, stivali, sandali)",
  "Baby first-step shoes": "Scarpe primi passi",
  "Children's sunscreen": "Crema solare per bambini",
  "Stroller accessories (umbrella, rain cover, bag)": "Accessori passeggino (ombrello, copertura pioggia, borsa)",
  "Nasal aspirator & daily care": "Aspiratore nasale & cura quotidiana",
  "High chairs (portable, foldable)": "Seggioloni (portatili, pieghevoli)",
  "High chairs": "Seggioloni",
  "Umbrella strollers": "Passeggini leggeri",
  "Helmets & bike protectors": "Caschi & protezioni bici",
  "Miscellaneous categories": "Categorie varie",
  "Academic counselling": "Consulenza accademica",
  "Beds & cribs (wooden bed, rocking crib, travel crib)": "Letti & culle (letto in legno, culla a dondolo, lettino da viaggio)",
  "Certified distance courses": "Corsi a distanza certificati",
  "Changing pads & diaper balls": "Fasciatoi & palle per pannolini",
  "Swings & garden play": "Altalene & giochi da giardino",
  "Educational books (7–14 years)": "Libri educativi (7–14 anni)",
  "Picture books & fairy tales (0–6 years)": "Libri illustrati & fiabe (0–6 anni)",
  "Foreign languages": "Lingue straniere",
  "Hygiene & care": "Igiene & cura",
  "Anatomic sleep pillows": "Cuscini anatomici",
  "Building blocks & Lego": "Mattoncini & Lego",
  "Business & management": "Business & management",
};

const PHRASE_IT = {
  ...MANUAL_IT,
  ...Object.fromEntries(
    Object.keys(CATEGORY_EN_FR_EXTRA)
      .filter((en) => !MANUAL_IT[en])
      .map((en) => [en, applyItalianPhrases(en)]),
  ),
};

/** Auto IT for every hand-maintained EN exact label. */
const AUTO_IT = Object.fromEntries(
  Object.values(CAT_EN_EXACT).map((en) => [en, PHRASE_IT[en] ?? applyItalianPhrases(en)]),
);

export function categoryToItalian(en) {
  if (!en) return en;
  if (PHRASE_IT[en]) return PHRASE_IT[en];
  if (AUTO_IT[en]) return AUTO_IT[en];
  return applyItalianPhrases(en);
}
