/** English category labels → German (listing + subcategories). */
import { CAT_EN_EXACT } from "./category-en-from-ks.mjs";
import { applyGermanPhrases } from "./german-phrases.mjs";
import { CATEGORY_EN_FR_EXTRA } from "./category-en-fr-extra.mjs";

/** Full-phrase overrides — avoid word-chop (e.g. Home → Startseite). */
const MANUAL_DE = {
  "Electronics & Home Appliances": "Elektronik & Haushaltsgeräte",
  "Large Home Appliances": "Große Haushaltsgeräte",
  "Homes & Apartments": "Wohnungen & Häuser",
  "Furniture & Decor": "Möbel & Dekoration",
  "Clothing & Shoes": "Kleidung & Schuhe",
  "Children": "Kinder",
  "Sport & Outdoor": "Sport & Outdoor",
  "Jobs & Services": "Jobs & Dienstleistungen",
  "Construction & Installations": "Bau & Installationen",
  "Construction & Masonry": "Bau & Maurerarbeiten",
  "Plaster & Finishing": "Putz & Ausbau",
  "Tiling & Mosaic": "Fliesen & Mosaik",
  "Painting & Decor": "Malerarbeiten & Dekoration",
  "Roof repair & insulation": "Dachreparatur & Dämmung",
  "Floor repair & parquet": "Bodenreparatur & Parkett",
  "Window & door repair": "Fenster- & Türreparatur",
  "Heating & A/C installation": "Heizungs- & Klimaanlageninstallation",
  "Camera & alarm installation": "Kamera- & Alarmanlageninstallation",
  "Solar panel installation": "Solaranlageninstallation",
  "Furniture moving & transport": "Möbeltransport & Umzug",
  "General maintenance & repairs": "Allgemeine Wartung & Reparaturen",
  "Agriculture & Livestock": "Landwirtschaft & Viehzucht",
  "Education & Courses": "Bildung & Kurse",
  "Music & Hobbies": "Musik & Hobbys",
  "Pets & Animals": "Haustiere & Tiere",
  "Wanted to Buy": "Gesucht",
  "Free Gifts & Giveaways": "Gratisgeschenke & Verschenken — Von guten Menschen!",
  "Free Gifts & Giveaways — From kind people!": "Gratisgeschenke & Verschenken — Von guten Menschen!",
  "Cars": "Autos",
  "Motorcycles & Scooters": "Motorräder & Roller",
  "Trucks & Vans": "LKW & Transporter",
  "Auto Parts": "Autoteile",
  "Commercial & Office Space": "Gewerbe- & Büroflächen",
  "Phones": "Handys",
  "Computers & Laptops": "Computer & Laptops",
  "Motorcycles": "Motorräder",
  "Scooters": "Roller",
  "Trucks": "LKW",
  "Vans": "Transporter",
  "Buses": "Busse",
  "Tyres & Wheels": "Reifen & Felgen",
  "Body & Glass": "Karosserie & Glas",
  "Accessories": "Zubehör",
  "Apartments & Flats": "Wohnungen",
  "Houses": "Häuser",
  "Apartments for Rent": "Wohnungen zur Miete",
  "Apartments for Sale": "Wohnungen zum Verkauf",
  "Houses & Villas": "Häuser & Villen",
  "Land & Plots": "Grundstücke & Parzellen",
  "Garages": "Garagen",
  "Rooms for Rent": "Zimmer zur Miete",
  "Commercial Units for Rent": "Gewerbeeinheiten zur Miete",
  "Commercial Units for Sale": "Gewerbeeinheiten zum Verkauf",
  "Offices": "Büros",
  "Warehouses & Storage": "Lager & Lagerräume",
  "Industrial Buildings": "Industriegebäude",
  "Other Phones": "Andere Handys",
  "Phone Accessories": "Handyzubehör",
  "Laptops": "Laptops",
  "Desktop PCs": "Desktop-PCs",
  "Tablets": "Tablets",
  "Gaming & Consoles": "Gaming & Konsolen",
  "Drones": "Drohnen",
  "HVAC & Heating": "Heizung & Klima",
  "TVs & Projectors": "Fernseher & Projektoren",
  "Audio & Sound Equipment": "Audio & Tonausrüstung",
  "Cameras, Photo & Smartwatches": "Kameras, Foto & Smartwatches",
  "Televisions": "Fernseher",
  "Fridges & Washing Machines": "Kühlschränke & Waschmaschinen",
  "Air Conditioners": "Klimaanlagen",
  "Cookers & Ovens": "Herd & Backöfen",
  "Audio & Cameras": "Audio & Kameras",
  "Bedroom": "Schlafzimmer",
  "Living Room": "Wohnzimmer",
  "Kitchen": "Küche",
  "Bathroom & Sanitary": "Badezimmer & Sanitär",
  "Decor": "Dekoration",
  "Building Materials": "Baumaterialien",
  "Women's Clothing": "Damenbekleidung",
  "Men's Clothing": "Herrenbekleidung",
  "Shoes": "Schuhe",
  "Bags & Accessories": "Taschen & Accessoires",
  "Jewellery & Watches": "Schmuck & Uhren",
  "Perfumes": "Parfüms",
  "Toys": "Spielzeug",
  "Children's Clothing": "Kinderkleidung",
  "Strollers & Cribs": "Kinderwagen & Gitterbetten",
  "School Books": "Schulbücher",
  "Maternity Products": "Produkte für Schwangere",
  "Sports Equipment": "Sportausrüstung",
  "Bicycles & E-bikes": "Fahrräder & E-Bikes",
  "Hunting & Fishing": "Jagd & Angeln",
  "Camping & Outdoors": "Camping & Outdoor",
  "Musical Instruments": "Musikinstrumente",
  "Job Offers": "Stellenangebote",
  "Looking for Work": "Jobsuche",
  "Professional Services": "Professionelle Dienstleistungen",
  "Cleaning & Maintenance": "Reinigung & Wartung",
  "Construction & Renovation": "Bau & Renovierung",
  "Farm Animals": "Nutztiere",
  "Farm Machinery": "Landmaschinen",
  "Seeds & Seedlings": "Saatgut & Setzlinge",
  "Farm Produce": "Agrarprodukte",
  "Private Tutoring": "Privatunterricht",
  "Language Courses": "Sprachkurse",
  "IT Courses": "IT-Kurse",
  "Books & Materials": "Bücher & Materialien",
  "Instruments": "Instrumente",
  "Books & Magazines": "Bücher & Zeitschriften",
  "Collectibles": "Sammlerstücke",
  "Games & Toys": "Spiele & Spielzeug",
  "Dogs": "Hunde",
  "Cats": "Katzen",
  "Birds": "Vögel",
  "Other Animals": "Andere Tiere",
  "Pet Accessories": "Tierzubehör",
  "Homework Help": "Hausaufgabenhilfe",
  "Help with Applications": "Hilfe bei Bewerbungen",
  "Preschool education": "Vorschulerziehung",
  "Arts & creativity": "Kunst & Kreativität",
  "Professional training": "Berufsausbildung",
  "Educational music": "Musikalische Bildung",
  "Children's clothing & shoes": "Kinderkleidung & -schuhe",
  "Baby clothing (0-12 months)": "Babykleidung (0–12 Monate)",
  "Toddler clothing (1-5 years)": "Kleidung für Kleinkinder (1–5 Jahre)",
  "School clothing (6-14 years)": "Schulkleidung (6–14 Jahre)",
  "Furniture (wardrobes, changing tables, toy shelves)":
    "Möbel (Schränke, Wickeltische, Spielzeugregale)",
  "Nurseries & kindergartens": "Krippen & Kindergärten",
  "Bags & maternity accessories": "Taschen & Accessoires für Schwangere",
  "Human resources": "Personalwesen",
  "Baby handbag": "Baby-Handtasche",
  "School bag": "Schultasche",
  "Baby backpack (diaper bag)": "Baby-Rucksack (Wickeltasche)",
  "Certificates & diplomas": "Zertifikate & Diplome",
  "Financial certificates": "Finanzzertifikate",
  "IT certificates": "IT-Zertifikate",
  "Decor & night lights": "Dekoration & Nachtlichter",
  "Design & media": "Design & Medien",
  "Graphic design": "Grafikdesign",
  "Art education": "Kunsterziehung",
  "Health education": "Gesundheitserziehung",
  "Sun hats & UV protection": "Sonnenhüte & UV-Schutz",
  "Baby chairs & seats": "Babystühle & -sitze",
  "Car seats (group 0+, 1, 2/3)": "Kindersitze (Gruppe 0+, 1, 2/3)",
  "Car seat group 0+ (0-13 kg)": "Kindersitz Gruppe 0+ (0–13 kg)",
  "Car seat group 1 (9-18 kg)": "Kindersitz Gruppe 1 (9–18 kg)",
  "Car seat group 2/3 (15-36 kg)": "Kindersitz Gruppe 2/3 (15–36 kg)",
  "Portable high chairs": "Tragbare Hochstühle",
  "Strollers & transport": "Kinderwagen & Transport",
  "Classic strollers": "Klassische Kinderwagen",
  "Twin strollers": "Zwillingskinderwagen",
  "Costumes & play clothing": "Kostüme & Spielkleidung",
  "Sports costumes": "Sportbekleidung",
  "Bed & children's room": "Bett & Kinderzimmer",
  "Acting course": "Schauspielkurs",
  "Ballet course": "Ballettkurs",
  "First aid course": "Erste-Hilfe-Kurs",
  "Painting course": "Malkurs",
  "Professional courses": "Berufskurse",
  "Standard courses": "Standardkurse",
  "Technical courses": "Technische Kurse",
  "Books & school supplies": "Bücher & Schulbedarf",
  "Educational toys": "Lernspielzeug",
  "Classic toys (dolls, figures, cars, trains)": "Klassisches Spielzeug (Puppen, Figuren, Autos, Züge)",
  "Montessori toys": "Montessori-Spielzeug",
  "Musical toys": "Musikspielzeug",
  "Sand & beach toys": "Sand- & Strandspielzeug",
  "Logic games & educational puzzles": "Logikspiele & Lernpuzzle",
  "Board games (table games, puzzles, cards)": "Brettspiele (Tischspiele, Puzzle, Karten)",
  "Master's & doctorate": "Master & Promotion",
  "Baby carriers (kangaroo, wrap, sling)": "Babytragen (Känguru, Tuch, Sling)",
  "Bottle holders": "Flaschenhalter",
  "Financial support": "Finanzielle Unterstützung",
  "Corner & table edge protectors": "Ecken- & Tischkantenschutz",
  "Electrical outlet covers": "Steckdosenschutz",
  "Rain & sun covers for strollers": "Regen- & Sonnenschutz für Kinderwagen",
  "Project management": "Projektmanagement",
  "Critical thinking for children": "Kritisches Denken für Kinder",
  "Homeschooling": "Hausunterricht",
  "Private lessons": "Privatstunden",
  "Drawing & painting supplies": "Zeichen- & Malbedarf",
  "Baby audio monitor": "Babyphone (Audio)",
  "Baby video monitor (camera)": "Babyphone mit Kamera",
  "Diploma recognition": "Diplomanerkennung",
  "Online learning": "Online-Lernen",
  "Stroller organisers": "Kinderwagen-Organizer",
  "Maternity trousers & tops": "Umstandshosen & -oberteile",
  "Disposable diapers": "Einwegwindeln",
  "Reusable diapers": "Stoffwindeln",
  "Goethe exam preparation": "Goethe-Prüfungsvorbereitung",
  "IELTS preparation": "IELTS-Vorbereitung",
  "Exam preparation": "Prüfungsvorbereitung",
  "TOEFL preparation": "TOEFL-Vorbereitung",
  "Inflatable pools": "Aufblasbare Pools",
  "Pool & beach for children": "Pool & Strand für Kinder",
  "Breast pumps (electric & manual)": "Milchpumpen (elektrisch & manuell)",
  "Safety gates (stairs & rooms)": "Sicherheitsgitter (Treppen & Räume)",
  "Care products (stretch mark cream)": "Pflegeprodukte (Dehnungsstreifen-Creme)",
  "Skincare products (cream, shampoo, massage oil)": "Hautpflege (Creme, Shampoo, Massageöl)",
  "JavaScript programming": "JavaScript-Programmierung",
  "Python programming": "Python-Programmierung",
  "International exams": "Internationale Prüfungen",
  "Development centre": "Entwicklungszentrum",
  "Health & wellness": "Gesundheit & Wohlbefinden",
  "Bottles & feeding": "Flaschen & Ernährung",
  "Practical skills": "Praktische Fähigkeiten",
  "Private primary school": "Private Grundschule",
  "Primary education": "Grundschulbildung",
  "Scooters & skates": "Roller & Schlittschuhe",
  "Child safety": "Kindersicherheit",
  "Travel systems (stroller + car seat)": "Reisesysteme (Kinderwagen + Kindersitz)",
  "Sterilisers & bottle warmers": "Sterilisatoren & Flaschenwärmer",
  "Nursing bras & breastfeeding clothing": "Still-BHs & Stillkleidung",
  "Play mats & sensory stimulation": "Spielmatten & Sinnesförderung",
  "Music theory": "Musiktheorie",
  "Thermometer & health devices": "Thermometer & Gesundheitsgeräte",
  "Balls & sports equipment": "Bälle & Sportausrüstung",
  "IT training": "IT-Schulung",
  "Scooters & skis": "Roller & Skier",
  "Academic tutoring": "Akademische Nachhilfe",
  "Booster seats": "Sitzerhöhungen",
  "University & scholarships": "Universität & Stipendien",
  "Baby food & snacks": "Babynahrung & Snacks",
  "Feeding & nutrition": "Ernährung & Nahrung",
  "Baby bath tub": "Babybadewanne",
  "Swimwear & swimming": "Bademode & Schwimmen",
  "Winter clothing (coats, jackets, costumes)": "Winterkleidung (Mäntel, Jacken, Kostüme)",
  "Maternity clothing": "Umstandskleidung",
  "Summer clothing": "Sommerkleidung",
  "Video editing": "Videobearbeitung",
  "Cognitive development": "Kognitive Entwicklung",
  "Personal development": "Persönliche Entwicklung",
  "Software development": "Softwareentwicklung",
  "Study scholarships": "Studienstipendien",
  "Children's dishes & spoons": "Kindergeschirr & Löffel",
  "Notebooks & school supplies": "Hefte & Schulbedarf",
  "Toys & games": "Spielzeug & Spiele",
  "Bath & pool toys": "Bad- & Poolspielzeug",
  "Electronic toys (battery-powered, children's tablets)": "Elektronisches Spielzeug (batteriebetrieben, Kinder-Tablets)",
  "Children's Activity & Sport": "Kinderaktivitäten & Sport",
  "Children's bicycles": "Kinderfahrräder",
  "Children's swim vests": "Kinder-Schwimmwesten",
  "Children's life jackets": "Kinder-Rettungswesten",
  "Children's shoes (sports, boots, sandals)": "Kinderschuhe (Sport, Stiefel, Sandalen)",
  "Baby first-step shoes": "Erste-Schritt-Schuhe",
  "Children's sunscreen": "Kinder-Sonnencreme",
  "Stroller accessories (umbrella, rain cover, bag)": "Kinderwagen-Zubehör (Schirm, Regenschutz, Tasche)",
  "Nasal aspirator & daily care": "Nasensauger & tägliche Pflege",
  "High chairs (portable, foldable)": "Hochstühle (tragbar, klappbar)",
  "High chairs": "Hochstühle",
  "Umbrella strollers": "Buggy-Kinderwagen",
  "Helmets & bike protectors": "Helme & Fahrradschutz",
  "Miscellaneous categories": "Verschiedene Kategorien",
  "Academic counselling": "Studienberatung",
  "Beds & cribs (wooden bed, rocking crib, travel crib)": "Betten & Gitterbetten (Holzbett, Schaukelwiege, Reisebett)",
  "Certified distance courses": "Zertifizierte Fernkurse",
  "Changing pads & diaper balls": "Wickelauflagen & Windelkugeln",
  "Swings & garden play": "Schaukeln & Gartenspiel",
  "Educational books (7–14 years)": "Lernbücher (7–14 Jahre)",
  "Picture books & fairy tales (0–6 years)": "Bilderbücher & Märchen (0–6 Jahre)",
  "Foreign languages": "Fremdsprachen",
  "Hygiene & care": "Hygiene & Pflege",
  "Anatomic sleep pillows": "Anatomische Schlafkissen",
  "Building blocks & Lego": "Bausteine & Lego",
  "Business & management": "Business & Management",
};

const PHRASE_DE = {
  ...MANUAL_DE,
  ...Object.fromEntries(
    Object.keys(CATEGORY_EN_FR_EXTRA)
      .filter((en) => !MANUAL_DE[en])
      .map((en) => [en, applyGermanPhrases(en)]),
  ),
};

/** Auto DE for every hand-maintained EN exact label. */
const AUTO_DE = Object.fromEntries(
  Object.values(CAT_EN_EXACT).map((en) => [en, PHRASE_DE[en] ?? applyGermanPhrases(en)]),
);

export function categoryToGerman(en) {
  if (!en) return en;
  if (PHRASE_DE[en]) return PHRASE_DE[en];
  if (AUTO_DE[en]) return AUTO_DE[en];
  return applyGermanPhrases(en);
}
