/** English category labels → French (listing + subcategories). */
import { CAT_EN_EXACT } from "./category-en-from-ks.mjs";
import { applyFrenchPhrases } from "./french-phrases.mjs";
import { CATEGORY_EN_FR_EXTRA } from "./category-en-fr-extra.mjs";

/** Full-phrase overrides — avoid word-chop (e.g. Home → Accueil). */
const PHRASE_FR = {
  "Electronics & Home Appliances": "Électronique & électroménager",
  "Large Home Appliances": "Gros électroménager",
  "Homes & Apartments": "Logements & appartements",
  "Furniture & Decor": "Meubles & décoration",
  "Clothing & Shoes": "Vêtements & chaussures",
  "Children": "Enfants",
  "Sport & Outdoor": "Sport & plein air",
  "Jobs & Services": "Emploi & services",
  "Construction & Installations": "Construction & installations",
  "Construction & Masonry": "Construction & maçonnerie",
  "Plaster & Finishing": "Plâtre & finitions",
  "Tiling & Mosaic": "Carrelage & mosaïque",
  "Painting & Decor": "Peinture & décoration",
  "Roof repair & insulation": "Réparation de toiture & isolation",
  "Floor repair & parquet": "Réparation de sol & parquet",
  "Window & door repair": "Réparation fenêtres & portes",
  "Heating & A/C installation": "Installation chauffage & climatisation",
  "Camera & alarm installation": "Installation caméras & alarmes",
  "Solar panel installation": "Installation panneaux solaires",
  "Furniture moving & transport": "Déménagement & transport",
  "General maintenance & repairs": "Entretien & réparations générales",
  "Agriculture & Livestock": "Agriculture & élevage",
  "Education & Courses": "Éducation & cours",
  "Music & Hobbies": "Musique & loisirs",
  "Pets & Animals": "Animaux",
  "Wanted to Buy": "Je recherche à acheter",
  "Free Gifts & Giveaways": "Cadeaux & dons gratuits — De bonnes personnes !",
  "Free Gifts & Giveaways — From kind people!": "Cadeaux & dons gratuits — De bonnes personnes !",
  "Cars": "Voitures",
  "Motorcycles & Scooters": "Motos & scooters",
  "Trucks & Vans": "Camions & fourgons",
  "Auto Parts": "Pièces auto",
  "Commercial & Office Space": "Locaux commerciaux & bureaux",
  "Phones": "Téléphones",
  "Computers & Laptops": "Ordinateurs & portables",
  "Motorcycles": "Motos",
  "Scooters": "Scooters",
  "Trucks": "Camions",
  "Vans": "Fourgons",
  "Buses": "Bus",
  "Tyres & Wheels": "Pneus & jantes",
  "Body & Glass": "Carrosserie & vitres",
  "Accessories": "Accessoires",
  "Apartments & Flats": "Appartements",
  "Houses": "Maisons",
  "Apartments for Rent": "Appartements à louer",
  "Apartments for Sale": "Appartements à vendre",
  "Houses & Villas": "Maisons & villas",
  "Land & Plots": "Terrains & parcelles",
  "Garages": "Garages",
  "Rooms for Rent": "Chambres à louer",
  "Commercial Units for Rent": "Locaux commerciaux à louer",
  "Commercial Units for Sale": "Locaux commerciaux à vendre",
  "Offices": "Bureaux",
  "Warehouses & Storage": "Entrepôts & stockage",
  "Industrial Buildings": "Bâtiments industriels",
  "Other Phones": "Autres téléphones",
  "Phone Accessories": "Accessoires téléphone",
  "Laptops": "Ordinateurs portables",
  "Desktop PCs": "PC de bureau",
  "Tablets": "Tablettes",
  "Gaming & Consoles": "Gaming & consoles",
  "Drones": "Drones",
  "HVAC & Heating": "Chauffage & climatisation",
  "TVs & Projectors": "Téléviseurs & projecteurs",
  "Audio & Sound Equipment": "Audio & équipement sonore",
  "Cameras, Photo & Smartwatches": "Appareils photo & montres connectées",
  "Televisions": "Téléviseurs",
  "Fridges & Washing Machines": "Réfrigérateurs & lave-linge",
  "Air Conditioners": "Climatiseurs",
  "Cookers & Ovens": "Cuisinières & fours",
  "Audio & Cameras": "Audio & appareils photo",
  "Bedroom": "Chambre",
  "Living Room": "Salon",
  "Kitchen": "Cuisine",
  "Bathroom & Sanitary": "Salle de bain & sanitaires",
  "Decor": "Décoration",
  "Building Materials": "Matériaux de construction",
  "Women's Clothing": "Vêtements femme",
  "Men's Clothing": "Vêtements homme",
  "Shoes": "Chaussures",
  "Bags & Accessories": "Sacs & accessoires",
  "Jewellery & Watches": "Bijoux & montres",
  "Perfumes": "Parfums",
  "Toys": "Jouets",
  "Children's Clothing": "Vêtements enfants",
  "Strollers & Cribs": "Poussettes & lits bébé",
  "School Books": "Manuels scolaires",
  "Maternity Products": "Produits maternité",
  "Sports Equipment": "Équipement sportif",
  "Bicycles & E-bikes": "Vélos & vélos électriques",
  "Hunting & Fishing": "Chasse & pêche",
  "Camping & Outdoors": "Camping & plein air",
  "Musical Instruments": "Instruments de musique",
  "Job Offers": "Offres d'emploi",
  "Looking for Work": "Recherche d'emploi",
  "Professional Services": "Services professionnels",
  "Cleaning & Maintenance": "Nettoyage & entretien",
  "Construction & Renovation": "Construction & rénovation",
  "Farm Animals": "Animaux de ferme",
  "Farm Machinery": "Machines agricoles",
  "Seeds & Seedlings": "Graines & plants",
  "Farm Produce": "Produits agricoles",
  "Private Tutoring": "Cours particuliers",
  "Language Courses": "Cours de langues",
  "IT Courses": "Cours informatique",
  "Books & Materials": "Livres & matériel",
  "Instruments": "Instruments",
  "Books & Magazines": "Livres & magazines",
  "Collectibles": "Collections",
  "Games & Toys": "Jeux & jouets",
  "Dogs": "Chiens",
  "Cats": "Chats",
  "Birds": "Oiseaux",
  "Other Animals": "Autres animaux",
  "Pet Accessories": "Accessoires pour animaux",
  "Homework Help": "Aide aux devoirs",
  "Help with Applications": "Aide aux candidatures",
  "Preschool education": "Éducation préscolaire",
  "Arts & creativity": "Arts & créativité",
  "Professional training": "Formation professionnelle",
  "Educational music": "Musique éducative",
  "Children's clothing & shoes": "Vêtements & chaussures enfants",
  "Baby clothing (0-12 months)": "Vêtements bébé (0-12 mois)",
  "Toddler clothing (1-5 years)": "Vêtements tout-petit (1-5 ans)",
  "School clothing (6-14 years)": "Vêtements scolaires (6-14 ans)",
  "Furniture (wardrobes, changing tables, toy shelves)":
    "Meubles (armoires, tables à langer, étagères jouets)",
  "Nurseries & kindergartens": "Crèches & jardins d'enfants",
  "Bags & maternity accessories": "Sacs & accessoires maternité",
  ...CATEGORY_EN_FR_EXTRA,
};

/** Auto FR for every hand-maintained EN exact label. */
const AUTO_FR = Object.fromEntries(
  Object.values(CAT_EN_EXACT).map((en) => [en, PHRASE_FR[en] ?? applyFrenchPhrases(en)]),
);

export function categoryToFrench(en) {
  if (!en) return en;
  if (PHRASE_FR[en]) return PHRASE_FR[en];
  if (AUTO_FR[en]) return AUTO_FR[en];
  return applyFrenchPhrases(en);
}
