/** Phrase replacements for auto English UI (longest match first). */
export const EN_PHRASES = [
  ["Registrujte se ili prijavite se emailom i lozinkom", "Sign in or register with email and password"],
  ["Registrujte se emailom. Dobićete kod za potvrdu na email", "Register with email. You will receive a confirmation code by email"],
  ["Novi nalog: kod na email. Imate nalog? Email + lozinka — odmah prijava", "New account: code by email. Already registered? Email + password — sign in immediately"],
  ["Prijava telefonom nije aktivna. Registruj se emailom", "Phone sign-in is not active. Register with email"],
  ["Unesite kod iz SMS-a", "Enter the code from SMS"],
  ["Ke llogari me telefon?", "Have a phone account?"],
  ["Llogari e re me email?", "New email account?"],
  ["Registrujte se kao partner", "Register as partner"],
  ["Kontaktirajte nas", "Contact us"],
  ["Bëhu i pari që posto në këtë kategori dhe arrij mijëra blerës potencialë!", "Be the first to post in this category and reach thousands of potential buyers!"],
  ["Bëhu i pari që posto në këtë kategori!", "Be the first to post in this category!"],
  ["nënkategori të disponueshme", "subcategories available"],
  ["marka të disponueshme", "brands available"],
  ["Të gjitha shtetet", "All countries"],
  ["Zgjidh këtë kategori", "Choose this category"],
  ["Keni arritur limitin falas", "You have reached the free limit"],
  ["Mbushni portofolin", "Top up your wallet"],
  ["për shpallje", "per listing"],
  ["Shpallja u postua", "Listing posted successfully"],
  ["Balanca", "Balance"],
  ["shpallje të mbetura", "listings remaining"],
  ["Përmbajtja nuk kaloi kontrollin automatik", "Content did not pass automatic review"],
  ["Gjuha e shitjes nuk lejohet", "Selling language is not allowed"],
  ["fjalë e ndaluar", "blocked word"],
  ["Në këtë kategori çmimi është gjithmonë 0 €", "In this category the price is always €0"],
  ["Duke klikuar", "By clicking"],
  ["ju merrni përgjegjësi të plotë ligjore", "you accept full legal responsibility"],
  ["vërtetësinë e postimit tuaj", "for the accuracy of your listing"],
  ["Ndihmë", "Help"],
  ["Shpallje të mbetura", "Listings remaining"],
  ["Paguaj me kartë", "Pay by card"],
  ["Pagesa me kartë", "Card payment"],
  ["Mund të vazhdoni me postimin e njoftimit", "You can continue posting your listing"],
  ["Hyni në llogari për të parë udhëzimet e pagesës", "Sign in to see payment instructions"],
  ["Pagesa nuk u gjet", "Payment not found"],
  ["Pagesë bankare", "Bank transfer"],
  ["Transfer bankar për portofolin", "Bank transfer for wallet top-up"],
  ["Përfituesi", "Beneficiary"],
  ["Përshkruani problemin", "Describe the problem"],
  ["Rruga, nr. shtëpisë", "Street, house number"],
  ["Sportet Ajrore", "Air sports"],
  ["Kërko Pajisje Sportive", "Search sports equipment"],
  ["Lloji i sportit", "Sport type"],
  ["Lloji i pajisjes", "Equipment type"],
  ["Gjermania, Zvicër, Austri", "Germany, Switzerland, Austria"],
  ["Metodat e pagesës", "Payment methods"],
  ["KetuJemi — Bli & Shit", "KetuJemi — Buy & Sell"],
  ["platforma e shpalljeve falas", "free classifieds platform"],
  ["Verifikim SMS & Email", "SMS & email verification"],
  ["Posto falas", "Post for free"],
  ["20 kategori", "20 categories"],
  ["KetuJemi në 11 tregje", "KetuJemi in 11 markets"],
  ["Shiko të gjitha", "View all"],
  ["Dërgo Mesazh", "Send message"],
  ["Takohu me shitësin personalisht", "Meet the seller in person"],
  ["Kontrolloje produktin para pagesës", "Inspect the item before paying"],
  ["Mos dërgo para paraprakisht", "Do not send money in advance"],
  ["Raporto nëse vëren diçka të dyshimtë", "Report anything suspicious"],
  ["Fshi shpalljen?", "Delete listing?"],
  ["Kjo veprim nuk mund të zhbehet", "This action cannot be undone"],
  ["Gabim gjatë fshirjes", "Error while deleting"],
  ["Gabim gjatë postimit", "Error while posting"],
  ["Gabim gjate perditesimit", "Error while updating"],
  ["Titulli i shpalljes", "Listing title"],
  ["Pershkruani në detaje", "Describe in detail"],
  ["produktin ose shërbimin tuaj", "your product or service"],
  ["Me marrëveshje", "Negotiable"],
  ["çmimi është i negociueshëm", "price is open to offers"],
  ["Kliko për të zgjedhur foto", "Tap to choose photos"],
  ["nga pajisja jote", "from your device"],
  ["Ju lutemi prisni", "Please wait"],
  ["Detajet e automjetit", "Vehicle details"],
  ["Detajet e pronës", "Property details"],
  ["Detajet e telefonit", "Phone details"],
  ["Viti i prodhimit", "Year of manufacture"],
  ["Gjendja teknike", "Technical condition"],
  ["Numri dhomave", "Number of rooms"],
  ["Posto Shpalljen", "Post listing"],
  ["Promovo shpalljen", "Promote listing"],
  ["seksionin e promovuar", "promoted section"],
  ["Papërdorur", "Unused"],
  ["Ka qenë në përdorim", "Previously used"],
  ["Me defekt / aksident", "Defective / accident"],
  ["Maqedoni e Veriut", "North Macedonia"],
  ["Mal i Zi", "Montenegro"],
  ["Shqipëri", "Albania"],
  ["Kosovë", "Kosovo"],
  ["Gjermani", "Germany"],
  ["Zvicër", "Switzerland"],
  ["Francë", "France"],
  ["Itali", "Italy"],
  ["Angli", "United Kingdom"],
  ["SHBA", "USA"],
  ["Na kontaktoni", "Contact us"],
  ["Siguria online", "Online security"],
  ["Rreth KetuJemi", "About KetuJemi"],
  ["Hap shitore", "Open a shop"],
  ["Paketa VIP", "VIP packages"],
  ["Reklamoni", "Advertise"],
  ["Partneritet", "Partnership"],
  ["Operohet nga", "Operated by"],
  ["Të rekomanduara", "Featured"],
  ["Njoftimet e fundit", "Recent listings"],
  ["qytetet kryesore", "main cities"],
  ["Hyr për të kontaktuar shitësin", "Log in to contact the seller"],
  ["Nuk keni akses", "You do not have access"],
  ["Kyçu për të parë numrin", "Log in to see the phone number"],
  ["Dërgo SMS", "Send SMS"],
  ["Postime falas të mbetura", "Free posts remaining"],
  ["Ke arritur limitin", "You have reached the limit"],
  ["Registruj", "Register"],
  ["Prijavi", "Sign in"],
  ["prijavi", "sign in"],
  ["Prijavite", "Sign in"],
  ["prijavite", "sign in"],
  ["lozink", "password"],
  ["Lozinka", "Password"],
  ["Unesite", "Enter"],
  ["unesite", "enter"],
  ["Izaberite", "Select"],
  ["izaberite", "select"],
  ["Izaberi", "Select"],
  ["izaberi", "select"],
  ["Pošalji", "Send"],
  ["pošalji", "send"],
  ["Molimo", "Please"],
  ["sačekajte", "wait"],
  ["Nije pronađeno", "Not found"],
  ["nije pronađeno", "not found"],
  ["Nije uspjelo", "Failed"],
  ["nije uspjelo", "failed"],
  ["Učitavanje", "Uploading"],
  ["učitavanje", "uploading"],
  ["Objavi", "Post"],
  ["objavi", "post"],
  ["Oglasi", "Listings"],
  ["oglas", "listing"],
  ["oglasa", "listings"],
  ["Traži", "Search"],
  ["traži", "search"],
  ["Kërko", "Search"],
  ["kërko", "search"],
  ["Primijeni", "Apply"],
  ["Očisti", "Clear"],
  ["Nazad", "Back"],
  ["Uredi", "Edit"],
  ["Obriši", "Delete"],
  ["Otkaži", "Cancel"],
  ["Sačuvaj", "Save"],
  ["Čuvanje", "Saving"],
  ["Dodaj", "Add"],
  ["Besplatno", "Free"],
  ["besplatno", "free"],
  ["Danas", "Today"],
  ["Sve ", "All "],
  ["Sve.", "All."],
  ["Sve,", "All,"],
  ["Sve\b", "All"],
  ["Grad", "City"],
  ["grad", "city"],
  ["Cijena", "Price"],
  ["cijena", "price"],
  ["Kategorij", "Categor"],
  ["kategorij", "categor"],
  ["Filtri", "Filters"],
  ["filtri", "filters"],
  ["Stanje", "Condition"],
  ["stanje", "condition"],
  ["Lokacija", "Location"],
  ["lokacija", "location"],
  ["Kontakt", "Contact"],
  ["Opis", "Description"],
  ["Detalji", "Details"],
  ["Marka", "Brand"],
  ["marka", "brand"],
  ["Godina", "Year"],
  ["Prodaja", "Sale"],
  ["Izdavanje", "Rent"],
  ["Kupovina", "Buy"],
  ["Korišten", "Used"],
  ["korišten", "used"],
  ["Po dogovoru", "Negotiable"],
  ["Pomoć", "Help"],
  ["Pravila", "Rules"],
  ["Privatnost", "Privacy"],
  ["Kolačići", "Cookies"],
  ["Uslovi", "Terms"],
  ["Sigurnost", "Security"],
  ["Mediji", "Press"],
  ["O nama", "About us"],
  ["Dijaspora", "Diaspora"],
  ["Tržišt", "Market"],
  ["Potkategorij", "Subcategor"],
  ["potkategorij", "subcategor"],
  ["dostupn", "available"],
  ["ukupno", "total"],
  ["pregleda", "views"],
  ["Stranica", "Page"],
  ["stranica", "page"],
  ["Profil", "Profile"],
  ["profil", "profile"],
  ["Telefon", "Phone"],
  ["telefon", "phone"],
  ["Email", "Email"],
  ["Vazhdo", "Continue"],
  ["vazhdo", "continue"],
  ["Konfirmo", "Confirm"],
  ["konfirmo", "confirm"],
  ["Promijeni", "Change"],
  ["promijeni", "change"],
  ["Provjerite", "Check"],
  ["provjerite", "check"],
  ["Već ste", "You are already"],
  ["Kliknite", "Click"],
  ["kliknite", "click"],
  ["Koristite", "Use"],
  ["koristite", "use"],
  ["Zaboravili", "Forgot"],
  ["Resetujte", "Reset"],
  ["Broj telefona", "Phone number"],
  ["ndrysho numrin", "change number"],
  ["ndrysho emailin", "change email"],
  ["Kodi", "Code"],
  ["kodi", "code"],
  ["Verifik", "Verif"],
  ["Zahtjev", "Request"],
  ["zahtjev", "request"],
  ["Slanje", "Sending"],
  ["slanje", "sending"],
  ["Verifikacija", "Verification"],
  ["verifikacija", "verification"],
  ["Poslat", "Sent"],
  ["poslat", "sent"],
  ["kreiran", "created"],
  ["Log inr", "logged in"],
  ["Shpalljet", "Listings"],
  ["shpallje", "listing"],
  ["Njoftimet", "Listings"],
  ["njoftime", "listings"],
  ["Filtrat", "Filters"],
  ["Kategoria", "Category"],
  ["Qyteti", "City"],
  ["Çmimi", "Price"],
  ["Zbato", "Apply"],
  ["Pastro", "Clear"],
  ["Kthehu", "Back"],
  ["Edito", "Edit"],
  ["Fshi", "Delete"],
  ["Anulo", "Cancel"],
  ["Ruaj", "Save"],
  ["Duke ruajtur", "Saving"],
  ["Posto", "Post"],
  ["Falas", "Free"],
  ["Sot", "Today"],
  ["Të gjitha", "All"],
  ["Kategoritë", "Categories"],
  ["Përshkrimi", "Description"],
  ["Detajet", "Details"],
  ["Shitësi", "Seller"],
  ["Shitës privat", "Private seller"],
  ["Telefono", "Call"],
  ["Zgjidh", "Select"],
  ["Nënkategoria", "Subcategory"],
  ["Vendndodhja", "Location"],
  ["Kontakti", "Contact"],
  ["Fotot", "Photos"],
  ["Gjendja", "Condition"],
  ["Hyr", "Log in"],
  ["Dil", "Log out"],
  ["Kyçu", "Log in"],
  ["Nuk u gjet", "Not found"],
  ["Nuk ka", "No"],
  [" ende", " yet"],
  ["Bëhu i pari", "Be the first"],
  ["Mund të postoni", "You can post"],
  ["nga kudo", "from anywhere"],
  ["I ri", "New"],
  ["I përdorur", "Used"],
  ["Shumë mirë", "Very good"],
  ["I dëmtuar", "Damaged"],
  ["Lloji i karocerisë", "Body type"],
  ["Zgjidh markën", "Choose brand"],
  ["Zgjidh kategorinë", "Choose category"],
  ["Zgjidh tipin", "Choose type"],
  ["Zgjidh vitin", "Choose year"],
  ["Zgjidh qytetin", "Choose city"],
  ["Titulli", "Title"],
  ["Emri juaj", "Your name"],
  ["Nr. telefonit", "Phone number"],
  ["Kryesore", "Main"],
  ["Shto foto", "Add photo"],
  ["Duke ngarkuar", "Uploading"],
  ["\\bPo\\b", "Yes"],
  ["Jo", "No"],
  ["Benzinë", "Petrol"],
  ["Naftë", "Diesel"],
  ["Elektrik", "Electric"],
  ["Hibrid", "Hybrid"],
  ["Gaz (LPG)", "LPG"],
  ["Tjetër", "Other"],
  ["Manuale", "Manual"],
  ["Automatike", "Automatic"],
  ["Gjysëm-automatike", "Semi-automatic"],
  ["I mobiluar", "Furnished"],
  ["Pa mobilje", "Unfurnished"],
  ["Pjesërisht i mobiluar", "Partly furnished"],
  ["E zezë", "Black"],
  ["E bardhë", "White"],
  ["E kaltër", "Blue"],
  ["E kuqe", "Red"],
  ["E gjelbër", "Green"],
  ["E verdhë", "Yellow"],
  ["Kafe", "Brown"],
  ["Vjollcë", "Purple"],
  ["Portokalli", "Orange"],
  ["Operater platforme", "Platform operator"],
  ["Pravni operater", "Legal operator"],
  ["Naša misija", "Our mission"],
  ["Gdje radimo", "Where we operate"],
  ["Šta je dozvoljeno", "What is allowed"],
  ["Šta je zabranjeno", "What is prohibited"],
  ["Jasna pravila", "Clear rules"],
  ["besplatne oglase", "free classifieds"],
  ["međunarodnih tržišta", "international markets"],
  ["Sjeverna Makedonija", "North Macedonia"],
  ["Crna Gora", "Montenegro"],
  ["Albanija", "Albania"],
  ["Njemačka", "Germany"],
  ["Švicarska", "Switzerland"],
  ["Austrija", "Austria"],
  ["Francuska", "France"],
  ["Italija", "Italy"],
  ["Engleska", "United Kingdom"],
  ["Pitanja i podrška", "Questions and support"],
  ["Lloji i pronës", "Property type"],
  ["Lloji i lokales", "Premises type"],
  ["Lloji i lokales", "Commercial space type"],
  ["Lokale & Zyrë", "Commercial & Office"],
  ["Kërko hapësira", "Search spaces"],
  ["hapësira afariste", "commercial premises"],
  ["objekte industriale", "industrial properties"],
  ["Rreth KetuJemi", "About KetuJemi"],
  ["platforma e zhvilluar", "platform built"],
  ["Misioni ynë", "Our mission"],
  ["Ku operojmë", "Where we operate"],
  ["Tregjet zyrtare", "Official markets"],
  ["diaspora shqiptare", "Albanian diaspora"],
  ["Kushtet e përdorimit", "Terms of use"],
  ["Politika e privatësisë", "Privacy policy"],
  ["Rregullat e platformës", "Platform rules"],
  ["Pyetjet e shpeshta", "Frequently asked questions"],
  ["Siguria e blerësve", "Buyer safety"],
  ["Si funksionon", "How it works"],
  ["Çfarë është e ndaluar", "What is not allowed"],
  ["Çfarë lejohet", "What is allowed"],
  ["Kohëzgjatja e shpalljes", "Listing duration"],
  ["Limiti i postimeve", "Posting limit"],
  ["Paketat e kreditit", "Credit packages"],
  ["Na kontaktoni", "Contact us"],
  ["Formulari i kontaktit", "Contact form"],
  ["Emri dhe mbiemri", "Full name"],
  ["Mesazhi juaj", "Your message"],
  ["Dërgo mesazhin", "Send message"],
  ["Rregullat e Platformës", "Platform rules"],
  ["Operatori i platformës", "Platform operator"],
  ["Termat dhe Kushtet", "Terms and conditions"],
  ["Politika e Privatësisë", "Privacy policy"],
  ["Politika e Cookies", "Cookie policy"],
  ["Pyetjet e Shpeshta (FAQ)", "Frequently asked questions (FAQ)"],
  ["Siguria Online", "Online security"],
  ["Na Kontaktoni", "Contact us"],
  ["Hap Shitoren Tënde", "Open your shop"],
  ["Reklamoni në KetuJemi.com", "Advertise on KetuJemi.com"],
  ["Bashkëpunim & Partneritet", "Cooperation & partnership"],
  ["Rregullorja e Bizneseve", "Business rules"],
  [
    "KetuJemi — Bli & Shit është platforma e shpalljeve falas në 11 tregje: Kosovë, Shqipëri, Maqedoni, Mal i Zi dhe diaspora shqiptare.",
    "KetuJemi — Buy & Sell is a free classifieds platform across 11 markets: Kosovo, Albania, North Macedonia, Montenegro and the Albanian diaspora.",
  ],
  [
    "KetuJemi.com është një platformë e zhvilluar nga ekipi i REVOLUTION INVEST Sh.p.k. për të ndihmuar tregun lokal dhe diasporën shqiptare — shpejt, thjesht dhe në mënyrë të sigurt.",
    "KetuJemi.com is a platform built by REVOLUTION INVEST Sh.p.k. to help local markets and the Albanian diaspora — quickly, simply and safely.",
  ],
  [
    "Operatori ligjor: REVOLUTION INVEST Sh.p.k., Ferizaj, Kosovë (NRB 811314567).",
    "Legal operator: REVOLUTION INVEST Sh.p.k., Ferizaj, Kosovo (NRB 811314567).",
  ],
  [
    "Lidhim blerësit dhe shitësit shpejt, thjesht dhe në mënyrë të sigurt — pa komisione të fshehura për postimin bazë.",
    "We connect buyers and sellers quickly, simply and safely — with no hidden fees for basic posting.",
  ],
  [
    "Platforma shërben si hapësirë ndërmjetëse; marrëveshja e çmimit dhe dorëzimit bëhet drejtpërdrejt mes palëve.",
    "The platform is an intermediary only; price and delivery are agreed directly between the parties.",
  ],
  [
    "Kosovë, Shqipëri, Maqedoni e Veriut, Mal i Zi",
    "Kosovo, Albania, North Macedonia, Montenegro",
  ],
  [
    "Diaspora: Gjermani, Zvicër, Austri, Francë, Itali, Angli, SHBA",
    "Diaspora: Germany, Switzerland, Austria, France, Italy, UK, USA",
  ],
  [
    "Për pyetje, partneritete ose mbështetje: info@ketujemi.com dhe support@ketujemi.com, ose përdorni formularin te «Na kontaktoni».",
    "For questions, partnerships or support: info@ketujemi.com and support@ketujemi.com, or use the «Contact us» form.",
  ],
  [
    "Rregullat e Platformës",
    "Platform rules",
  ],
  [
    "Rregulla të qarta për postime të pastra dhe të besueshme për të gjithë përdoruesit.",
    "Clear rules for clean, trustworthy listings for all users.",
  ],
  [
    "Termat dhe Kushtet",
    "Terms and conditions",
  ],
  [
    "Politika e Privatësisë",
    "Privacy policy",
  ],
  [
    "Si i trajtojmë të dhënat tuaja — thjesht dhe transparent.",
    "How we handle your data — simply and transparently.",
  ],
  [
    "Pyetjet e Shpeshta (FAQ)",
    "Frequently asked questions (FAQ)",
  ],
  [
    "Njoftime të vërteta, në kategorinë e duhur, me foto dhe përshkrim të qartë",
    "Genuine listings in the right category, with clear photos and description",
  ],
  [
    "Çmim real ose shënim i qartë nëse është falas / me marrëveshje",
    "A real price or a clear note if free / negotiable",
  ],
  [
    "Një produkt ose shërbim për njoftim (jo reklamë e përgjithshme)",
    "One product or service per listing (not generic advertising)",
  ],
  [
    "Spam, mashtrim, përmbajtje ofenduese ose e paligjshme",
    "Spam, fraud, offensive or illegal content",
  ],
  [
    "Plotësisht falas për përdoruesit e thjeshtë.",
    "Completely free for private users.",
  ],
  [
    "Na Kontaktoni",
    "Contact us",
  ],
  [
    "Formulari i kontaktit",
    "Contact form",
  ],
  [
    "Dërgo Mesazhin",
    "Send message",
  ],
  // Montenegrin (MNE) → English for static pages
  ["O KetuJemi.com", "About KetuJemi.com"],
  [
    "KetuJemi.com je jedna od najvećih platformi za besplatne oglase na 11 međunarodnih tržišta.",
    "KetuJemi.com is one of the largest free classifieds platforms across 11 international markets.",
  ],
  ["Operater platforme", "Platform operator"],
  [
    "KetuJemi.com je platforma koju je razvio tim REVOLUTION INVEST Sh.p.k. da pomogne lokalnom tržištu i dijaspori — brzo, jednostavno i sigurno.",
    "KetuJemi.com is a platform built by the REVOLUTION INVEST Sh.p.k. team to help local markets and the diaspora — quickly, simply and safely.",
  ],
  [
    "Pravni operater: REVOLUTION INVEST Sh.p.k., Ferizaj, Kosovo (NRB 811314567).",
    "Legal operator: REVOLUTION INVEST Sh.p.k., Ferizaj, Kosovo (NRB 811314567).",
  ],
  ["Naša misija", "Our mission"],
  [
    "Brzo, čisto i sigurno povezivanje kupaca i prodavaca — bez skrivenih provizija za osnovno objavljivanje.",
    "Fast, clean and safe connections between buyers and sellers — no hidden fees for basic posting.",
  ],
  [
    "Platforma je posrednik; dogovor o cijeni i predaji je direktno između strana.",
    "The platform is an intermediary; price and handover are agreed directly between the parties.",
  ],
  ["Gdje radimo", "Where we operate"],
  [
    "Kosovo, Albanija, Sjeverna Makedonija, Crna Gora",
    "Kosovo, Albania, North Macedonia, Montenegro",
  ],
  [
    "Dijaspora: Njemačka, Švicarska, Austrija, Francuska, Italija, Engleska, SAD",
    "Diaspora: Germany, Switzerland, Austria, France, Italy, UK, USA",
  ],
  [
    "Pitanja i podrška: info@ketujemi.com i support@ketujemi.com, ili formular «Kontaktirajte nas».",
    "Questions and support: info@ketujemi.com and support@ketujemi.com, or the «Contact us» form.",
  ],
  ["Pravila platforme", "Platform rules"],
  [
    "Jasna pravila za čiste i pouzdane oglase za sve korisnike.",
    "Clear rules for clean, trustworthy listings for all users.",
  ],
  ["Šta je dozvoljeno", "What is allowed"],
  [
    "Istiniti oglasi u odgovarajućoj kategoriji, sa jasnim fotografijama i opisom",
    "Genuine listings in the right category, with clear photos and description",
  ],
  [
    "Stvarna cijena ili jasna napomena ako je besplatno / po dogovoru",
    "A real price or a clear note if free / negotiable",
  ],
  ["Jedan proizvod ili usluga po oglasu", "One product or service per listing"],
  ["Duplikati", "Duplicates"],
  [
    "Ako ponovo objavite isti oglas (isti naslov i opis), stari se automatski briše i ostaje samo novi.",
    "If you post the same listing again (same title and description), the old one is deleted automatically and only the new one remains.",
  ],
  [
    "Potrebno je najmanje 30 sekundi između dvije uzastopne objave.",
    "You must wait at least 30 seconds between two consecutive posts.",
  ],
  ["Limiti objava (10 mjesečno po glavnoj kategoriji)", "Posting limits (10 per month per main category)"],
  [
    "Svaki korisnik ima **10 besplatnih objava mjesečno** po **glavnoj kategoriji** (20). Potkategorije se broje unutar glavne — ne zasebno.",
    "Each user has **10 free posts per month** per **main category** (20 categories). Subcategories count within the main category — not separately.",
  ],
  [
    "Broj se resetuje svakog kalendarskog mjeseca. Nema posebnog limita «10 aktivnih odjednom».",
    "The count resets every calendar month. There is no separate «10 active at once» limit.",
  ],
  [
    "Kada premašite mjesečni limit, kupite kredit (Paket S / M / L) — Stripe:",
    "When you exceed the monthly limit, buy wallet credit (Package S / M / L) — Stripe:",
  ],
  [
    "Paket S — €5 (~16 plaćenih objava, €0.30 po objavi iz novčanika)",
    "Package S — €5 (~16 paid posts, €0.30 per post from wallet)",
  ],
  ["Paket M — €10 (~33 objave)", "Package M — €10 (~33 posts)"],
  ["Paket L — €20 (~66 objava)", "Package L — €20 (~66 posts)"],
  [
    "Kredit ne ističe dok se ne potroši. Do 10 stvarnih fotografija po oglasu.",
    "Credit does not expire until used. Up to 10 real photos per listing.",
  ],
  [
    "Trajanje oglasa (3 mjeseca) — različito od limita 10",
    "Listing duration (3 months) — separate from the limit of 10",
  ],
  [
    "Svaki oglas je aktivan **do 3 mjeseca (90 dana)** od objave, zatim se **automatski uklanja** ako ga sami ne obrišete.",
    "Each listing stays active **for up to 3 months (90 days)** from posting, then is **removed automatically** unless you delete it sooner.",
  ],
  [
    "Ovo **nije** isto što i limit 10/mjesečno: mjesečni limit je koliko puta **objavite**; rok od 3 mjeseca je koliko **dugo** oglas stoji online.",
    "This is **not** the same as the 10/month limit: the monthly limit is how often you **post**; the 3-month period is how **long** a listing stays online.",
  ],
  ["Šta je zabranjeno", "What is not allowed"],
  [
    "Spam, prevara, uvredljiv ili nezakonit sadržaj",
    "Spam, fraud, offensive or illegal content",
  ],
  [
    "Stock fotografije bez veze sa stvarnim proizvodom",
    "Stock photos unrelated to the actual item",
  ],
  [
    "Više telefona ili emailova za zaobilaženje pravila",
    "Multiple phone numbers or emails to bypass the rules",
  ],
  ["Prijavljivanje", "Reporting"],
  [
    "Sumnjiv oglas? Kliknite «Prijavi» ili pišite na support@ketujemi.com — reagujemo u roku od 24 sata.",
    "Suspicious listing? Click «Report» or email support@ketujemi.com — we respond within 24 hours.",
  ],
  ["Kontaktirajte nas", "Contact us"],
  ["Pošaljite poruku", "Send message"],
  ["Uslovi korišćenja", "Terms of use"],
  ["Politika privatnosti", "Privacy policy"],
  ["Politika kolačića", "Cookie policy"],
  ["Sigurnost online", "Online security"],
  ["Često postavljana pitanja", "Frequently asked questions"],
  ["Uslovi i odredbe", "Terms and conditions"],
  [
    "Korišćenjem KetuJemi.com prihvatate sljedeće uslove pravnog operatera platforme.",
    "By using KetuJemi.com you accept the following terms of the platform's legal operator.",
  ],
  ["Pravni subjekt i platforma", "Legal entity and platform"],
  [
    "Platformu KetuJemi.com (Bli & Shit) upravlja i nudi REVOLUTION INVEST Sh.p.k., sa sjedištem u Ferizaju, Republika Kosovo.",
    "KetuJemi.com (Buy & Sell) is operated by REVOLUTION INVEST Sh.p.k., based in Ferizaj, Republic of Kosovo.",
  ],
  [
    "Plaćanja za usluge platforme (novčanik, VIP/TOP, reklame i slično) vrše se u ime ovog subjekta. KetuJemi.com je trgovački naziv; pravni odnos je sa REVOLUTION INVEST Sh.p.k.",
    "Payments for platform services (wallet, VIP/TOP, advertising, etc.) are made on behalf of this entity. KetuJemi.com is a trade name; the legal relationship is with REVOLUTION INVEST Sh.p.k.",
  ],
  ["Službeni podaci operatera:", "Official operator details:"],
  ["Puno ime: REVOLUTION INVEST Sh.p.k.", "Full name: REVOLUTION INVEST Sh.p.k."],
  ["NRB (broj registracije biznisa): 811314567", "NRB (business registration number): 811314567"],
  ["Sjedište: Ferizaj, Republika Kosovo", "Registered office: Ferizaj, Republic of Kosovo"],
  ["Uloga platforme", "Role of the platform"],
  [
    "KetuJemi.com je samo posrednički prostor. REVOLUTION INVEST Sh.p.k. nije strana u ugovoru o prodaji robe između korisnika.",
    "KetuJemi.com is only an intermediary space. REVOLUTION INVEST Sh.p.k. is not a party to sales contracts between users.",
  ],
  [
    "Korisnik snosi punu pravnu odgovornost za svaki objavljeni oglas.",
    "The user bears full legal responsibility for every listing they publish.",
  ],
  ["Ograničena odgovornost za robu i usluge", "Limited liability for goods and services"],
  [
    "KetuJemi.com ne kupuje, ne prodaje i ne posjeduje proizvode u oglasima. Svaka transakcija (cijena, plaćanje, isporuka, garancija) je dogovor direktno između kupca i prodavca.",
    "KetuJemi.com does not buy, sell or own the products in listings. Every transaction (price, payment, delivery, warranty) is agreed directly between buyer and seller.",
  ],
  [
    "Ne garantujemo kvalitet, stanje, zakonitost ili dostupnost robe ili usluga koje objavljuju drugi korisnici.",
    "We do not guarantee the quality, condition, legality or availability of goods or services posted by other users.",
  ],
  [
    "Nismo odgovorni za direktnu ili indirektnu štetu od korišćenja platforme, neslaganja između strana, plaćanja van platforme ili radnji trećih lica.",
    "We are not liable for direct or indirect damage from use of the platform, disputes between parties, off-platform payments or third-party actions.",
  ],
  [
    "Naša maksimalna odgovornost, gdje zakon dozvoljava, ograničena je na iznos plaćen za usluge platforme (paketi, VIP, TOP) u posljednjih 12 mjeseci — ne za vrijednost robe prodate među korisnicima.",
    "Our maximum liability, where the law allows, is limited to amounts paid for platform services (packages, VIP, TOP) in the last 12 months — not the value of goods sold between users.",
  ],
  ["Politika povrata i novčanik", "Refunds and wallet policy"],
  [
    "Kako tretiramo vaše podatke — jednostavno i transparentno.",
    "How we handle your data — simply and transparently.",
  ],
  ["Šta prikupljamo", "What we collect"],
  ["Zašto ih koristimo", "Why we use them"],
  ["Čuvanje i prava", "Storage and your rights"],
  [
    "Podaci su šifrovani. Ne prodajemo ih trećim stranama za marketing.",
    "Data is encrypted. We do not sell it to third parties for marketing.",
  ],
  [
    "Možete zatražiti ispravku ili brisanje na support@ketujemi.com.",
    "You may request correction or deletion at support@ketujemi.com.",
  ],
  ["Politika kolačića (Cookies)", "Cookie policy"],
  [
    "Kako koristimo kolačiće na KetuJemi.com.",
    "How we use cookies on KetuJemi.com.",
  ],
  ["Kontakt informacije", "Contact information"],
  [
    "Za pravna pitanja, usluge platforme, prijave ili podršku:",
    "For legal questions, platform services, reports or support:",
  ],
  [
    "Radno vrijeme: Ponedjeljak – Petak, 09:00 – 17:00",
    "Working hours: Monday – Friday, 09:00 – 17:00",
  ],
];

export function applyEnglishPhrases(text) {
  let s = text;
  const ordered = [...EN_PHRASES].sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of ordered) {
    if (from.includes("\\b")) {
      s = s.replace(new RegExp(from, "gi"), to);
    } else {
      s = s.split(from).join(to);
    }
  }
  return s;
}
