/** English → French phrase replacements (longest match first). */
export const FR_PHRASES = [
  ["Sign in or register with email and password", "Connectez-vous ou inscrivez-vous avec e-mail et mot de passe"],
  ["Register with email. You will receive a confirmation code by email", "Inscrivez-vous par e-mail. Vous recevrez un code de confirmation par e-mail"],
  ["New account: code by email. Already registered? Email + password — sign in immediately", "Nouveau compte : code par e-mail. Déjà inscrit ? E-mail + mot de passe — connexion immédiate"],
  ["Phone sign-in is not active. Register with email", "La connexion par téléphone n'est pas active. Inscrivez-vous par e-mail"],
  ["Enter the code from SMS.", "Saisissez le code reçu par SMS."],
  ["Enter the code from SMS", "Saisissez le code reçu par SMS"],
  ["Have a phone account?", "Vous avez un compte téléphone ?"],
  ["New email account?", "Nouveau compte e-mail ?"],
  ["Register as partner", "S'inscrire comme partenaire"],
  ["Contact us", "Nous contacter"],
  ["Be the first to post in this category and reach thousands of potential buyers!", "Soyez le premier à publier dans cette catégorie et touchez des milliers d'acheteurs potentiels !"],
  ["Be the first to post in this category!", "Soyez le premier à publier dans cette catégorie !"],
  ["subcategories available", "sous-catégories disponibles"],
  ["brands available", "marques disponibles"],
  ["All countries", "Tous les pays"],
  ["Choose this category", "Choisir cette catégorie"],
  ["You have reached the free limit", "Vous avez atteint la limite gratuite"],
  ["Top up your wallet", "Recharger votre portefeuille"],
  ["per listing", "par annonce"],
  ["Listing posted successfully", "Annonce publiée avec succès"],
  ["Balance", "Solde"],
  ["listings remaining", "annonces restantes"],
  ["Content did not pass automatic review", "Le contenu n'a pas passé la vérification automatique"],
  ["Selling language is not allowed", "Langage de vente non autorisé"],
  ["blocked word", "mot interdit"],
  ["In this category the price is always €0", "Dans cette catégorie le prix est toujours 0 €"],
  ["By clicking", "En cliquant"],
  ["you accept full legal responsibility", "vous acceptez l'entière responsabilité légale"],
  ["for the accuracy of your listing", "pour l'exactitude de votre annonce"],
  ["Sign up", "S'inscrire"],
  ["Log in", "Connexion"],
  ["Home", "Accueil"],
  ["Open menu", "Ouvrir le menu"],
  ["Menu", "Menu"],
  ["Help", "Aide"],
  ["TOP LISTINGS", "ANNONCES TOP"],
  ["Listings", "Annonces"],
  ["Our trusted partners", "Nos partenaires de confiance"],
  ["Listings remaining", "Annonces restantes"],
  ["Pay by card", "Payer par carte"],
  ["Card payment", "Paiement par carte"],
  ["You can continue posting your listing", "Vous pouvez continuer à publier votre annonce"],
  ["Sign in to see payment instructions", "Connectez-vous pour voir les instructions de paiement"],
  ["Payment not found", "Paiement introuvable"],
  ["Bank transfer", "Virement bancaire"],
  ["Bank transfer for wallet top-up", "Virement bancaire pour recharger le portefeuille"],
  ["Beneficiary", "Bénéficiaire"],
  ["Describe the problem", "Décrivez le problème"],
  ["Street, house number", "Rue, numéro"],
  ["Air sports", "Sports aériens"],
  ["Search sports equipment", "Rechercher équipement sportif"],
  ["Sport type", "Type de sport"],
  ["Equipment type", "Type d'équipement"],
  ["Germany, Switzerland, Austria", "Allemagne, Suisse, Autriche"],
  ["Payment methods", "Modes de paiement"],
  ["KetuJemi — Buy & Sell", "KetuJemi — Acheter et vendre"],
  ["free classifieds platform", "plateforme d'annonces gratuite"],
  ["Buy & Sell", "Acheter et vendre"],
  ["Shops", "Boutiques"],
  ["Search listings", "Rechercher des annonces"],
  ["Search", "Rechercher"],
  ["Filters", "Filtres"],
  ["Category", "Catégorie"],
  ["City", "Ville"],
  ["Min price", "Prix min."],
  ["Max price", "Prix max."],
  ["Apply", "Appliquer"],
  ["Clear", "Effacer"],
  ["No listings found", "Aucune annonce trouvée"],
  ["Try changing filters or post a new listing", "Modifiez les filtres ou publiez une nouvelle annonce"],
  ["Post listing", "Publier une annonce"],
  ["Post for free", "Publier gratuitement"],
  ["View all", "Tout voir"],
  ["Categories", "Catégories"],
  ["Back", "Retour"],
  ["Edit", "Modifier"],
  ["Delete", "Supprimer"],
  ["Cancel", "Annuler"],
  ["Save changes", "Enregistrer"],
  ["Saving", "Enregistrement"],
  ["Description", "Description"],
  ["Details", "Détails"],
  ["Seller", "Vendeur"],
  ["Private seller", "Vendeur particulier"],
  ["Call", "Appeler"],
  ["Share", "Partager"],
  ["All", "Tout"],
  ["Yes", "Oui"],
  ["No", "Non"],
  ["About us", "À propos"],
  ["Privacy", "Confidentialité"],
  ["Terms", "Conditions"],
  ["Security", "Sécurité"],
  ["FAQ", "FAQ"],
  ["Contact", "Contact"],
  ["Refresh", "Actualiser"],
  ["Page could not load", "La page n'a pas pu se charger"],
  ["Shop not found", "Boutique introuvable"],
  ["Back to home", "Retour à l'accueil"],
  ["About the shop", "À propos de la boutique"],
  ["Map", "Carte"],
  ["Shop listings", "Annonces de la boutique"],
  ["No active listings at the moment.", "Aucune annonce active pour le moment."],
  ["Negotiable", "Négociable"],
  ["active listings", "annonces actives"],
  ["Post New Listing", "Publier une nouvelle annonce"],
  ["Delete listing?", "Supprimer l'annonce ?"],
  ["This cannot be undone. The listing will be permanently removed.", "Cette action est irréversible. L'annonce sera définitivement supprimée."],
  ["Welcome! Your shop is ready — post your first listing now and start selling!", "Bienvenue ! Votre boutique est prête — publiez votre première annonce et commencez à vendre !"],
  ["Post Your First Listing", "Publiez votre première annonce"],
  ["Edit Shop", "Modifier la boutique"],
  ["Delete Shop", "Supprimer la boutique"],
  ["Delete shop?", "Supprimer la boutique ?"],
  ["Are you sure? This will delete your shop and all your listings.", "Êtes-vous sûr ? Cela supprimera votre boutique et toutes vos annonces."],
  ["Save", "Enregistrer"],
  ["Shop updated.", "Boutique mise à jour."],
  ["Error saving shop.", "Erreur lors de l'enregistrement de la boutique."],
  ["Shop deleted.", "Boutique supprimée."],
  ["Error deleting shop.", "Erreur lors de la suppression de la boutique."],
  ["My Shop", "Ma boutique"],
  ["Verified Shop", "Boutique vérifiée"],
  ["Approved", "Approuvé"],
  ["Pending", "En attente"],
  ["Manage Listings", "Gérer les annonces"],
  ["Total listings", "Annonces au total"],
  ["Total views", "Vues au total"],
  ["View shop", "Voir la boutique"],
  ["No active listings from your shop.", "Aucune annonce active de votre boutique."],
  ["Shop name", "Nom de la boutique"],
  ["Address", "Adresse"],
  ["Area/Neighbourhood", "Quartier"],
  ["Apply for a shop", "Demander une boutique"],
  ["Sign in / Register", "Connexion / Inscription"],
  ["Shop identity", "Identité de la boutique"],
  ["Business description", "Description de l'activité"],
  ["Main category", "Catégorie principale"],
  ["Location", "Localisation"],
  ["Country", "Pays"],
  ["Region/Neighbourhood", "Région/Quartier"],
  ["Full address", "Adresse complète"],
  ["Social media", "Réseaux sociaux"],
  ["Fill in at least one social network", "Renseignez au moins un réseau social"],
  ["Contact name", "Nom du contact"],
  ["Phone number", "Numéro de téléphone"],
  ["Submit Shop Request", "Envoyer la demande de boutique"],
  ["Uploading logo...", "Envoi du logo..."],
  ["Help from our system", "Aide de notre système"],
  ["Generate", "Générer"],
  ["Generating...", "Génération..."],
  ["Frequently Asked Questions", "Questions fréquentes"],
  ["FREQUENTLY ASKED QUESTIONS", "QUESTIONS FRÉQUENTES"],
  ["Ready to grow your business?", "Prêt à développer votre activité ?"],
  ["Apply as partner", "Devenir partenaire"],
  ["Apply as Partner", "Devenir partenaire"],
  ["Apply as VIP Partner", "Devenir partenaire VIP"],
  ["Business packages", "Forfaits entreprise"],
  ["BUSINESS PACKAGES", "FORFAITS ENTREPRISE"],
  ["Choose the package that fits your business", "Choisissez le forfait adapté à votre activité"],
  ["Partner not found", "Partenaire introuvable"],
  ["This profile is not available.", "Ce profil n'est pas disponible."],
  ["Partner", "Partenaire"],
  ["VIP Partner", "Partenaire VIP"],
  ["Contact & social", "Contact et réseaux sociaux"],
  ["About KetuJemi.com", "À propos de KetuJemi.com"],
  ["Platform rules", "Règles de la plateforme"],
  ["OFFICIAL MARKETS", "MARCHÉS OFFICIELS"],
  ["+8 diaspora countries", "+8 pays de la diaspora"],
  ["North Macedonia", "Macédoine du Nord"],
  ["Kosovo", "Kosovo"],
  ["Albania", "Albanie"],
  ["Montenegro", "Monténégro"],
  ["Germany", "Allemagne"],
  ["Switzerland", "Suisse"],
  ["Austria", "Autriche"],
  ["France", "France"],
  ["Italy", "Italie"],
  ["United Kingdom", "Royaume-Uni"],
  ["USA", "États-Unis"],
  // Hub / filters (EN → FR, full phrases only)
  ["Choose category", "Choisir la catégorie"],
  ["Choose brand", "Choisir la marque"],
  ["Select model", "Choisir le modèle"],
  ["Select city", "Choisir la ville"],
  ["Select country", "Sélectionner le pays"],
  ["Choose city", "Choisir la ville"],
  ["Choose year", "Choisir l'année"],
  ["Choose category — each selection opens a new page with filters.", "Choisissez la catégorie — chaque sélection ouvre une nouvelle page avec des filtres."],
  ["Select transaction type, property type and filters — results update automatically in the list below.", "Sélectionnez le type de transaction, le type de bien et les filtres — les résultats se mettent à jour automatiquement dans la liste ci-dessous."],
  ["Choose what you are looking for — each option opens a page with filters and listings.", "Choisissez ce que vous recherchez — chaque option ouvre une page avec filtres et annonces."],
  ["Select sport type", "Choisir le type de sport"],
  ["Select equipment type", "Choisir le type d'équipement"],
  ["Sport type", "Type de sport"],
  ["Equipment type", "Type d'équipement"],
  ["All levels", "Tous les niveaux"],
  ["Beginner", "Débutant"],
  ["Intermediate", "Intermédiaire"],
  ["Advanced", "Avancé"],
  ["Hybrid", "Hybride"],
  ["Select category…", "Choisir la catégorie…"],
  ["Select subcategory…", "Choisir la sous-catégorie…"],
  ["Select city…", "Choisir la ville…"],
  ["Select format…", "Choisir le format…"],
  ["Select level…", "Choisir le niveau…"],
  ["Select a reason before continuing.", "Sélectionnez une raison avant de continuer."],
  ["Select your phone", "Sélectionnez votre téléphone"],
  ["Open your shop", "Ouvrir votre boutique"],
  ["Start now", "Commencer"],
  ["Choose your package", "Choisir votre forfait"],
  ["Contact us", "Nous contacter"],
  ["Send message", "Envoyer le message"],
  ["Frequently asked questions (FAQ)", "Questions fréquentes (FAQ)"],
  ["Online security", "Sécurité en ligne"],
  ["For press and media", "Presse et médias"],
  ["Business rules", "Règles pour les entreprises"],
  ["Registered business listings", "Annonces pour entreprises enregistrées"],
  ["Violation", "Infraction"],
  ["Consequence", "Mesure"],
  ["Registration", "Inscription"],
  ["Posting", "Publication"],
  ["Private accounts", "Comptes privés"],
  ["How do I post a listing?", "Comment publier une annonce ?"],
  ["How much does posting cost?", "Combien coûte la publication ?"],
  ["How do I delete or edit a listing?", "Comment supprimer ou modifier une annonce ?"],
  ["Posting listings", "Publication d'annonces"],
  ["Account and security", "Compte et sécurité"],
  ["Buying and selling", "Achat et vente"],
  ["Technical", "Technique"],
  ["Security rules", "Règles de sécurité"],
  ["What we offer the media", "Ce que nous offrons aux médias"],
  ["Response time", "Délai de réponse"],
];

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function applyFrenchPhrases(text) {
  if (!text || typeof text !== "string") return text;
  let s = text;
  const sorted = [...FR_PHRASES].sort((a, b) => b[0].length - a[0].length);
  for (const [en, fr] of sorted) {
    if (!s.includes(en)) continue;
    if (!en.includes(" ") && /^[A-Za-z'’-]+$/.test(en)) {
      s = s.replace(new RegExp(`\\b${escapeRegExp(en)}\\b`, "g"), fr);
    } else if (s.includes(en)) {
      s = s.split(en).join(fr);
    }
  }
  return s;
}
