/** English → German phrase replacements (longest match first). */
export const DE_PHRASES = [
  ["Sign in or register with email and password", "Mit E-Mail und Passwort anmelden oder registrieren"],
  ["Register with email. You will receive a confirmation code by email", "Mit E-Mail registrieren. Sie erhalten einen Bestätigungscode per E-Mail"],
  ["New account: code by email. Already registered? Email + password — sign in immediately", "Neues Konto: Code per E-Mail. Bereits registriert? E-Mail + Passwort — sofort anmelden"],
  ["Phone sign-in is not active. Register with email", "Telefon-Anmeldung ist nicht aktiv. Bitte mit E-Mail registrieren"],
  ["Enter the code from SMS.", "Geben Sie den Code aus der SMS ein."],
  ["Enter the code from SMS", "Geben Sie den Code aus der SMS ein"],
  ["Have a phone account?", "Haben Sie ein Telefonkonto?"],
  ["New email account?", "Neues E-Mail-Konto?"],
  ["Register as partner", "Als Partner registrieren"],
  ["Contact us", "Kontaktieren Sie uns"],
  ["Be the first to post in this category and reach thousands of potential buyers!", "Seien Sie der Erste in dieser Kategorie und erreichen Sie Tausende potenzieller Käufer!"],
  ["Be the first to post in this category!", "Seien Sie der Erste in dieser Kategorie!"],
  ["subcategories available", "Unterkategorien verfügbar"],
  ["brands available", "Marken verfügbar"],
  ["All countries", "Alle Länder"],
  ["Choose this category", "Diese Kategorie wählen"],
  ["You have reached the free limit", "Sie haben das kostenlose Limit erreicht"],
  ["Top up your wallet", "Guthaben aufladen"],
  ["per listing", "pro Anzeige"],
  ["Listing posted successfully", "Anzeige erfolgreich veröffentlicht"],
  ["Balance", "Guthaben"],
  ["listings remaining", "verbleibende Anzeigen"],
  ["Content did not pass automatic review", "Inhalt hat die automatische Prüfung nicht bestanden"],
  ["Selling language is not allowed", "Verkaufssprache ist nicht erlaubt"],
  ["blocked word", "gesperrtes Wort"],
  ["In this category the price is always €0", "In dieser Kategorie beträgt der Preis immer 0 €"],
  ["By clicking", "Mit dem Klick"],
  ["you accept full legal responsibility", "übernehmen Sie die volle rechtliche Verantwortung"],
  ["for the accuracy of your listing", "für die Richtigkeit Ihrer Anzeige"],
  ["Sign up", "Registrieren"],
  ["Log in", "Anmelden"],
  ["Home", "Startseite"],
  ["Open menu", "Menü öffnen"],
  ["Menu", "Menü"],
  ["Help", "Hilfe"],
  ["TOP LISTINGS", "TOP-ANZEIGEN"],
  ["Listings", "Anzeigen"],
  ["Our trusted partners", "Unsere vertrauenswürdigen Partner"],
  ["Listings remaining", "Verbleibende Anzeigen"],
  ["Pay by card", "Mit Karte bezahlen"],
  ["Card payment", "Kartenzahlung"],
  ["You can continue posting your listing", "Sie können Ihre Anzeige weiter veröffentlichen"],
  ["Sign in to see payment instructions", "Melden Sie sich an, um Zahlungsanweisungen zu sehen"],
  ["Payment not found", "Zahlung nicht gefunden"],
  ["Bank transfer", "Banküberweisung"],
  ["Bank transfer for wallet top-up", "Banküberweisung zum Aufladen des Guthabens"],
  ["Beneficiary", "Empfänger"],
  ["Describe the problem", "Beschreiben Sie das Problem"],
  ["Street, house number", "Straße, Hausnummer"],
  ["Air sports", "Luftsport"],
  ["Search sports equipment", "Sportausrüstung suchen"],
  ["Sport type", "Sportart"],
  ["Equipment type", "Ausrüstungstyp"],
  ["Germany, Switzerland, Austria", "Deutschland, Schweiz, Österreich"],
  ["Payment methods", "Zahlungsmethoden"],
  ["KetuJemi — Buy & Sell", "KetuJemi — Kaufen & Verkaufen"],
  ["free classifieds platform", "kostenlose Kleinanzeigen-Plattform"],
  ["Buy & Sell", "Kaufen & Verkaufen"],
  ["Shops", "Shops"],
  ["Search listings", "Anzeigen suchen"],
  ["Search", "Suchen"],
  ["Filters", "Filter"],
  ["Category", "Kategorie"],
  ["City", "Stadt"],
  ["Min price", "Mindestpreis"],
  ["Max price", "Höchstpreis"],
  ["Apply", "Anwenden"],
  ["Clear", "Zurücksetzen"],
  ["No listings found", "Keine Anzeigen gefunden"],
  ["Try changing filters or post a new listing", "Filter ändern oder eine neue Anzeige aufgeben"],
  ["Post listing", "Anzeige aufgeben"],
  ["Post for free", "Kostenlos aufgeben"],
  ["View all", "Alle anzeigen"],
  ["Categories", "Kategorien"],
  ["Back", "Zurück"],
  ["Edit", "Bearbeiten"],
  ["Delete", "Löschen"],
  ["Cancel", "Abbrechen"],
  ["Save changes", "Speichern"],
  ["Saving", "Wird gespeichert"],
  ["Description", "Beschreibung"],
  ["Details", "Details"],
  ["Seller", "Verkäufer"],
  ["Private seller", "Privatverkäufer"],
  ["Call", "Anrufen"],
  ["Share", "Teilen"],
  ["All", "Alle"],
  ["Yes", "Ja"],
  ["No", "Nein"],
  ["About us", "Über uns"],
  ["Privacy", "Datenschutz"],
  ["Terms", "AGB"],
  ["Security", "Sicherheit"],
  ["FAQ", "FAQ"],
  ["Contact", "Kontakt"],
  ["Refresh", "Aktualisieren"],
  ["Page could not load", "Seite konnte nicht geladen werden"],
  ["Shop not found", "Shop nicht gefunden"],
  ["Back to home", "Zurück zur Startseite"],
  ["About the shop", "Über den Shop"],
  ["Map", "Karte"],
  ["Shop listings", "Shop-Anzeigen"],
  ["No active listings at the moment.", "Derzeit keine aktiven Anzeigen."],
  ["Negotiable", "Verhandelbar"],
  ["active listings", "aktive Anzeigen"],
  ["Post New Listing", "Neue Anzeige aufgeben"],
  ["Delete listing?", "Anzeige löschen?"],
  ["This cannot be undone. The listing will be permanently removed.", "Dies kann nicht rückgängig gemacht werden. Die Anzeige wird dauerhaft entfernt."],
  ["Welcome! Your shop is ready — post your first listing now and start selling!", "Willkommen! Ihr Shop ist bereit — geben Sie jetzt Ihre erste Anzeige auf und beginnen Sie zu verkaufen!"],
  ["Post Your First Listing", "Erste Anzeige aufgeben"],
  ["Edit Shop", "Shop bearbeiten"],
  ["Delete Shop", "Shop löschen"],
  ["Delete shop?", "Shop löschen?"],
  ["Are you sure? This will delete your shop and all your listings.", "Sind Sie sicher? Dadurch werden Ihr Shop und alle Ihre Anzeigen gelöscht."],
  ["Save", "Speichern"],
  ["Shop updated.", "Shop aktualisiert."],
  ["Error saving shop.", "Fehler beim Speichern des Shops."],
  ["Shop deleted.", "Shop gelöscht."],
  ["Error deleting shop.", "Fehler beim Löschen des Shops."],
  ["My Shop", "Mein Shop"],
  ["Verified Shop", "Verifizierter Shop"],
  ["Approved", "Genehmigt"],
  ["Pending", "Ausstehend"],
  ["Manage Listings", "Anzeigen verwalten"],
  ["Total listings", "Anzeigen gesamt"],
  ["Total views", "Aufrufe gesamt"],
  ["View shop", "Shop ansehen"],
  ["No active listings from your shop.", "Keine aktiven Anzeigen aus Ihrem Shop."],
  ["Shop name", "Shop-Name"],
  ["Address", "Adresse"],
  ["Area/Neighbourhood", "Stadtteil"],
  ["Apply for a shop", "Shop beantragen"],
  ["Sign in / Register", "Anmelden / Registrieren"],
  ["Shop identity", "Shop-Identität"],
  ["Business description", "Geschäftsbeschreibung"],
  ["Main category", "Hauptkategorie"],
  ["Location", "Standort"],
  ["Country", "Land"],
  ["Region/Neighbourhood", "Region/Stadtteil"],
  ["Full address", "Vollständige Adresse"],
  ["Social media", "Soziale Medien"],
  ["Fill in at least one social network", "Mindestens ein soziales Netzwerk angeben"],
  ["Contact name", "Kontaktname"],
  ["Phone number", "Telefonnummer"],
  ["Submit Shop Request", "Shop-Anfrage senden"],
  ["Uploading logo...", "Logo wird hochgeladen..."],
  ["Help from our system", "Hilfe von unserem System"],
  ["Generate", "Generieren"],
  ["Generating...", "Wird generiert..."],
  ["Frequently Asked Questions", "Häufig gestellte Fragen"],
  ["FREQUENTLY ASKED QUESTIONS", "HÄUFIG GESTELLTE FRAGEN"],
  ["Ready to grow your business?", "Bereit, Ihr Geschäft auszubauen?"],
  ["Apply as partner", "Als Partner bewerben"],
  ["Apply as Partner", "Als Partner bewerben"],
  ["Apply as VIP Partner", "Als VIP-Partner bewerben"],
  ["Business packages", "Geschäftspakete"],
  ["BUSINESS PACKAGES", "GESCHÄFTSPAKETE"],
  ["Choose the package that fits your business", "Wählen Sie das Paket, das zu Ihrem Geschäft passt"],
  ["Partner not found", "Partner nicht gefunden"],
  ["This profile is not available.", "Dieses Profil ist nicht verfügbar."],
  ["Partner", "Partner"],
  ["VIP Partner", "VIP-Partner"],
  ["Contact & social", "Kontakt & soziale Medien"],
  ["About KetuJemi.com", "Über KetuJemi.com"],
  ["Platform rules", "Plattformregeln"],
  ["OFFICIAL MARKETS", "OFFIZIELLE MÄRKTE"],
  ["+8 diaspora countries", "+8 Diaspora-Länder"],
  ["North Macedonia", "Nordmazedonien"],
  ["Kosovo", "Kosovo"],
  ["Albania", "Albanien"],
  ["Montenegro", "Montenegro"],
  ["Germany", "Deutschland"],
  ["Switzerland", "Schweiz"],
  ["Austria", "Österreich"],
  ["France", "Frankreich"],
  ["Italy", "Italien"],
  ["United Kingdom", "Vereinigtes Königreich"],
  ["USA", "USA"],
  // Hub / filters (EN → DE, full phrases only)
  ["Choose category", "Kategorie wählen"],
  ["Choose brand", "Marke wählen"],
  ["Select model", "Modell wählen"],
  ["Select city", "Stadt wählen"],
  ["Select country", "Land auswählen"],
  ["Choose city", "Stadt wählen"],
  ["Choose year", "Jahr wählen"],
  ["Choose category — each selection opens a new page with filters.", "Kategorie wählen — jede Auswahl öffnet eine neue Seite mit Filtern."],
  ["Select transaction type, property type and filters — results update automatically in the list below.", "Transaktionstyp, Immobilientyp und Filter wählen — die Ergebnisse werden automatisch in der Liste unten aktualisiert."],
  ["Choose what you are looking for — each option opens a page with filters and listings.", "Wählen Sie, wonach Sie suchen — jede Option öffnet eine Seite mit Filtern und Anzeigen."],
  ["Select sport type", "Sportart wählen"],
  ["Select equipment type", "Ausrüstungstyp wählen"],
  ["Sport type", "Sportart"],
  ["Equipment type", "Ausrüstungstyp"],
  ["All levels", "Alle Niveaus"],
  ["Beginner", "Anfänger"],
  ["Intermediate", "Fortgeschritten"],
  ["Advanced", "Experte"],
  ["Hybrid", "Hybrid"],
  ["Select category…", "Kategorie wählen…"],
  ["Select subcategory…", "Unterkategorie wählen…"],
  ["Select city…", "Stadt wählen…"],
  ["Select format…", "Format wählen…"],
  ["Select level…", "Niveau wählen…"],
  ["Select a reason before continuing.", "Wählen Sie einen Grund, bevor Sie fortfahren."],
  ["Select your phone", "Telefon auswählen"],
  ["Open your shop", "Shop eröffnen"],
  ["Start now", "Jetzt starten"],
  ["Choose your package", "Paket wählen"],
  ["Contact us", "Kontaktieren Sie uns"],
  ["Send message", "Nachricht senden"],
  ["Frequently asked questions (FAQ)", "Häufig gestellte Fragen (FAQ)"],
  ["Online security", "Online-Sicherheit"],
  ["For press and media", "Für Presse und Medien"],
  ["Business rules", "Geschäftsregeln"],
  ["Registered business listings", "Anzeigen für registrierte Unternehmen"],
  ["Violation", "Verstoß"],
  ["Consequence", "Konsequenz"],
  ["Registration", "Registrierung"],
  ["Posting", "Veröffentlichung"],
  ["Private accounts", "Privatkonten"],
  ["How do I post a listing?", "Wie gebe ich eine Anzeige auf?"],
  ["How much does posting cost?", "Was kostet die Veröffentlichung?"],
  ["How do I delete or edit a listing?", "Wie lösche oder bearbeite ich eine Anzeige?"],
  ["Posting listings", "Anzeigen veröffentlichen"],
  ["Account and security", "Konto und Sicherheit"],
  ["Buying and selling", "Kaufen und Verkaufen"],
  ["Technical", "Technisch"],
  ["Security rules", "Sicherheitsregeln"],
  ["What we offer the media", "Was wir den Medien bieten"],
  ["Response time", "Antwortzeit"],
];

/** Extra direct sq→de (UI labels). */
export const SQ_DE_EXTRA = [
  ["Kryefaqja", "Startseite"],
  ["Kyçu", "Anmelden"],
  ["Regjistrohu", "Registrieren"],
  ["Menyja", "Menü"],
  ["Hap menyunë", "Menü öffnen"],
  ["Ndihmë", "Hilfe"],
  ["Kërko", "Suchen"],
  ["Posto", "Aufgeben"],
  ["Posto Njoftim", "Anzeige aufgeben"],
  ["Njoftime", "Anzeigen"],
  ["Njoftimet e mia", "Meine Anzeigen"],
  ["Profili", "Mein Profil"],
  ["Të gjitha", "Alle"],
  ["Të gjitha shtetet", "Alle Länder"],
  ["Qyteti", "Stadt"],
  ["Vendi", "Land"],
  ["Çmimi", "Preis"],
  ["Përshkrimi", "Beschreibung"],
  ["Detajet", "Details"],
  ["Kategoria", "Kategorie"],
  ["Nënkategoria", "Unterkategorie"],
  ["Filtri", "Filter"],
  ["Apliko", "Anwenden"],
  ["Pastro", "Zurücksetzen"],
  ["Ruaj", "Speichern"],
  ["Anulo", "Abbrechen"],
  ["Fshi", "Löschen"],
  ["Edito", "Bearbeiten"],
  ["Kthehu", "Zurück"],
  ["Dyqani", "Shop"],
  ["Dyqanet", "Shops"],
  ["Shitësi", "Verkäufer"],
  ["Blerësi", "Käufer"],
  ["Me marrëveshje", "Verhandelbar"],
  ["Falas", "Kostenlos"],
  ["Kontakti", "Kontakt"],
  ["Telefoni", "Telefon"],
  ["Emaili", "E-Mail"],
  ["Adresa", "Adresse"],
  ["Harta", "Karte"],
  ["Rreth dyqanit", "Über den Shop"],
  ["Hap dyqanin", "Shop eröffnen"],
  ["Apliko për dyqan", "Shop beantragen"],
  ["Partnerët tanë të besuar", "Unsere vertrauenswürdigen Partner"],
  ["TOP Njoftime", "TOP-ANZEIGEN"],
  ["Plotëso", "Ausfüllen"],
  ["Dërgo", "Senden"],
  ["Konfirmo", "Bestätigen"],
  ["Vazhdo", "Weiter"],
  ["Gabim", "Fehler"],
  ["Sukses", "Erfolg"],
  ["Duke u ngarkuar", "Wird geladen"],
  ["Nuk u gjet", "Nicht gefunden"],
  ["Kosovë", "Kosovo"],
  ["Shqipëri", "Albanien"],
  ["Maqedoni e Veriut", "Nordmazedonien"],
  ["Mal i Zi", "Montenegro"],
  ["Gjermania", "Deutschland"],
  ["Zvicra", "Schweiz"],
  ["Austria", "Österreich"],
  ["Francë", "Frankreich"],
  ["Itali", "Italien"],
  ["Angli", "Vereinigtes Königreich"],
  ["SHBA", "USA"],
  ["Zgjidh kategorinë", "Kategorie wählen"],
  ["Zgjidh nënkategorinë", "Unterkategorie wählen"],
  ["Kërkoj punë", "Jobsuche"],
  ["Kërkoj të Blej", "Sie suchen etwas? Hier aufgeben und finden"],
  ["PROGRAMI PARTNER", "PARTNERPROGRAMM"],
  ["PËRFITIMET TUAJA", "IHRE VORTEILE"],
  ["FORMULARI I APLIKIMIT", "BEWERBUNGSFORMULAR"],
];

/** Key-level overrides (UI bundle keys). */
export const DE_KEY_FROM_SQ = {
  login_heading: "Anmelden",
  login_heading_register: "Registrieren",
  login_mode_login: "Anmelden",
  login_mode_register: "Registrieren",
  login_submit_login: "Anmelden",
  login_submit_register: "Konto erstellen",
  nav_menuAria: "Menü öffnen",
  nav_menuTitle: "Menü",
  nav_home: "Startseite",
  nav_postShort: "Aufgeben",
  nav_myProfile: "Mein Profil",
  nav_myListings: "Meine Anzeigen",
  nf_title: "Seite nicht gefunden",
  home_topListingsHeading: "TOP-ANZEIGEN",
  ak_lang_de: "Deutsch",
  login_phoneVerifyHint: "Geben Sie den Code aus der SMS ein.",
};

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function applyGermanPhrases(text) {
  if (!text || typeof text !== "string") return text;
  let s = text;
  const sorted = [...DE_PHRASES].sort((a, b) => b[0].length - a[0].length);
  for (const [en, de] of sorted) {
    if (!s.includes(en)) continue;
    if (!en.includes(" ") && /^[A-Za-z'’-]+$/.test(en)) {
      s = s.replace(new RegExp(`\\b${escapeRegExp(en)}\\b`, "g"), de);
    } else if (s.includes(en)) {
      s = s.split(en).join(de);
    }
  }
  return s;
}
