/** English → Italian phrase replacements (longest match first). */
export const IT_PHRASES = [
  ["Sign in or register with email and password", "Accedi o registrati con e-mail e password"],
  ["Register with email. You will receive a confirmation code by email", "Registrati con e-mail. Riceverai un codice di conferma via e-mail"],
  ["New account: code by email. Already registered? Email + password — sign in immediately", "Nuovo account: codice via e-mail. Già registrato? E-mail + password — accesso immediato"],
  ["Phone sign-in is not active. Register with email", "L'accesso tramite telefono non è attivo. Registrati con e-mail"],
  ["Enter the code from SMS.", "Inserisci il codice ricevuto via SMS."],
  ["Enter the code from SMS", "Inserisci il codice ricevuto via SMS"],
  ["Have a phone account?", "Hai un account telefonico?"],
  ["New email account?", "Nuovo account e-mail?"],
  ["Register as partner", "Registrati come partner"],
  ["Contact us", "Contattaci"],
  ["Be the first to post in this category and reach thousands of potential buyers!", "Sii il primo a pubblicare in questa categoria e raggiungi migliaia di potenziali acquirenti!"],
  ["Be the first to post in this category!", "Sii il primo a pubblicare in questa categoria!"],
  ["subcategories available", "sottocategorie disponibili"],
  ["brands available", "marchi disponibili"],
  ["All countries", "Tutti i paesi"],
  ["Choose this category", "Scegli questa categoria"],
  ["You have reached the free limit", "Hai raggiunto il limite gratuito"],
  ["Top up your wallet", "Ricarica il portafoglio"],
  ["per listing", "per annuncio"],
  ["Listing posted successfully", "Annuncio pubblicato con successo"],
  ["Balance", "Saldo"],
  ["listings remaining", "annunci rimanenti"],
  ["Content did not pass automatic review", "Il contenuto non ha superato la verifica automatica"],
  ["Selling language is not allowed", "Linguaggio commerciale non consentito"],
  ["blocked word", "parola bloccata"],
  ["In this category the price is always €0", "In questa categoria il prezzo è sempre 0 €"],
  ["By clicking", "Cliccando"],
  ["you accept full legal responsibility", "accetti la piena responsabilità legale"],
  ["for the accuracy of your listing", "per l'accuratezza del tuo annuncio"],
  ["Sign up", "Registrati"],
  ["Log in", "Accedi"],
  ["Home", "Home"],
  ["Open menu", "Apri menu"],
  ["Menu", "Menu"],
  ["Help", "Aiuto"],
  ["TOP LISTINGS", "ANNUNCI TOP"],
  ["Listings", "Annunci"],
  ["Our trusted partners", "I nostri partner di fiducia"],
  ["Listings remaining", "Annunci rimanenti"],
  ["Pay by card", "Paga con carta"],
  ["Card payment", "Pagamento con carta"],
  ["You can continue posting your listing", "Puoi continuare a pubblicare il tuo annuncio"],
  ["Sign in to see payment instructions", "Accedi per vedere le istruzioni di pagamento"],
  ["Payment not found", "Pagamento non trovato"],
  ["Bank transfer", "Bonifico bancario"],
  ["Bank transfer for wallet top-up", "Bonifico bancario per ricaricare il portafoglio"],
  ["Beneficiary", "Beneficiario"],
  ["Describe the problem", "Descrivi il problema"],
  ["Street, house number", "Via, numero civico"],
  ["Air sports", "Sport aerei"],
  ["Search sports equipment", "Cerca attrezzatura sportiva"],
  ["Sport type", "Tipo di sport"],
  ["Equipment type", "Tipo di attrezzatura"],
  ["Germany, Switzerland, Austria", "Germania, Svizzera, Austria"],
  ["Payment methods", "Metodi di pagamento"],
  ["KetuJemi — Buy & Sell", "KetuJemi — Compra e vendi"],
  ["free classifieds platform", "piattaforma di annunci gratuita"],
  ["Buy & Sell", "Compra e vendi"],
  ["Shops", "Negozi"],
  ["Search listings", "Cerca annunci"],
  ["Search", "Cerca"],
  ["Filters", "Filtri"],
  ["Category", "Categoria"],
  ["City", "Città"],
  ["Min price", "Prezzo min."],
  ["Max price", "Prezzo max."],
  ["Apply", "Applica"],
  ["Clear", "Cancella"],
  ["No listings found", "Nessun annuncio trovato"],
  ["Try changing filters or post a new listing", "Modifica i filtri o pubblica un nuovo annuncio"],
  ["Post listing", "Pubblica annuncio"],
  ["Post for free", "Pubblica gratis"],
  ["View all", "Vedi tutto"],
  ["Categories", "Categorie"],
  ["Back", "Indietro"],
  ["Edit", "Modifica"],
  ["Delete", "Elimina"],
  ["Cancel", "Annulla"],
  ["Save changes", "Salva"],
  ["Saving", "Salvataggio"],
  ["Description", "Descrizione"],
  ["Details", "Dettagli"],
  ["Seller", "Venditore"],
  ["Private seller", "Venditore privato"],
  ["Call", "Chiama"],
  ["Share", "Condividi"],
  ["All", "Tutto"],
  ["Yes", "Sì"],
  ["No", "No"],
  ["About us", "Chi siamo"],
  ["Privacy", "Privacy"],
  ["Terms", "Termini"],
  ["Security", "Sicurezza"],
  ["FAQ", "FAQ"],
  ["Contact", "Contatto"],
  ["Refresh", "Aggiorna"],
  ["Page could not load", "Impossibile caricare la pagina"],
  ["Shop not found", "Negozio non trovato"],
  ["Back to home", "Torna alla home"],
  ["About the shop", "Informazioni sul negozio"],
  ["Map", "Mappa"],
  ["Shop listings", "Annunci del negozio"],
  ["No active listings at the moment.", "Nessun annuncio attivo al momento."],
  ["Negotiable", "Trattabile"],
  ["active listings", "annunci attivi"],
  ["Post New Listing", "Pubblica nuovo annuncio"],
  ["Delete listing?", "Eliminare l'annuncio?"],
  ["This cannot be undone. The listing will be permanently removed.", "Questa azione è irreversibile. L'annuncio verrà rimosso definitivamente."],
  ["Welcome! Your shop is ready — post your first listing now and start selling!", "Benvenuto! Il tuo negozio è pronto — pubblica il tuo primo annuncio e inizia a vendere!"],
  ["Post Your First Listing", "Pubblica il tuo primo annuncio"],
  ["Edit Shop", "Modifica negozio"],
  ["Delete Shop", "Elimina negozio"],
  ["Delete shop?", "Eliminare il negozio?"],
  ["Are you sure? This will delete your shop and all your listings.", "Sei sicuro? Questo eliminerà il tuo negozio e tutti i tuoi annunci."],
  ["Save", "Salva"],
  ["Shop updated.", "Negozio aggiornato."],
  ["Error saving shop.", "Errore durante il salvataggio del negozio."],
  ["Shop deleted.", "Negozio eliminato."],
  ["Error deleting shop.", "Errore durante l'eliminazione del negozio."],
  ["My Shop", "Il mio negozio"],
  ["Verified Shop", "Negozio verificato"],
  ["Approved", "Approvato"],
  ["Pending", "In attesa"],
  ["Manage Listings", "Gestisci annunci"],
  ["Total listings", "Annunci totali"],
  ["Total views", "Visualizzazioni totali"],
  ["View shop", "Vedi negozio"],
  ["No active listings from your shop.", "Nessun annuncio attivo dal tuo negozio."],
  ["Shop name", "Nome del negozio"],
  ["Address", "Indirizzo"],
  ["Area/Neighbourhood", "Quartiere"],
  ["Apply for a shop", "Richiedi un negozio"],
  ["Sign in / Register", "Accedi / Registrati"],
  ["Shop identity", "Identità del negozio"],
  ["Business description", "Descrizione dell'attività"],
  ["Main category", "Categoria principale"],
  ["Location", "Posizione"],
  ["Country", "Paese"],
  ["Region/Neighbourhood", "Regione/Quartiere"],
  ["Full address", "Indirizzo completo"],
  ["Social media", "Social media"],
  ["Fill in at least one social network", "Compila almeno un social network"],
  ["Contact name", "Nome del contatto"],
  ["Phone number", "Numero di telefono"],
  ["Submit Shop Request", "Invia richiesta negozio"],
  ["Uploading logo...", "Caricamento logo..."],
  ["Help from our system", "Aiuto dal nostro sistema"],
  ["Generate", "Genera"],
  ["Generating...", "Generazione..."],
  ["Frequently Asked Questions", "Domande frequenti"],
  ["FREQUENTLY ASKED QUESTIONS", "DOMANDE FREQUENTI"],
  ["Ready to grow your business?", "Pronto a far crescere la tua attività?"],
  ["Apply as partner", "Candidati come partner"],
  ["Apply as Partner", "Candidati come partner"],
  ["Apply as VIP Partner", "Candidati come partner VIP"],
  ["Business packages", "Pacchetti business"],
  ["BUSINESS PACKAGES", "PACCHETTI BUSINESS"],
  ["Choose the package that fits your business", "Scegli il pacchetto adatto alla tua attività"],
  ["Partner not found", "Partner non trovato"],
  ["This profile is not available.", "Questo profilo non è disponibile."],
  ["Partner", "Partner"],
  ["VIP Partner", "Partner VIP"],
  ["Contact & social", "Contatto e social"],
  ["About KetuJemi.com", "Informazioni su KetuJemi.com"],
  ["Platform rules", "Regole della piattaforma"],
  ["OFFICIAL MARKETS", "MERCATI UFFICIALI"],
  ["+8 diaspora countries", "+8 paesi della diaspora"],
  ["North Macedonia", "Macedonia del Nord"],
  ["Kosovo", "Kosovo"],
  ["Albania", "Albania"],
  ["Montenegro", "Montenegro"],
  ["Germany", "Germania"],
  ["Switzerland", "Svizzera"],
  ["Austria", "Austria"],
  ["France", "Francia"],
  ["Italy", "Italia"],
  ["United Kingdom", "Regno Unito"],
  ["USA", "USA"],
  // Hub / filters (EN → IT, full phrases only)
  ["Choose category", "Scegli categoria"],
  ["Choose brand", "Scegli marca"],
  ["Select model", "Scegli modello"],
  ["Select city", "Scegli città"],
  ["Select country", "Seleziona paese"],
  ["Choose city", "Scegli città"],
  ["Choose year", "Scegli anno"],
  ["Choose category — each selection opens a new page with filters.", "Scegli la categoria — ogni selezione apre una nuova pagina con filtri."],
  ["Select transaction type, property type and filters — results update automatically in the list below.", "Seleziona tipo di transazione, tipo di immobile e filtri — i risultati si aggiornano automaticamente nell'elenco sottostante."],
  ["Choose what you are looking for — each option opens a page with filters and listings.", "Scegli cosa stai cercando — ogni opzione apre una pagina con filtri e annunci."],
  ["Select sport type", "Scegli tipo di sport"],
  ["Select equipment type", "Scegli tipo di attrezzatura"],
  ["Sport type", "Tipo di sport"],
  ["Equipment type", "Tipo di attrezzatura"],
  ["All levels", "Tutti i livelli"],
  ["Beginner", "Principiante"],
  ["Intermediate", "Intermedio"],
  ["Advanced", "Avanzato"],
  ["Hybrid", "Ibrido"],
  ["Select category…", "Scegli categoria…"],
  ["Select subcategory…", "Scegli sottocategoria…"],
  ["Select city…", "Scegli città…"],
  ["Select format…", "Scegli formato…"],
  ["Select level…", "Scegli livello…"],
  ["Select a reason before continuing.", "Seleziona un motivo prima di continuare."],
  ["Select your phone", "Seleziona il tuo telefono"],
  ["Open your shop", "Apri il tuo negozio"],
  ["Start now", "Inizia ora"],
  ["Choose your package", "Scegli il tuo pacchetto"],
  ["Contact us", "Contattaci"],
  ["Send message", "Invia messaggio"],
  ["Frequently asked questions (FAQ)", "Domande frequenti (FAQ)"],
  ["Online security", "Sicurezza online"],
  ["For press and media", "Per stampa e media"],
  ["Business rules", "Regole per le aziende"],
  ["Registered business listings", "Annunci per aziende registrate"],
  ["Violation", "Violazione"],
  ["Consequence", "Conseguenza"],
  ["Registration", "Registrazione"],
  ["Posting", "Pubblicazione"],
  ["Private accounts", "Account privati"],
  ["How do I post a listing?", "Come pubblico un annuncio?"],
  ["How much does posting cost?", "Quanto costa la pubblicazione?"],
  ["How do I delete or edit a listing?", "Come elimino o modifico un annuncio?"],
  ["Posting listings", "Pubblicazione annunci"],
  ["Account and security", "Account e sicurezza"],
  ["Buying and selling", "Acquisto e vendita"],
  ["Technical", "Tecnico"],
  ["Security rules", "Regole di sicurezza"],
  ["What we offer the media", "Cosa offriamo ai media"],
  ["Response time", "Tempo di risposta"],
];

/** Extra direct sq→it (UI labels). */
export const SQ_IT_EXTRA = [
  ["Kryefaqja", "Home"],
  ["Kyçu", "Accedi"],
  ["Regjistrohu", "Registrati"],
  ["Menyja", "Menu"],
  ["Hap menyunë", "Apri menu"],
  ["Ndihmë", "Aiuto"],
  ["Kërko", "Cerca"],
  ["Posto", "Pubblica"],
  ["Posto Njoftim", "Pubblica annuncio"],
  ["Njoftime", "Annunci"],
  ["Njoftimet e mia", "I miei annunci"],
  ["Profili", "Il mio profilo"],
  ["Të gjitha", "Tutto"],
  ["Të gjitha shtetet", "Tutti i paesi"],
  ["Qyteti", "Città"],
  ["Vendi", "Paese"],
  ["Çmimi", "Prezzo"],
  ["Përshkrimi", "Descrizione"],
  ["Detajet", "Dettagli"],
  ["Kategoria", "Categoria"],
  ["Nënkategoria", "Sottocategoria"],
  ["Filtri", "Filtri"],
  ["Apliko", "Applica"],
  ["Pastro", "Cancella"],
  ["Ruaj", "Salva"],
  ["Anulo", "Annulla"],
  ["Fshi", "Elimina"],
  ["Edito", "Modifica"],
  ["Kthehu", "Indietro"],
  ["Dyqani", "Negozio"],
  ["Dyqanet", "Negozi"],
  ["Shitësi", "Venditore"],
  ["Blerësi", "Acquirente"],
  ["Me marrëveshje", "Trattabile"],
  ["Falas", "Gratis"],
  ["Kontakti", "Contatto"],
  ["Telefoni", "Telefono"],
  ["Emaili", "E-mail"],
  ["Adresa", "Indirizzo"],
  ["Harta", "Mappa"],
  ["Rreth dyqanit", "Informazioni sul negozio"],
  ["Hap dyqanin", "Apri il negozio"],
  ["Apliko për dyqan", "Richiedi un negozio"],
  ["Partnerët tanë të besuar", "I nostri partner di fiducia"],
  ["TOP Njoftime", "ANNUNCI TOP"],
  ["Plotëso", "Compila"],
  ["Dërgo", "Invia"],
  ["Konfirmo", "Conferma"],
  ["Vazhdo", "Continua"],
  ["Gabim", "Errore"],
  ["Sukses", "Successo"],
  ["Duke u ngarkuar", "Caricamento"],
  ["Nuk u gjet", "Non trovato"],
  ["Kosovë", "Kosovo"],
  ["Shqipëri", "Albania"],
  ["Maqedoni e Veriut", "Macedonia del Nord"],
  ["Mal i Zi", "Montenegro"],
  ["Gjermania", "Germania"],
  ["Zvicra", "Svizzera"],
  ["Austria", "Austria"],
  ["Francë", "Francia"],
  ["Itali", "Italia"],
  ["Angli", "Regno Unito"],
  ["SHBA", "USA"],
  ["Zgjidh kategorinë", "Scegli categoria"],
  ["Zgjidh nënkategorinë", "Scegli sottocategoria"],
  ["Kërkoj punë", "Cerco lavoro"],
  ["Kërkoj të Blej", "Cerchi qualcosa? Pubblica qui e trova"],
  ["PROGRAMI PARTNER", "PROGRAMMA PARTNER"],
  ["PËRFITIMET TUAJA", "I TUOI VANTAGGI"],
  ["FORMULARI I APLIKIMIT", "MODULO DI CANDIDATURA"],
];

/** Key-level overrides (UI bundle keys). */
export const IT_KEY_FROM_SQ = {
  login_heading: "Accedi",
  login_heading_register: "Registrazione",
  login_mode_login: "Accedi",
  login_mode_register: "Registrazione",
  login_submit_login: "Accedi",
  login_submit_register: "Crea account",
  nav_menuAria: "Apri menu",
  nav_menuTitle: "Menu",
  nav_home: "Home",
  nav_postShort: "Pubblica",
  nav_myProfile: "Il mio profilo",
  nav_myListings: "I miei annunci",
  nf_title: "Pagina non trovata",
  home_topListingsHeading: "ANNUNCI TOP",
  ak_lang_it: "Italiano",
  login_phoneVerifyHint: "Inserisci il codice ricevuto via SMS.",
};

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function applyItalianPhrases(text) {
  if (!text || typeof text !== "string") return text;
  let s = text;
  const sorted = [...IT_PHRASES].sort((a, b) => b[0].length - a[0].length);
  for (const [en, it] of sorted) {
    if (!s.includes(en)) continue;
    if (!en.includes(" ") && /^[A-Za-z'’-]+$/.test(en)) {
      s = s.replace(new RegExp(`\\b${escapeRegExp(en)}\\b`, "g"), it);
    } else if (s.includes(en)) {
      s = s.split(en).join(it);
    }
  }
  return s;
}
