export const KOMPJUTER_HUB_TYPE_NAMES = [
  "Desktop PC",
  "Laptopë",
  "Monitorë",
  "Pjesë Harduerike",
  "Serverë",
  "Tabletë",
] as const;

export type KompjuterHubTypeName = (typeof KOMPJUTER_HUB_TYPE_NAMES)[number];

export const KOMPJUTER_SUB_ITEM_KEYS = [
  "desktop_gaming",
  "desktop_office",
  "desktop_workstation",
  "desktop_aio",
  "desktop_mini",
  "laptop_gaming",
  "laptop_ultrabook",
  "laptop_biznes",
  "laptop_2in1",
  "laptop_macbook",
  "monitor_gaming",
  "monitor_office",
  "monitor_pro",
  "monitor_curved",
  "hw_cpu",
  "hw_gpu",
  "hw_mobo",
  "hw_ram",
  "hw_ssd",
  "hw_psu",
  "hw_case",
  "hw_cooler",
  "srv_rack",
  "srv_tower",
  "srv_blade",
  "srv_nas",
  "srv_parts",
  "tab_ipad",
  "tab_android",
  "tab_drawing",
  "tab_accessories",
] as const;

export type KompjuterSubItemKey = (typeof KOMPJUTER_SUB_ITEM_KEYS)[number];

export const KOMPJUTER_SUB_SEARCH: Record<KompjuterSubItemKey, string> = {
  desktop_gaming: "PC Gaming",
  desktop_office: "PC Zyre Shtepi Office Home",
  desktop_workstation: "Workstation",
  desktop_aio: "All-in-One PC AIO",
  desktop_mini: "Mini PC",
  laptop_gaming: "Gaming Laptop",
  laptop_ultrabook: "Ultrabook Notebook",
  laptop_biznes: "Biznes Business Laptop",
  laptop_2in1: "2-in-1 Convertible",
  laptop_macbook: "MacBook Apple",
  monitor_gaming: "Gaming Monitor",
  monitor_office: "Zyra Standard Office Monitor",
  monitor_pro: "Profesional Professional Monitor",
  monitor_curved: "Curved Ultrawide Monitor",
  hw_cpu: "Procesor CPU",
  hw_gpu: "Kartela Grafike GPU",
  hw_mobo: "Pllaka Ame Motherboard",
  hw_ram: "RAM Memorie",
  hw_ssd: "SSD M.2 SATA HDD",
  hw_psu: "PSU Furnizues",
  hw_case: "PC Cases",
  hw_cooler: "Ftohës Cooler",
  srv_rack: "Rack Servers",
  srv_tower: "Tower Servers",
  srv_blade: "Blade Servers",
  srv_nas: "NAS Storage",
  srv_parts: "Pjese Serveresh RAM ECC Xeon EPYC",
  tab_ipad: "Apple iPad",
  tab_android: "Android Samsung Xiaomi Lenovo Tablet",
  tab_drawing: "Tablete Grafike Wacom Huion",
  tab_accessories: "Aksesore Kellef Tastiere Stylus",
};

export const KOMPJUTER_SUB_LABEL_KEY: Record<KompjuterSubItemKey, string> = {
  desktop_gaming: "kl_sub_desktop_gaming",
  desktop_office: "kl_sub_desktop_office",
  desktop_workstation: "kl_sub_desktop_workstation",
  desktop_aio: "kl_sub_desktop_aio",
  desktop_mini: "kl_sub_desktop_mini",
  laptop_gaming: "kl_sub_laptop_gaming",
  laptop_ultrabook: "kl_sub_laptop_ultrabook",
  laptop_biznes: "kl_sub_laptop_biznes",
  laptop_2in1: "kl_sub_laptop_2in1",
  laptop_macbook: "kl_sub_laptop_macbook",
  monitor_gaming: "kl_sub_monitor_gaming",
  monitor_office: "kl_sub_monitor_office",
  monitor_pro: "kl_sub_monitor_pro",
  monitor_curved: "kl_sub_monitor_curved",
  hw_cpu: "kl_sub_hw_cpu",
  hw_gpu: "kl_sub_hw_gpu",
  hw_mobo: "kl_sub_hw_mobo",
  hw_ram: "kl_sub_hw_ram",
  hw_ssd: "kl_sub_hw_ssd",
  hw_psu: "kl_sub_hw_psu",
  hw_case: "kl_sub_hw_case",
  hw_cooler: "kl_sub_hw_cooler",
  srv_rack: "kl_sub_srv_rack",
  srv_tower: "kl_sub_srv_tower",
  srv_blade: "kl_sub_srv_blade",
  srv_nas: "kl_sub_srv_nas",
  srv_parts: "kl_sub_srv_parts",
  tab_ipad: "kl_sub_tab_ipad",
  tab_android: "kl_sub_tab_android",
  tab_drawing: "kl_sub_tab_drawing",
  tab_accessories: "kl_sub_tab_accessories",
};

export const KOMPJUTER_TYPE_SUB_ITEMS: Record<KompjuterHubTypeName, readonly KompjuterSubItemKey[]> = {
  "Desktop PC": [
    "desktop_gaming",
    "desktop_office",
    "desktop_workstation",
    "desktop_aio",
    "desktop_mini",
  ],
  Laptopë: ["laptop_gaming", "laptop_ultrabook", "laptop_biznes", "laptop_2in1", "laptop_macbook"],
  Monitorë: ["monitor_gaming", "monitor_office", "monitor_pro", "monitor_curved"],
  "Pjesë Harduerike": ["hw_cpu", "hw_gpu", "hw_mobo", "hw_ram", "hw_ssd", "hw_psu", "hw_case", "hw_cooler"],
  Serverë: ["srv_rack", "srv_tower", "srv_blade", "srv_nas", "srv_parts"],
  Tabletë: ["tab_ipad", "tab_android", "tab_drawing", "tab_accessories"],
};

export const KOMPJUTER_FILTER_KEYS = [
  "proc_intel",
  "proc_amd",
  "ram_8",
  "ram_16",
  "ram_32p",
  "gpu_rtx",
  "gpu_radeon",
  "gpu_integrated",
  "storage_ssd",
  "storage_hdd",
  "lap_screen_13",
  "lap_screen_14",
  "lap_screen_15",
  "lap_screen_17",
  "res_fhd",
  "res_4k",
  "os_windows",
  "os_macos",
  "os_none",
  "hz_60",
  "hz_144",
  "hz_240p",
  "panel_ips",
  "panel_va",
  "panel_oled",
  "port_hdmi",
  "port_dp",
  "port_usbc",
  "socket_am5",
  "socket_lga1700",
  "fmt_atx",
  "fmt_matx",
  "psu_450",
  "psu_550",
  "psu_650",
  "psu_750p",
  "srv_cpu_1",
  "srv_cpu_2",
  "srv_cpu_4p",
  "srv_ram_32",
  "srv_ram_64",
  "srv_ram_128p",
  "srv_bays_4",
  "srv_bays_8",
  "srv_bays_12p",
  "conn_wifi",
  "conn_4g",
  "conn_5g",
  "tab_screen_8",
  "tab_screen_10",
  "tab_screen_12p",
  "tab_mem_64",
  "tab_mem_128",
  "tab_mem_256p",
] as const;

export type KompjuterFilterKey = (typeof KOMPJUTER_FILTER_KEYS)[number];

export const KOMPJUTER_FILTER_SEARCH: Record<KompjuterFilterKey, string> = {
  proc_intel: "Intel Core i3 i5 i7 i9",
  proc_amd: "AMD Ryzen",
  ram_8: "8GB RAM",
  ram_16: "16GB RAM",
  ram_32p: "32GB 64GB RAM",
  gpu_rtx: "NVIDIA RTX GeForce",
  gpu_radeon: "AMD Radeon",
  gpu_integrated: "Integrated Graphics",
  storage_ssd: "SSD NVMe M.2",
  storage_hdd: "HDD",
  lap_screen_13: '13"',
  lap_screen_14: '14"',
  lap_screen_15: '15.6"',
  lap_screen_17: '17"',
  res_fhd: "FHD 1080p",
  res_4k: "4K UHD",
  os_windows: "Windows",
  os_macos: "macOS MacBook",
  os_none: "Pa sistem",
  hz_60: "60Hz",
  hz_144: "144Hz",
  hz_240p: "240Hz 360Hz",
  panel_ips: "IPS",
  panel_va: "VA",
  panel_oled: "OLED",
  port_hdmi: "HDMI",
  port_dp: "DisplayPort",
  port_usbc: "USB-C Type-C",
  socket_am5: "AM5",
  socket_lga1700: "LGA1700",
  fmt_atx: "ATX",
  fmt_matx: "Micro-ATX mATX",
  psu_450: "450W PSU",
  psu_550: "550W PSU",
  psu_650: "650W PSU",
  psu_750p: "750W 850W 1000W PSU",
  srv_cpu_1: "1 CPU single",
  srv_cpu_2: "2 CPU dual",
  srv_cpu_4p: "4 CPU multi",
  srv_ram_32: "32GB RAM max",
  srv_ram_64: "64GB RAM max",
  srv_ram_128p: "128GB 256GB RAM",
  srv_bays_4: "4 bay HDD SSD",
  srv_bays_8: "8 bay HDD SSD",
  srv_bays_12p: "12 bay 24 bay",
  conn_wifi: "WiFi",
  conn_4g: "4G LTE",
  conn_5g: "5G",
  tab_screen_8: '8" tablet',
  tab_screen_10: '10" tablet',
  tab_screen_12p: '12" 13" tablet',
  tab_mem_64: "64GB storage",
  tab_mem_128: "128GB storage",
  tab_mem_256p: "256GB 512GB storage",
};

export const KOMPJUTER_FILTER_LABEL_KEY: Record<KompjuterFilterKey, string> = {
  proc_intel: "kl_filt_proc_intel",
  proc_amd: "kl_filt_proc_amd",
  ram_8: "kl_filt_ram_8",
  ram_16: "kl_filt_ram_16",
  ram_32p: "kl_filt_ram_32p",
  gpu_rtx: "kl_filt_gpu_rtx",
  gpu_radeon: "kl_filt_gpu_radeon",
  gpu_integrated: "kl_filt_gpu_integrated",
  storage_ssd: "kl_filt_storage_ssd",
  storage_hdd: "kl_filt_storage_hdd",
  lap_screen_13: "kl_filt_lap_screen_13",
  lap_screen_14: "kl_filt_lap_screen_14",
  lap_screen_15: "kl_filt_lap_screen_15",
  lap_screen_17: "kl_filt_lap_screen_17",
  res_fhd: "kl_filt_res_fhd",
  res_4k: "kl_filt_res_4k",
  os_windows: "kl_filt_os_windows",
  os_macos: "kl_filt_os_macos",
  os_none: "kl_filt_os_none",
  hz_60: "kl_filt_hz_60",
  hz_144: "kl_filt_hz_144",
  hz_240p: "kl_filt_hz_240p",
  panel_ips: "kl_filt_panel_ips",
  panel_va: "kl_filt_panel_va",
  panel_oled: "kl_filt_panel_oled",
  port_hdmi: "kl_filt_port_hdmi",
  port_dp: "kl_filt_port_dp",
  port_usbc: "kl_filt_port_usbc",
  socket_am5: "kl_filt_socket_am5",
  socket_lga1700: "kl_filt_socket_lga1700",
  fmt_atx: "kl_filt_fmt_atx",
  fmt_matx: "kl_filt_fmt_matx",
  psu_450: "kl_filt_psu_450",
  psu_550: "kl_filt_psu_550",
  psu_650: "kl_filt_psu_650",
  psu_750p: "kl_filt_psu_750p",
  srv_cpu_1: "kl_filt_srv_cpu_1",
  srv_cpu_2: "kl_filt_srv_cpu_2",
  srv_cpu_4p: "kl_filt_srv_cpu_4p",
  srv_ram_32: "kl_filt_srv_ram_32",
  srv_ram_64: "kl_filt_srv_ram_64",
  srv_ram_128p: "kl_filt_srv_ram_128p",
  srv_bays_4: "kl_filt_srv_bays_4",
  srv_bays_8: "kl_filt_srv_bays_8",
  srv_bays_12p: "kl_filt_srv_bays_12p",
  conn_wifi: "kl_filt_conn_wifi",
  conn_4g: "kl_filt_conn_4g",
  conn_5g: "kl_filt_conn_5g",
  tab_screen_8: "kl_filt_tab_screen_8",
  tab_screen_10: "kl_filt_tab_screen_10",
  tab_screen_12p: "kl_filt_tab_screen_12p",
  tab_mem_64: "kl_filt_tab_mem_64",
  tab_mem_128: "kl_filt_tab_mem_128",
  tab_mem_256p: "kl_filt_tab_mem_256p",
};

export type KompjuterFilterGroup = {
  titleKey: string;
  optionKeys: readonly KompjuterFilterKey[];
};

export const KOMPJUTER_TYPE_FILTER_GROUPS: Record<KompjuterHubTypeName, readonly KompjuterFilterGroup[]> = {
  "Desktop PC": [
    {
      titleKey: "kl_filt_grp_processor",
      optionKeys: ["proc_intel", "proc_amd"],
    },
    {
      titleKey: "kl_filt_grp_ram",
      optionKeys: ["ram_8", "ram_16", "ram_32p"],
    },
    {
      titleKey: "kl_filt_grp_gpu",
      optionKeys: ["gpu_rtx", "gpu_radeon", "gpu_integrated"],
    },
    {
      titleKey: "kl_filt_grp_storage",
      optionKeys: ["storage_ssd", "storage_hdd"],
    },
  ],
  Laptopë: [
    {
      titleKey: "kl_filt_grp_screen",
      optionKeys: ["lap_screen_13", "lap_screen_14", "lap_screen_15", "lap_screen_17"],
    },
    {
      titleKey: "kl_filt_grp_resolution",
      optionKeys: ["res_fhd", "res_4k"],
    },
    {
      titleKey: "kl_filt_grp_os",
      optionKeys: ["os_windows", "os_macos", "os_none"],
    },
  ],
  Monitorë: [
    {
      titleKey: "kl_filt_grp_hz",
      optionKeys: ["hz_60", "hz_144", "hz_240p"],
    },
    {
      titleKey: "kl_filt_grp_panel",
      optionKeys: ["panel_ips", "panel_va", "panel_oled"],
    },
    {
      titleKey: "kl_filt_grp_ports",
      optionKeys: ["port_hdmi", "port_dp", "port_usbc"],
    },
  ],
  "Pjesë Harduerike": [
    {
      titleKey: "kl_filt_grp_socket",
      optionKeys: ["socket_am5", "socket_lga1700"],
    },
    {
      titleKey: "kl_filt_grp_format",
      optionKeys: ["fmt_atx", "fmt_matx"],
    },
    {
      titleKey: "kl_filt_grp_psu",
      optionKeys: ["psu_450", "psu_550", "psu_650", "psu_750p"],
    },
  ],
  Serverë: [
    {
      titleKey: "kl_filt_grp_srv_cpu",
      optionKeys: ["srv_cpu_1", "srv_cpu_2", "srv_cpu_4p"],
    },
    {
      titleKey: "kl_filt_grp_srv_ram",
      optionKeys: ["srv_ram_32", "srv_ram_64", "srv_ram_128p"],
    },
    {
      titleKey: "kl_filt_grp_srv_bays",
      optionKeys: ["srv_bays_4", "srv_bays_8", "srv_bays_12p"],
    },
  ],
  Tabletë: [
    {
      titleKey: "kl_filt_grp_connectivity",
      optionKeys: ["conn_wifi", "conn_4g", "conn_5g"],
    },
    {
      titleKey: "kl_filt_grp_tab_screen",
      optionKeys: ["tab_screen_8", "tab_screen_10", "tab_screen_12p"],
    },
    {
      titleKey: "kl_filt_grp_tab_memory",
      optionKeys: ["tab_mem_64", "tab_mem_128", "tab_mem_256p"],
    },
  ],
};

export const KOMPJUTER_TYPE_PHOTOS: Record<KompjuterHubTypeName, string> = {
  "Desktop PC":
    "https://images.pexels.com/photos/30469974/pexels-photo-30469974.jpeg?auto=compress&cs=tinysrgb&w=400",
  Laptopë: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80",
  Monitorë: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80",
  "Pjesë Harduerike":
    "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=400&q=80",
  Serverë: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&q=80",
  Tabletë:
    "https://images.pexels.com/photos/28461044/pexels-photo-28461044.jpeg?auto=compress&cs=tinysrgb&w=400",
};

export function isKompjuterHubTypeName(name: string): name is KompjuterHubTypeName {
  return (KOMPJUTER_HUB_TYPE_NAMES as readonly string[]).includes(name);
}
