/** German UI strings — merged into TRANSLATIONS.de in market-context.tsx */
export const DE_TRANSLATIONS: Record<string, string> = {
  title: "Anzeigen",
  search: "Anzeigen suchen...",
  searchBtn: "Suchen",
  searchShopsSection: "Shops",
  filters: "Filter",
  category: "Kategorie",
  city: "Stadt",
  minPrice: "Mindestpreis",
  maxPrice: "Höchstpreis",
  apply: "Anwenden",
  clear: "Zurücksetzen",
  noResults: "Keine Anzeigen gefunden",
  noResultsSub: "Filter ändern oder eine neue Anzeige aufgeben",
  post: "Anzeige aufgeben",
  postFree: "Kostenlos inserieren",
  shopSuggestBanner: `💡 Haben Sie einen Shop? Eröffnen Sie Ihren kostenlosen digitalen Shop und bündeln Sie alle Ihre Anzeigen an einem Ort!`,
  shopSuggestBannerBtn: "Shop eröffnen →",
  all: "Alle",
  today: "Heute",
  views: "Aufrufe",
  total: "Anzeigen insgesamt",
  in: "in",
  page: "Seite",
  of: "von",
  hero: "KetuJemi — Kaufen und Verkaufen",
  heroSub: "Kaufen und verkaufen auf dem Balkan — kostenlose Anzeigenplattform",
  categories: "Kategorien",
  viewAll: "Alle anzeigen",
  trust1: "SMS- und E-Mail-Verifizierung",
  trust2: "Kostenlose Veröffentlichung",
  trust3: "21 Kategorien",
  markets: "KetuJemi in 11 Märkten",
  back: "Zurück",
  edit: "Bearbeiten",
  delete: "Löschen",
  cancel: "Abbrechen",
  saveChanges: "Änderungen speichern",
  saving: "Wird gespeichert...",
  promoted: "Hervorgehoben",
  agreement: "Verhandelbar",
  description: "Beschreibung",
  details: "Details",
  noPhoto: "Kein Foto",
  seller: "Verkäufer",
  privateSeller: "Privatverkäufer",
  sellerOnline: "Online",
  callSeller: "Anrufen",
  whatsapp: "WhatsApp-Nachricht",
  share_sectionTitle: "Diese Anzeige teilen",
  share_motivation: "💡 Teilen Sie Ihre Anzeige — jeder Klick bringt kostenlos neue Kunden in Ihren Shop!",
  share_facebook: "Facebook",
  share_whatsapp: "WhatsApp",
  share_instagram: "Instagram",
  share_tiktok: "TikTok",
  share_instagramCopyTooltip: "In Instagram-Story einfügen",
  share_tiktokCopyTooltip: "Link für TikTok kopieren",
  share_socialPostedTitle: "Anzeige in sozialen Netzwerken geteilt",
  share_socialPostedHint: "Erneut mit Ihren Freunden teilen — jedes Teilen erhöht die Aufrufe Ihrer Anzeige.",
  share_socialPostedIgDialogTitle: "Auf Instagram teilen",
  share_socialPostedIgDialogBody: `Kopieren Sie den Anzeigenlink und fügen Sie ihn in Ihre Instagram-Story, Ihren Reel oder Beitrag ein.`,
  share_socialPostedIgCopied: "✓ Link kopiert! Öffnen Sie Instagram und teilen Sie ihn in Ihrer Story oder Ihrem Beitrag.",
  share_socialPostedOpenInstagram: "Instagram öffnen",
  share_copyLink: "🔗 Link kopieren",
  share_copied: "✓ Link kopiert! Posten Sie ihn auf Instagram oder TikTok für mehr Kunden 🚀",
  share_socialApps: "📲 Instagram / TikTok",
  share_toastSocial: `✓ Link kopiert! Öffnen Sie Instagram oder TikTok und posten Sie ihn in Ihrer Story oder Ihrem Feed 📲`,
  share_compactLabel: "Teilen",
  caution: "⚠ Achtung",
  cautionTip1: "Treffen Sie den Verkäufer persönlich",
  cautionTip2: "Artikel vor der Zahlung prüfen",
  cautionTip3: "Kein Geld im Voraus überweisen",
  cautionTip4: "Verdächtiges Verhalten melden",
  deleteTitle: "Anzeige löschen?",
  deleteDesc: "Diese Aktion ist unwiderruflich. Die Anzeige wird dauerhaft gelöscht.",
  deleteSuccess: "Anzeige erfolgreich gelöscht",
  deleteError: "Fehler beim Löschen",
  listingNotFound: "Anzeige nicht gefunden",
  listingNotFoundSub: "Sie wurde möglicherweise gelöscht oder der Link ist fehlerhaft.",
  backToListings: "Zurück zu den Anzeigen",
  conditionNew: "Neu",
  conditionGood: "Sehr guter Zustand",
  conditionUsed: "Gebraucht",
  conditionDamaged: "Beschädigt",
  bodyType: "Karosserietyp",
  chooseBrand: "Marke auswählen",
  noListingsYet: "Noch keine Anzeigen",
  beFirst: "Seien Sie der Erste, der in dieser Kategorie inseriert!",
  kerkojEmptyTitle: "Noch keine Gesuche",
  kerkojEmptySub: `Suchen Sie etwas, das Sie anderswo nicht finden? Beschreiben Sie, was Sie brauchen, und veröffentlichen Sie Ihr Gesuch hier — Personen, die den Artikel haben, sehen es und können sich schnell bei Ihnen melden.`,
  kerkojEmptyTrust: "Ihr Gesuch wird hier wie jede andere Anzeige angezeigt.",
  kerkojEmptyPost: "Gesuch aufgeben",
  kerkojHubIntroTitle: "Ich möchte kaufen — Gesuch aufgeben",
  kerkojFormBanner: `Dies ist ein Kaufgesuch — beschreiben Sie, was Sie suchen. Ihr Gesuch wird auf der Plattform veröffentlicht und erreicht Personen und Shops, die diesen Artikel führen, damit Sie schneller finden, was Sie brauchen.`,
  kerkojFormPhotoHint: `📸 Fügen Sie Fotos hinzu, die zeigen, was Sie suchen (Modell, Farbe, Zustand…) — Verkäufer verstehen Sie besser und melden sich schneller.`,
  kerkojFormTitlePh: "z.B. Suche BMW X5 Diesel 2018+, iPhone 14 Pro 256GB, Kinderwagen...",
  kerkojFormDescPh: `Beschreiben Sie ausführlich: was Sie suchen, Modell, Spezifikationen, gewünschten Zustand, Budget (optional), woher Sie es abholen können. Je klarer das Gesuch, desto schneller meldet sich jemand.`,
  kerkojFormDescNote: `Ihr Gesuch gelangt direkt an Personen und Shops, die diese Art von Artikel führen — nicht nur an die öffentliche Liste.`,
  kerkojFormPostTitle: "Gesuch aufgeben",
  kerkojFormTitleLbl: "Titel des Gesuchs",
  kerkojFormPhotosLbl: "Fotos des Gesuchs",
  kerkojFormClickPhoto: "Klicken, um Fotos hinzuzufügen — zeigen Sie, was Sie suchen",
  kerkojFormDescSection: "Beschreibung des Gesuchs",
  postFromAnywhere: "Sie können von überall aus inserieren.",
  allListings: "Alle Anzeigen",
  listings: "Anzeigen",
  brandsAvail: "Marken verfügbar",
  subcategoriesAvail: "Unterkategorien verfügbar",
  totalLabel: "gesamt",
  postTitle: "Anzeige aufgeben",
  mainCategory: "Hauptkategorie",
  chooseCategory: "Kategorie auswählen...",
  subcategory: "Unterkategorie",
  fj_guide_includes: "Was diese Kategorie umfasst",
  fj_guide_conditions: "Wie Sie den Zustand in Ihrer Anzeige beschreiben",
  fj_guide_col_state: "Zustand",
  fj_guide_col_meaning: "Was schreiben",
  bodyTypeLabel: "Karosserietyp",
  chooseType: "Typ auswählen...",
  chooseMark: "Marke auswählen...",
  chooseSubcategory: "Unterkategorie auswählen...",
  subcategoryTitleMinHint: `Geben Sie einen Titel ein (min. 5 Zeichen) — dann wählen Sie oder die Unterkategorie wird automatisch festgelegt.`,
  subcategoryAutoSetting: "Unterkategorie wird festgelegt…",
  titlePlaceholderExample: "z.B. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
  postErrTitleForSubcategory: "Geben Sie einen Titel (mindestens 5 Zeichen) ein, damit das System die Unterkategorie festlegt.",
  postErrChooseSubcategory: "Wählen Sie eine Unterkategorie aus der Liste, oder warten Sie einen Moment nach der Titeleingabe.",
  postErrChooseBrand: "Wählen Sie die Marke / das Modell des Produkts.",
  photoAnalyzeFailed: "Automatisches Ausfüllen nicht möglich",
  photoAnalyzeFailedHint: `Fahren Sie manuell mit Kategorie, Titel und Beschreibung fort — oder versuchen Sie ein schärferes Foto.`,
  photoAnalyzeLoginRequired: "Sie müssen angemeldet sein",
  photoAnalyzeLoginRequiredHint: "Melden Sie sich an und versuchen Sie erneut, das Foto zu senden.",
  photoAnalyzeUnavailable: "Fotoanalyse ist vorübergehend nicht verfügbar",
  photoAnalyzeUnavailableHint: "Füllen Sie Kategorie, Titel und Beschreibung manuell aus.",
  choose: "Auswählen...",
  chooseYear: "Jahr auswählen...",
  chooseCity: "Stadt auswählen...",
  zodParentCategory: "Wählen Sie eine Hauptkategorie.",
  zodTitleMin: "Der Titel muss mindestens 5 Zeichen enthalten.",
  zodDescriptionMin: "Die Beschreibung muss mindestens 15 Zeichen enthalten.",
  zodLocation: "Wählen Sie eine Stadt.",
  zodPhoneMin: "Die Telefonnummer muss mindestens 5 Ziffern enthalten.",
  zodSellerName: "Geben Sie den Namen des Verkäufers ein.",
  formInvalidSummary: `Füllen Sie alle Pflichtfelder aus (Kategorie, Titel min. 5, Beschreibung min. 15, Foto, Preis, Stadt).`,
  videoInvalidFormatTitle: "Ungültiges Format",
  videoInvalidFormatDesc: "Nur MP4, MOV und AVI werden akzeptiert.",
  videoPreparingTitle: "Video wird vorbereitet...",
  videoPreparingHint: "Das Video wird für Ihre Anzeige optimiert (max. 100 MB). Schließen Sie diese Seite nicht.",
  videoAnalyzeFrameHint: `Ein Bild aus dem Video konnte nicht gelesen werden. Versuchen Sie einen kürzeren Clip mit guter Beleuchtung oder fügen Sie ein Foto hinzu.`,
  similarListingsHeading: "Das könnte Ihnen auch gefallen",
  titleField: "Titel",
  listingTitle: "Titel der Anzeige",
  descField: "Beschreibung",
  descPlaceholder: "Beschreiben Sie Ihr Produkt oder Ihre Dienstleistung ausführlich...",
  priceField: "Preis",
  priceEur: "Preis (EUR)",
  agreementToggle: "Verhandelbar (Preis für Angebote offen)",
  conditionField: "Zustand",
  locationSection: "Standort",
  contactSection: "Kontakt",
  yourName: "Ihr Name",
  phoneNum: "Telefonnummer",
  mainPhotoLabel: "Hauptfoto",
  photosSection: "Fotos",
  listingPhotos: "Anzeigenfotos",
  listingPhotosMinHint: "(mind. 1)",
  addPhoto: "Foto hinzufügen",
  photoCameraBtn: "Foto mit Kamera aufnehmen",
  videoCameraBtn: "Video mit Kamera aufnehmen",
  clickToSelect: "Tippen, um Fotos auf Ihrem Gerät auszuwählen",
  uploading: "Wird hochgeladen...",
  waitPlease: "Bitte warten",
  analyzingPhoto: "Foto wird von unserem System analysiert...",
  analyzingPhotoHint: "Kategorie, Titel und Beschreibung werden automatisch ausgefüllt.",
  firstPhotoAiHint: `📸 Laden Sie Ihr erstes Foto hoch und unser System füllt automatisch Kategorie, Titel und Beschreibung aus — spart Zeit und vereinfacht die Veröffentlichung!`,
  firstPhotoAiHintShop: `📸 Laden Sie ein Produktfoto hoch — unser System füllt automatisch Kategorie, Titel und Beschreibung für Ihren Shop aus. Verkaufen Sie schneller!`,
  systemHelpBtn: "Hilfe von unserem System",
  descriptionHelperAccept: "Übernehmen",
  descriptionHelperIgnore: "Ignorieren",
  postingSuggestionsTitle: "Vorschläge von unserem System",
  postingSuggestionsLoading: "Ihre Anzeige wird analysiert…",
  firstPhotoMain: "Das erste Foto wird das Hauptbild der Anzeige",
  carDetails: "Fahrzeugdetails",
  houseDetails: "Immobiliendetails",
  phoneDetails: "Telefondetails",
  yearField: "Jahr",
  mileageField: "Kilometerstand",
  fuelField: "Kraftstoff",
  transmissionField: "Getriebe",
  colorField: "Farbe",
  engineField: "Motor (L)",
  powerField: "Leistung (PS)",
  techCondField: "Technischer Zustand",
  areaField: "Fläche (m²)",
  floorField: "Etage",
  roomsField: "Zimmer",
  furnishedField: "Möblierung",
  brandField: "Marke",
  modelField: "Modell",
  capacityField: "Kapazität",
  yes: "Ja",
  no: "Nein",
  posting: "Wird veröffentlicht...",
  submitListing: "Anzeige aufgeben →",
  successPost: "✓ Anzeige erfolgreich veröffentlicht!",
  postError: "Fehler bei der Veröffentlichung",
  postRefusedTitle: "Nicht veröffentlicht",
  tooManyPhotos: "Sie können noch",
  photosSuffix: "Fotos hinzufügen",
  addAtLeastPhoto: "Fügen Sie mindestens 1 Foto hinzu",
  uploadFailed: "Upload fehlgeschlagen. Erneut versuchen.",
  editListingTitle: "Anzeige bearbeiten",
  editAnalyzePhotoBtn: "Foto mit KI analysieren",
  editUploadPhotoBtn: "Foto hochladen",
  editPhotoAnalyzeOk: "Titel und Beschreibung aus dem Foto aktualisiert.",
  backToListing: "Zurück zur Anzeige",
  imageUrlField: "Foto-URL (optional)",
  promoteLabel: "Hervorheben",
  promoteDesc: "Die Anzeige erscheint im hervorgehobenen Bereich",
  updateSuccess: "Anzeige erfolgreich aktualisiert!",
  updateError: "Fehler bei der Aktualisierung",
  conditionNewSub: "Nie benutzt",
  conditionUsedSub: "Bereits benutzt",
  conditionDamagedSub: "Defekt / Unfallschaden",
  marketsTagline: "Kosovo · Albanien · Nordmazedonien · Montenegro",
  marketsBannerLine: `Kosovo - Albanien - Nordmazedonien - Montenegro - Deutschland - Schweiz - Österreich - Frankreich - Italien - Vereinigtes Königreich - USA`,
  terms: "Nutzungsbedingungen",
  businessRules: "Unternehmen",
  privacy: "Datenschutz",
  contact: "Kontakt",
  faq: "FAQ",
  aboutUs: "Über uns",
  security: "Sicherheit",
  footer_colHelp: "HILFE",
  footer_colInfo: "INFO",
  footer_colBusiness: "UNTERNEHMEN",
  footer_colMarkets: "MÄRKTE",
  footer_diaspora: "Diaspora",
  footer_contactUs: "Kontakt",
  footer_onlineSecurity: "Online-Sicherheit",
  footer_press: "Presse",
  footer_aboutKetuJemi: "Über KetuJemi",
  footer_rules: "Regeln",
  footer_cookies: "Cookies",
  footer_openShop: "Shop eröffnen",
  footer_vipPackages: "VIP-Pakete",
  footer_advertise: "Werbung",
  footer_partnership: "Partnerschaft",
  footer_operatedBy: "Betrieben von REVOLUTION INVEST SH.P.K.",
  featured: "Hervorgehoben",
  recent: "Neueste Anzeigen",
  listingsCount: "Anzeigen",
  citiesLabel: "Hauptstädte",
  authLogin: "Anmelden",
  authLogout: "Abmelden",
  contactRequiresLogin: "Melden Sie sich an, um den Verkäufer zu kontaktieren",
  listingAccessDenied: "Sie haben keine Berechtigung, diese Anzeige zu bearbeiten",
  loginToViewPhone: "Melden Sie sich an, um die Telefonnummer zu sehen",
  sendSms: "SMS senden",
  postQuotaExceeded: "Sie haben das Limit für kostenlose Veröffentlichungen in dieser Kategorie erreicht.",
  postQuotaRemaining: "Verbleibende kostenlose Veröffentlichungen in dieser Kategorie: {n}",
};
