/** German UI strings — merged into TRANSLATIONS.de in market-context.tsx */
export const DE_TRANSLATIONS: Record<string, string> = {
  title: "Anzeigen",
  searchShopsSection: "Shops",
  filters: "Filter",
  minPrice: "Mindestpreis",
  clear: "Zurücksetzen",
  noResultsSub: "Filter ändern oder eine neue Anzeige aufgeben",
  post: "Anzeige aufgeben",
  shopSuggestBanner: "💡 Have a shop? Open your free digital shop and showcase all your listings in one place!",
  shopSuggestBannerBtn: "Open shop →",
  all: "Alle",
  views: "views",
  page: "Page",
  hero: "KetuJemi — Kaufen & Verkaufen",
  heroSub: "Buy & sell across the Balkans — kostenlose Kleinanzeigen-Plattform",
  categories: "Kategorien",
  trust1: "SMS & email verification",
  markets: "KetuJemi in 11 markets",
  back: "Zurück",
  saveChanges: "Speichern",
  promoted: "Promoted",
  description: "Beschreibung",
  seller: "Verkäufer",
  callSeller: "Anrufen",
  share_sectionTitle: "Teilen this listing",
  share_motivation: "💡 Teilen your listing — every click brings new customers to your shop for free!",
  share_facebook: "Facebook",
  share_whatsapp: "WhatsApp",
  share_instagram: "Instagram",
  share_tiktok: "TikTok",
  share_instagramCopyTooltip: "Paste to Instagram Story",
  share_tiktokCopyTooltip: "Copy link for TikTok",
  share_socialPostedTitle: "Listing published on social media",
  share_socialPostedHint: "Teilen again with friends — every share brings more views to your listing.",
  share_socialPostedIgDialogTitle: "Teilen on Instagram",
  share_socialPostedIgDialogBody: "Copy the listing link and paste it to your story, reels, or feed on Instagram.",
  share_socialPostedIgCopied: "✓ Link copied! Open Instagram and share it to your story or post.",
  share_socialPostedOpenInstagram: "Open Instagram",
  share_copyLink: "🔗 Copy link",
  share_copied: "✓ Link copied! Post it on Instagram or TikTok for more customers 🚀",
  share_socialApps: "📲 Instagram / TikTok",
  share_toastSocial: "✓ Link copied! Open Instagram or TikTok and post it to your story or feed 📲",
  share_compactLabel: "Teilen",
  caution: "⚠ Caution",
  cautionTip1: "Meet the seller in person",
  cautionTip2: "Inspect the item before paying",
  cautionTip3: "Do not send money in advance",
  cautionTip4: "Report anything suspicious",
  deleteTitle: "Anzeige löschen?",
  deleteDesc: "Dies kann nicht rückgängig gemacht werden. Die Anzeige wird dauerhaft entfernt.",
  deleteSuccess: "Listing deleted successfully",
  deleteError: "Error while deleting",
  listingNotFound: "Listing not found",
  listingNotFoundSub: "It may have been removed or the link is incorrect.",
  backToListings: "Zurück to listings",
  conditionNew: "New",
  conditionUsed: "Used",
  bodyType: "Body type",
  chooseBrand: "Marke wählen",
  noListingsYet: "Nein listings yet",
  beFirst: "Seien Sie der Erste in dieser Kategorie!",
  kerkojEmptyTitle: "Nein requests yet",
  kerkojEmptySub: `Looking for something you cannot find? Post your request here — people who have the item will see it and can contact you quickly.`,
  kerkojEmptyTrust: "Your listing appears here like any other listing.",
  kerkojEmptyPost: "Post request",
  kerkojHubIntroTitle: "Looking to buy — post your request",
  kerkojFormBanner: `This is a buying request — describe what you are looking for. Your request is published on the platform and reaches people and shops who deal with that item, so you can find what you need faster.`,
  kerkojFormPhotoHint: `📸 Add photos that show what you are looking for (model, colour, condition…) — sellers understand you more easily and contact you faster.`,
  kerkojFormTitlePh: "e.g. Looking for BMW X5 diesel 2018+, iPhone 14 Pro 256GB, baby stroller...",
  kerkojFormDescPh: `Describe in detail: what you need, model, specs, preferred condition, budget (optional), where you can pick it up. The clearer the request, the faster someone who has the item will contact you.`,
  kerkojFormDescNote: `Your request goes directly to people and shops who deal with this type of item — not only the public listing.`,
  kerkojFormPostTitle: "Post request",
  kerkojFormTitleLbl: "Request title",
  kerkojFormPhotosLbl: "Request photos",
  kerkojFormClickPhoto: "Tap to add photos — show what you are looking for",
  kerkojFormDescSection: "Request description",
  postFromAnywhere: "You can post from anywhere.",
  allListings: "Alle listings",
  listings: "Anzeigen",
  brandsAvail: "Marken verfügbar",
  subcategoriesAvail: "Unterkategorien verfügbar",
  totalLabel: "total",
  postTitle: "Anzeige aufgeben",
  mainCategory: "Hauptkategorie",
  chooseCategory: "Kategorie wählen...",
  subcategory: "Subcategory",
  fj_guide_includes: "What this category includes",
  fj_guide_conditions: "How to describe condition in your listing",
  fj_guide_col_state: "Condition",
  fj_guide_col_meaning: "What to write",
  bodyTypeLabel: "Body type",
  chooseType: "Choose type...",
  chooseMark: "Marke wählen...",
  chooseSubcategory: "Choose subcategory...",
  subcategoryTitleMinHint: "Enter a title (min. 5 characters) — then pick or the subcategory will be set automatically.",
  subcategoryAutoSetting: "Setting subcategory…",
  titlePlaceholderExample: "e.g. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
  postErrTitleForSubcategory: "Enter a title (at least 5 characters) so the system can set the subcategory.",
  postErrChooseSubcategory: "Choose a subcategory from the list, or wait a moment after entering the title.",
  postErrChooseBrand: "Choose the product brand / model.",
  photoAnalyzeFailed: "Could not fill in automatically",
  photoAnalyzeFailedHint: "Continue manually with category, title, and description — or try a clearer photo.",
  photoAnalyzeLoginRequired: "You need to be logged in",
  photoAnalyzeLoginRequiredHint: "Sign in and try uploading the photo again.",
  photoAnalyzeUnavailable: "Photo analysis is temporarily unavailable",
  photoAnalyzeUnavailableHint: "Fill in category, title, and description manually.",
  choose: "Choose...",
  chooseYear: "Jahr wählen...",
  chooseCity: "Stadt wählen...",
  zodParentCategory: "Choose a main category.",
  zodTitleMin: "Title must be at least 5 characters.",
  zodDescriptionMin: "Beschreibung must be at least 15 characters.",
  zodLocation: "Choose a city.",
  zodPhoneMin: "Phone must have at least 5 digits.",
  zodSellerName: "Enter the seller name.",
  formInvalidSummary: "Fill in all required fields (category, title min. 5, description min. 15, photo, price, city).",
  videoInvalidFormatTitle: "Invalid format",
  videoInvalidFormatDesc: "Only MP4, MOV, and AVI are allowed.",
  videoPreparingTitle: "Preparing video...",
  videoPreparingHint: "Video is being optimized for your listing (max 100 MB). Do not close this page.",
  videoAnalyzeFrameHint: "Could not read a frame from the video. Try a shorter clip with good lighting, or add a photo.",
  similarListingsHeading: "You may also like",
  titleField: "Title",
  listingTitle: "Listing title",
  descField: "Beschreibung",
  descPlaceholder: "Describe your product or service in detail...",
  priceField: "Price",
  priceEur: "Price (EUR)",
  agreementToggle: "Verhandelbar (price is open to offers)",
  conditionField: "Condition",
  locationSection: "Standort",
  contactSection: "Kontakt",
  yourName: "Your name",
  phoneNum: "Telefonnummer",
  mainPhotoLabel: "Main",
  photosSection: "Photos",
  listingPhotos: "Listing photos",
  addPhoto: "Add photo",
  photoCameraBtn: "Take photo with camera",
  videoCameraBtn: "Record video with camera",
  clickToSelect: "Tap to choose photos from your device",
  uploading: "Uploading...",
  waitPlease: "Please wait",
  analyzingPhoto: "Analyzing photo with our system...",
  analyzingPhotoHint: "Kategorie, title, and description are filled in automatically.",
  firstPhotoAiHint: `📸 Upload your first photo and our system will automatically fill in the category, title and description for you — saves time and makes listing easier!`,
  firstPhotoAiHintShop: `📸 Upload a product photo — our system will automatically fill in the category, title and description for your shop listing. Saves time and makes selling easier!`,
  systemHelpBtn: "Hilfe von unserem System",
  descriptionHelperAccept: "Accept",
  descriptionHelperIgnore: "Ignore",
  postingSuggestionsTitle: "Suggestions from our system",
  postingSuggestionsLoading: "Analyzing your listing…",
  firstPhotoMain: "The first photo will be the main listing image",
  carDetails: "Vehicle details",
  houseDetails: "Property details",
  phoneDetails: "Phone details",
  yearField: "Year",
  mileageField: "Mileage",
  fuelField: "Fuel",
  transmissionField: "Transmission",
  colorField: "Color",
  engineField: "Engine (L)",
  powerField: "Power (hp)",
  techCondField: "Technisch condition",
  areaField: "Area (m²)",
  floorField: "Floor",
  roomsField: "Rooms",
  furnishedField: "Furnishing",
  brandField: "Brand",
  modelField: "Model",
  capacityField: "Capacity",
  yes: "Ja",
  posting: "Veröffentlichung...",
  submitListing: "Anzeige aufgeben →",
  successPost: "✓ Anzeige erfolgreich veröffentlicht!",
  postError: "Error while posting",
  postRefusedTitle: "Not posted",
  tooManyPhotos: "You can add",
  photosSuffix: "more photos",
  addAtLeastPhoto: "Add at least 1 photo",
  uploadFailed: "Upload failed. Try again.",
  editListingTitle: "Bearbeiten listing",
  editAnalyzePhotoBtn: "Analyze photo with AI",
  editUploadPhotoBtn: "Upload photo",
  editPhotoAnalyzeOk: "Title and description updated from the photo.",
  backToListing: "Zurück to listing",
  imageUrlField: "Photo URL (optional)",
  promoteLabel: "Promote listing",
  promoteDesc: "Listing will appear in the promoted section",
  updateSuccess: "Listing updated successfully!",
  updateError: "Error while updating",
  conditionNewSub: "Unused",
  conditionUsedSub: "Previously used",
  conditionDamagedSub: "Defective / accident",
  marketsTagline: "Kosovo · Albanien · Nordmazedonien · Montenegro",
  marketsBannerLine: `Kosovo - Albanien - Nordmazedonien - Montenegro - Deutschland - Schweiz - Österreich - Frankreich - Italien - UK - USA`,
  terms: "AGB",
  businessRules: "Business",
  privacy: "Datenschutz",
  contact: "Kontakt",
  faq: "FAQ",
  aboutUs: "Über uns",
  security: "Sicherheit",
  footer_colHelp: "HELP",
  footer_colInfo: "INFO",
  footer_colBusiness: "BUSINESS",
  footer_colMarkets: "MARKETS",
  footer_diaspora: "Diaspora",
  footer_contactUs: "Kontaktieren Sie uns",
  footer_onlineSecurity: "Online-Sicherheit",
  footer_press: "Press",
  footer_aboutKetuJemi: "About KetuJemi",
  footer_rules: "Rules",
  footer_cookies: "Cookies",
  footer_openShop: "Open a shop",
  footer_vipPackages: "VIP packages",
  footer_advertise: "Advertise",
  footer_partnership: "Partnership",
  footer_operatedBy: "Operated by REVOLUTION INVEST SH.P.K.",
  featured: "Featured",
  listingsCount: "listings",
  authLogin: "Anmelden",
  authLogout: "Log out",
  contactRequiresLogin: "Anmelden to contact the seller",
  listingAccessDenied: "You do not have permission to edit this listing",
  loginToViewPhone: "Anmelden to see the phone number",
  sendSms: "Send SMS",
  postQuotaExceeded: "You have reached the free posting limit for this category.",
  postQuotaRemaining: "Free posts remaining in this category: {n}",
};
