import { createContext, useContext, useState, useEffect, useMemo, type ReactNode } from "react";
import {
  DEFAULT_UI_LANG,
  isUiLang,
  translationKeyForUiLang,
  type UiLang,
} from "./ui-languages";

export const MARKETS = [
  { code: "ks",  flag: "🇽🇰", name: "Kosovë",             currency: "EUR", symbol: "€",   prefix: "+383" },
  { code: "al",  flag: "🇦🇱", name: "Shqipëri",           currency: "ALL", symbol: "L",   prefix: "+355" },
  { code: "mk",  flag: "🇲🇰", name: "Maqedoni e Veriut",  currency: "MKD", symbol: "ден", prefix: "+389" },
  { code: "mne", flag: "🇲🇪", name: "Mal i Zi",           currency: "EUR", symbol: "€",   prefix: "+382" },
  { code: "de",  flag: "🇩🇪", name: "Gjermani",           currency: "EUR", symbol: "€",   prefix: "+49" },
  { code: "at",  flag: "🇦🇹", name: "Austri",             currency: "EUR", symbol: "€",   prefix: "+43" },
  { code: "ch",  flag: "🇨🇭", name: "Zvicër",             currency: "CHF", symbol: "CHF", prefix: "+41" },
  { code: "it",  flag: "🇮🇹", name: "Itali",              currency: "EUR", symbol: "€",   prefix: "+39" },
  { code: "fr",  flag: "🇫🇷", name: "Francë",             currency: "EUR", symbol: "€",   prefix: "+33" },
  { code: "gb",  flag: "🇬🇧", name: "Angli",              currency: "GBP", symbol: "£",   prefix: "+44" },
  { code: "us",  flag: "🇺🇸", name: "SHBA",               currency: "USD", symbol: "$",   prefix: "+1" },
] as const;

export type Market = (typeof MARKETS)[number];

let _ratesCache: Record<string, number> = { EUR: 1, ALL: 109.5, MKD: 61.5 };
let _ratesFetched = false;

export async function fetchLiveRates(): Promise<Record<string, number>> {
  if (_ratesFetched) return _ratesCache;
  try {
    const res = await fetch("/api/exchange-rates");
    if (res.ok) { _ratesCache = await res.json(); }
  } catch {}
  _ratesFetched = true;
  return _ratesCache;
}

export function convertPrice(eurPrice: number, market: Market, rates: Record<string, number>): string {
  if (market.currency === "EUR") return `${eurPrice.toLocaleString()} ${market.symbol}`;
  const rate = rates[market.currency] ?? 1;
  return `${Math.round(eurPrice * rate).toLocaleString()} ${market.symbol}`;
}

// ─── Translations ─────────────────────────────────────────────────────────────
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  ks: {
    // Listings / filter
    title: "Shpalljet", search: "Kërko shpallje...", searchBtn: "Kërko",
    filters: "Filtrat", category: "Kategoria", city: "Qyteti",
    minPrice: "Çmimi min", maxPrice: "Çmimi max", apply: "Zbato",
    clear: "Pastro", noResults: "Nuk u gjet asnjë shpallje",
    noResultsSub: "Provo të ndryshosh filtrat ose posto shpallje të re",
    post: "Posto Shpallje", postFree: "Posto Falas", all: "Të gjitha", today: "Sot",
    views: "shikime", total: "shpallje gjithsej", in: "në",
    page: "Faqja", of: "nga",
    // Home
    hero: "KetuJemi — Bli & Shit",
    heroSub: "Bli & shit në Kosovë — platforma e shpalljeve falas",
    categories: "Kategoritë", viewAll: "Shiko të gjitha",
    trust1: "Verifikim SMS & Email", trust2: "Posto falas", trust3: "18 kategori",
    markets: "KetuJemi në 11 tregje",
    // Common actions
    back: "Kthehu", edit: "Edito", delete: "Fshi", cancel: "Anulo",
    saveChanges: "Ruaj ndryshimet", saving: "Duke ruajtur...",
    promoted: "Promovuar", agreement: "Me marrëveshje",
    // Listing detail
    description: "Përshkrimi", details: "Detajet", noPhoto: "Nuk ka foto",
    seller: "Shitësi", privateSeller: "Shitës privat",
    callSeller: "Telefono", whatsapp: "Dërgo Mesazh (WhatsApp)",
    caution: "⚠ Kujdes",
    cautionTip1: "Takohu me shitësin personalisht",
    cautionTip2: "Kontrolloje produktin para pagesës",
    cautionTip3: "Mos dërgo para paraprakisht",
    cautionTip4: "Raporto nëse vëren diçka të dyshimtë",
    deleteTitle: "Fshi shpalljen?",
    deleteDesc: "Kjo veprim nuk mund të zhbehet. Shpallja do të fshihet përgjithmonë.",
    deleteSuccess: "Shpallja u fshi me sukses",
    deleteError: "Gabim gjatë fshirjes",
    listingNotFound: "Shpallja nuk u gjet",
    listingNotFoundSub: "Mund të jetë fshirë ose mund të kesh një link të gabuar.",
    backToListings: "Kthehu te shpalljet",
    conditionNew: "I ri", conditionGood: "Shumë mirë",
    conditionUsed: "I përdorur", conditionDamaged: "I dëmtuar",
    // Category page
    bodyType: "Lloji i karocerisë",
    chooseBrand: "Zgjidh markën",
    noListingsYet: "Nuk ka njoftime ende",
    beFirst: "Bëhu i pari që posto në këtë kategori!",
    allListings: "Të gjitha njoftimet",
    listings: "Njoftimet",
    brandsAvail: "marka të disponueshme",
    totalLabel: "gjithsej",
    // Post / Edit form
    postTitle: "Posto Shpallje",
    mainCategory: "Kategoria kryesore",
    chooseCategory: "Zgjidh kategorinë...",
    subcategory: "Nënkategoria",
    bodyTypeLabel: "Tipi i karocerisë",
    chooseType: "Zgjidh tipin...",
    chooseMark: "Zgjidh markën...",
    choose: "Zgjidh...",
    chooseYear: "Zgjidh vitin...",
    chooseCity: "Zgjidh qytetin...",
    titleField: "Titulli",
    listingTitle: "Titulli i shpalljes",
    descField: "Përshkrimi",
    descPlaceholder: "Pershkruani në detaje produktin ose shërbimin tuaj...",
    priceField: "Çmimi",
    priceEur: "Çmimi (EUR)",
    agreementToggle: "Me marrëveshje (çmimi është i negociueshëm)",
    conditionField: "Gjendja",
    locationSection: "Vendndodhja",
    contactSection: "Kontakti",
    yourName: "Emri juaj",
    phoneNum: "Nr. telefonit",
    mainPhotoLabel: "Kryesore",
    photosSection: "Fotot",
    listingPhotos: "Fotot e shpalljes",
    addPhoto: "Shto foto",
    clickToSelect: "Kliko për të zgjedhur foto nga pajisja jote",
    uploading: "Duke ngarkuar...",
    waitPlease: "Ju lutemi prisni",
    firstPhotoMain: "Foto e parë do të jetë foto kryesore e shpalljes",
    carDetails: "Detajet e automjetit",
    houseDetails: "Detajet e pronës",
    phoneDetails: "Detajet e telefonit",
    yearField: "Viti i prodhimit",
    mileageField: "Kilometrazha",
    fuelField: "Karburanti",
    transmissionField: "Transmisioni",
    colorField: "Ngjyra",
    engineField: "Motori (L)",
    powerField: "Fuqia (hp)",
    techCondField: "Gjendja teknike",
    areaField: "Sipërfaqja (m²)",
    floorField: "Kati",
    roomsField: "Numri dhomave",
    furnishedField: "Mobilimi",
    brandField: "Marka",
    modelField: "Modeli",
    capacityField: "Kapaciteti",
    yes: "Po", no: "Jo",
    posting: "Duke postuar...",
    submitListing: "Posto Shpalljen →",
    successPost: "✓ Shpallja u postua me sukses!",
    postError: "Gabim gjatë postimit",
    tooManyPhotos: "Mund të shtosh edhe",
    photosSuffix: "foto",
    addAtLeastPhoto: "Shto të paktën 1 foto",
    uploadFailed: "Ngarkimi dështoi. Provo sërish.",
    editListingTitle: "Edito Shpalljen",
    backToListing: "Kthehu te shpallja",
    imageUrlField: "URL e fotos (opsionale)",
    promoteLabel: "Promovo shpalljen",
    promoteDesc: "Shpallja do të shfaqet në seksionin e promovuar",
    updateSuccess: "Shpallja u perditesua me sukses!",
    updateError: "Gabim gjate perditesimit",
    conditionNewSub: "Papërdorur",
    conditionUsedSub: "Ka qenë në përdorim",
    conditionDamagedSub: "Me defekt / aksident",
    marketsTagline: "Kosovë · Shqipëri · Maqedoni · Mal i Zi",
    marketsBannerLine:
      "Kosovë - Shqipëri - Maqedoni - Mal i Zi - Gjermani - Zvicër - Austri - Francë - Itali - Angli - SHBA",
    terms: "Kushtet",
    businessRules: "Bizneset",
    privacy: "Privatësia",
    contact: "Kontakti",
    faq: "FAQ",
    aboutUs: "Rreth Nesh",
    security: "Siguria",
    footer_colHelp: "NDIHMË",
    footer_colInfo: "INFORMATA",
    footer_colBusiness: "BIZNESE",
    footer_colMarkets: "TREGJET",
    footer_diaspora: "Diaspora",
    footer_contactUs: "Na kontaktoni",
    footer_onlineSecurity: "Siguria online",
    footer_press: "Shtypi",
    footer_aboutKetuJemi: "Rreth KetuJemi",
    footer_rules: "Rregullat",
    footer_cookies: "Cookies",
    footer_openShop: "Hap shitore",
    footer_vipPackages: "Paketa VIP",
    footer_advertise: "Reklamoni",
    footer_partnership: "Partneritet",
    footer_operatedBy: "Operohet nga REVOLUTION INVEST SH.P.K.",
    featured: "Të rekomanduara", recent: "Njoftimet e fundit",
    listingsCount: "shpallje", citiesLabel: "qytetet kryesore",
    authLogin: "Hyr",
    authLogout: "Dil",
    contactRequiresLogin: "Hyr për të kontaktuar shitësin",
    listingAccessDenied: "Nuk keni akses për ta ndryshuar këtë shpallje",
    loginToViewPhone: "Kyçu për të parë numrin",
    sendSms: "Dërgo SMS",
    postQuotaExceeded: "Ke arritur limitin e postimeve falas për këtë kategori.",
    postQuotaRemaining: "Postime falas të mbetura në këtë kategori: {n}",
  },
  al: {
    title: "Njoftimet", search: "Kërko njoftim...", searchBtn: "Kërko",
    filters: "Filtrat", category: "Kategoria", city: "Qyteti",
    minPrice: "Çmimi min", maxPrice: "Çmimi max", apply: "Zbato",
    clear: "Pastro", noResults: "Nuk u gjet asnjë njoftim",
    noResultsSub: "Provo të ndryshosh filtrat ose posto njoftim të ri",
    post: "Posto Njoftim", postFree: "Posto Falas", all: "Të gjitha", today: "Sot",
    views: "shikime", total: "njoftime gjithsej", in: "në",
    page: "Faqja", of: "nga",
    hero: "KetuJemi — Bli & Shit",
    heroSub: "Bli & shit në Shqipëri — platforma e njoftimeve falas",
    categories: "Kategoritë", viewAll: "Shiko të gjitha",
    trust1: "Verifikim SMS & Email", trust2: "Posto falas", trust3: "18 kategori",
    markets: "KetuJemi në 11 tregje",
    back: "Kthehu", edit: "Edito", delete: "Fshi", cancel: "Anulo",
    saveChanges: "Ruaj ndryshimet", saving: "Duke ruajtur...",
    promoted: "Promovuar", agreement: "Me marrëveshje",
    description: "Përshkrimi", details: "Detajet", noPhoto: "Nuk ka foto",
    seller: "Shitësi", privateSeller: "Shitës privat",
    callSeller: "Telefono", whatsapp: "Dërgo Mesazh (WhatsApp)",
    caution: "⚠ Kujdes",
    cautionTip1: "Takohu me shitësin personalisht",
    cautionTip2: "Kontrolloje produktin para pagesës",
    cautionTip3: "Mos dërgo para paraprakisht",
    cautionTip4: "Raporto nëse vëren diçka të dyshimtë",
    deleteTitle: "Fshi njoftimin?",
    deleteDesc: "Kjo veprim nuk mund të zhbehet. Njoftimi do të fshihet përgjithmonë.",
    deleteSuccess: "Njoftimi u fshi me sukses",
    deleteError: "Gabim gjatë fshirjes",
    listingNotFound: "Njoftimi nuk u gjet",
    listingNotFoundSub: "Mund të jetë fshirë ose mund të kesh një link të gabuar.",
    backToListings: "Kthehu te njoftimet",
    conditionNew: "I ri", conditionGood: "Shumë mirë",
    conditionUsed: "I përdorur", conditionDamaged: "I dëmtuar",
    bodyType: "Lloji i karocerisë",
    chooseBrand: "Zgjidh markën",
    noListingsYet: "Nuk ka njoftime ende",
    beFirst: "Bëhu i pari që posto në këtë kategori!",
    allListings: "Të gjitha njoftimet",
    listings: "Njoftimet",
    brandsAvail: "marka të disponueshme",
    totalLabel: "gjithsej",
    postTitle: "Posto Njoftim",
    mainCategory: "Kategoria kryesore",
    chooseCategory: "Zgjidh kategorinë...",
    subcategory: "Nënkategoria",
    bodyTypeLabel: "Tipi i karocerisë",
    chooseType: "Zgjidh tipin...",
    chooseMark: "Zgjidh markën...",
    choose: "Zgjidh...",
    chooseYear: "Zgjidh vitin...",
    chooseCity: "Zgjidh qytetin...",
    titleField: "Titulli",
    listingTitle: "Titulli i njoftimit",
    descField: "Përshkrimi",
    descPlaceholder: "Pershkruani në detaje produktin ose shërbimin tuaj...",
    priceField: "Çmimi",
    priceEur: "Çmimi",
    agreementToggle: "Me marrëveshje (çmimi është i negociueshëm)",
    conditionField: "Gjendja",
    locationSection: "Vendndodhja",
    contactSection: "Kontakti",
    yourName: "Emri juaj",
    phoneNum: "Nr. telefonit",
    mainPhotoLabel: "Kryesore",
    photosSection: "Fotot",
    listingPhotos: "Fotot e njoftimit",
    addPhoto: "Shto foto",
    clickToSelect: "Kliko për të zgjedhur foto nga pajisja jote",
    uploading: "Duke ngarkuar...",
    waitPlease: "Ju lutemi prisni",
    firstPhotoMain: "Foto e parë do të jetë foto kryesore e njoftimit",
    carDetails: "Detajet e automjetit",
    houseDetails: "Detajet e pronës",
    phoneDetails: "Detajet e telefonit",
    yearField: "Viti i prodhimit",
    mileageField: "Kilometrazha",
    fuelField: "Karburanti",
    transmissionField: "Transmisioni",
    colorField: "Ngjyra",
    engineField: "Motori (L)",
    powerField: "Fuqia (hp)",
    techCondField: "Gjendja teknike",
    areaField: "Sipërfaqja (m²)",
    floorField: "Kati",
    roomsField: "Numri dhomave",
    furnishedField: "Mobilimi",
    brandField: "Marka",
    modelField: "Modeli",
    capacityField: "Kapaciteti",
    yes: "Po", no: "Jo",
    posting: "Duke postuar...",
    submitListing: "Posto Njoftimin →",
    successPost: "✓ Njoftimi u postua me sukses!",
    postError: "Gabim gjatë postimit",
    tooManyPhotos: "Mund të shtosh edhe",
    photosSuffix: "foto",
    addAtLeastPhoto: "Shto të paktën 1 foto",
    uploadFailed: "Ngarkimi dështoi. Provo sërish.",
    editListingTitle: "Edito Njoftimin",
    backToListing: "Kthehu te njoftimi",
    imageUrlField: "URL e fotos (opsionale)",
    promoteLabel: "Promovo njoftimin",
    promoteDesc: "Njoftimi do të shfaqet në seksionin e promovuar",
    updateSuccess: "Njoftimi u perditesua me sukses!",
    updateError: "Gabim gjate perditesimit",
    conditionNewSub: "Papërdorur",
    conditionUsedSub: "Ka qenë në përdorim",
    conditionDamagedSub: "Me defekt / aksident",
    marketsTagline: "Kosovë · Shqipëri · Maqedoni · Mal i Zi",
    marketsBannerLine:
      "Kosovë - Shqipëri - Maqedoni - Mal i Zi - Gjermani - Zvicër - Austri - Francë - Itali - Angli - SHBA",
    terms: "Kushtet",
    businessRules: "Bizneset",
    privacy: "Privatësia",
    contact: "Kontakti",
    faq: "FAQ",
    aboutUs: "Rreth Nesh",
    security: "Siguria",
    footer_colHelp: "NDIHMË",
    footer_colInfo: "INFORMATA",
    footer_colBusiness: "BIZNESE",
    footer_colMarkets: "TREGJET",
    footer_diaspora: "Diaspora",
    footer_contactUs: "Na kontaktoni",
    footer_onlineSecurity: "Siguria online",
    footer_press: "Shtypi",
    footer_aboutKetuJemi: "Rreth KetuJemi",
    footer_rules: "Rregullat",
    footer_cookies: "Cookies",
    footer_openShop: "Hap shitore",
    footer_vipPackages: "Paketa VIP",
    footer_advertise: "Reklamoni",
    footer_partnership: "Partneritet",
    footer_operatedBy: "Operohet nga REVOLUTION INVEST SH.P.K.",
    featured: "Të rekomanduara", recent: "Njoftimet e fundit",
    listingsCount: "njoftime", citiesLabel: "qytetet kryesore",
    authLogin: "Hyr",
    authLogout: "Dil",
    contactRequiresLogin: "Hyr për të kontaktuar shitësin",
    listingAccessDenied: "Nuk keni akses për ta ndryshuar këtë njoftim",
    loginToViewPhone: "Kyçu për të parë numrin",
    sendSms: "Dërgo SMS",
    postQuotaExceeded: "Ke arritur limitin e postimeve falas për këtë kategori.",
    postQuotaRemaining: "Postime falas të mbetura në këtë kategori: {n}",
  },
  mk: {
    title: "Огласи", search: "Барај оглас...", searchBtn: "Барај",
    filters: "Филтри", category: "Категорија", city: "Град",
    minPrice: "Цена МИН", maxPrice: "Цена МАКС", apply: "Примени",
    clear: "Исчисти", noResults: "Не се најдени огласи",
    noResultsSub: "Обидете се да ги промените филтрите или додајте нов оглас",
    post: "Додај оглас", postFree: "Објави бесплатно", all: "Сите", today: "Денес",
    views: "прегледи", total: "огласи вкупно", in: "во",
    page: "Страна", of: "од",
    hero: "KetuJemi — Купи & Продај",
    heroSub: "Купи & продавај во Македонија — бесплатни огласи",
    categories: "Категории", viewAll: "Види ги сите",
    trust1: "СМС и е-пошта верификација", trust2: "Бесплатно огласување", trust3: "18 категории",
    markets: "КетуЈеми на 11 пазари",
    back: "Назад", edit: "Уреди", delete: "Избриши", cancel: "Откажи",
    saveChanges: "Зачувај промени", saving: "Се зачувува...",
    promoted: "Промовиран", agreement: "По договор",
    description: "Опис", details: "Детали", noPhoto: "Нема фото",
    seller: "Продавач", privateSeller: "Приватен продавач",
    callSeller: "Телефонирај", whatsapp: "Испрати порака (WhatsApp)",
    caution: "⚠ Внимание",
    cautionTip1: "Сретни го продавачот лично",
    cautionTip2: "Провери го производот пред плаќање",
    cautionTip3: "Не испраќај пари однапред",
    cautionTip4: "Пријави ако забележиш нешто сомнително",
    deleteTitle: "Избриши оглас?",
    deleteDesc: "Оваа акција не може да се поврати. Огласот ќе биде трајно избришан.",
    deleteSuccess: "Огласот е успешно избришан",
    deleteError: "Грешка при бришење",
    listingNotFound: "Огласот не е најден",
    listingNotFoundSub: "Можеби е избришан или имате погрешен линк.",
    backToListings: "Назад кон огласите",
    conditionNew: "Нов", conditionGood: "Многу добро",
    conditionUsed: "Користен", conditionDamaged: "Оштетен",
    bodyType: "Тип на каросерија",
    chooseBrand: "Изберете марка",
    noListingsYet: "Нема огласи уште",
    beFirst: "Биди прв кој ќе огласи во оваа категорија!",
    allListings: "Сите огласи",
    listings: "Огласи",
    brandsAvail: "марки достапни",
    totalLabel: "вкупно",
    postTitle: "Додај оглас",
    mainCategory: "Главна категорија",
    chooseCategory: "Изберете категорија...",
    subcategory: "Подкатегорија",
    bodyTypeLabel: "Тип на каросерија",
    chooseType: "Изберете тип...",
    chooseMark: "Изберете марка...",
    choose: "Изберете...",
    chooseYear: "Изберете година...",
    chooseCity: "Изберете град...",
    titleField: "Наслов",
    listingTitle: "Наслов на оглас",
    descField: "Опис",
    descPlaceholder: "Опишете го производот или услугата детално...",
    priceField: "Цена",
    priceEur: "Цена (EUR)",
    agreementToggle: "По договор (цената е преговарачка)",
    conditionField: "Состојба",
    locationSection: "Локација",
    contactSection: "Контакт",
    yourName: "Вашето име",
    phoneNum: "Бр. телефон",
    mainPhotoLabel: "Главна",
    photosSection: "Фотографии",
    listingPhotos: "Фотографии на огласот",
    addPhoto: "Додај фото",
    clickToSelect: "Кликни за да изберете фото од уредот",
    uploading: "Се прикачува...",
    waitPlease: "Ве молиме почекајте",
    firstPhotoMain: "Првата фотографија ќе биде главна на огласот",
    carDetails: "Детали за возилото",
    houseDetails: "Детали за имотот",
    phoneDetails: "Детали за телефонот",
    yearField: "Година на производство",
    mileageField: "Километража",
    fuelField: "Гориво",
    transmissionField: "Менувач",
    colorField: "Боја",
    engineField: "Мотор (L)",
    powerField: "Снага (hp)",
    techCondField: "Техничка состојба",
    areaField: "Површина (m²)",
    floorField: "Кат",
    roomsField: "Број на соби",
    furnishedField: "Наместеност",
    brandField: "Марка",
    modelField: "Модел",
    capacityField: "Капацитет",
    yes: "Да", no: "Не",
    posting: "Се објавува...",
    submitListing: "Додај оглас →",
    successPost: "✓ Огласот е успешно објавен!",
    postError: "Грешка при објавување",
    tooManyPhotos: "Можете да додадете уште",
    photosSuffix: "фотографии",
    addAtLeastPhoto: "Додај барем 1 фотографија",
    uploadFailed: "Прикачувањето не успеа. Обидете се повторно.",
    editListingTitle: "Уреди оглас",
    backToListing: "Назад кон огласот",
    imageUrlField: "URL на фото (опционално)",
    promoteLabel: "Промовирај оглас",
    promoteDesc: "Огласот ќе биде прикажан во промовиран дел",
    updateSuccess: "Огласот е успешно ажуриран!",
    updateError: "Грешка при ажурирање",
    conditionNewSub: "Неупотребуван",
    conditionUsedSub: "Бил во употреба",
    conditionDamagedSub: "Со дефект / акцидент",
    marketsTagline: "Косово · Албанија · Македонија · Црна Гора",
    marketsBannerLine:
      "Косово - Албанија - Македонија - Црна Гора - Германија - Швајцарија - Австрија - Франција - Италија - Англија - САД",
    terms: "Услови",
    businessRules: "Бизнис",
    privacy: "Приватност",
    contact: "Контакт",
    faq: "FAQ",
    aboutUs: "За нас",
    security: "Безбедност",
    footer_colHelp: "ПОМОШ",
    footer_colInfo: "ИНФОРМАЦИИ",
    footer_colBusiness: "БИЗНИС",
    footer_colMarkets: "ПАЗАРИ",
    footer_diaspora: "Дијаспора",
    footer_contactUs: "Контактирајте нè",
    footer_onlineSecurity: "Онлајн безбедност",
    footer_press: "Медиуми",
    footer_aboutKetuJemi: "За KetuJemi",
    footer_rules: "Правила",
    footer_cookies: "Колачиња",
    footer_openShop: "Отвори продавница",
    footer_vipPackages: "VIP пакети",
    footer_advertise: "Рекламирај",
    footer_partnership: "Партнерство",
    footer_operatedBy: "Оперира REVOLUTION INVEST SH.P.K.",
    featured: "Препорачани", recent: "Последни огласи",
    listingsCount: "огласи", citiesLabel: "главни градови",
    authLogin: "Најави се",
    authLogout: "Одјави се",
    contactRequiresLogin: "Најави се за да го контактираш продавачот",
    listingAccessDenied: "Немате пристап за уредување на овој оглас",
    loginToViewPhone: "Најави се за да го видиш бројот",
    sendSms: "Испрати SMS",
    postQuotaExceeded: "Го достигнавте лимитот на бесплатни огласи за оваа категорија.",
    postQuotaRemaining: "Преостанати бесплатни огласи во оваа категорија: {n}",
  },
  mne: {
    title: "Oglasi", search: "Traži oglas...", searchBtn: "Traži",
    filters: "Filtri", category: "Kategorija", city: "Grad",
    minPrice: "Cijena MIN", maxPrice: "Cijena MAX", apply: "Primijeni",
    clear: "Očisti", noResults: "Nisu pronađeni oglasi",
    noResultsSub: "Pokušajte promijeniti filtere ili dodajte novi oglas",
    post: "Dodaj oglas", postFree: "Objavi besplatno", all: "Sve", today: "Danas",
    views: "pregleda", total: "oglasa ukupno", in: "u",
    page: "Stranica", of: "od",
    hero: "KetuJemi — Kupuj & Prodaj",
    heroSub: "Kupuj & prodaj u Crnoj Gori — besplatni oglasi",
    categories: "Kategorije", viewAll: "Vidi sve",
    trust1: "SMS i email verifikacija", trust2: "Besplatno oglašavanje", trust3: "18 kategorija",
    markets: "KetuJemi na 11 tržišta",
    back: "Nazad", edit: "Uredi", delete: "Obriši", cancel: "Otkaži",
    saveChanges: "Sačuvaj promjene", saving: "Čuvanje...",
    promoted: "Promovisan", agreement: "Po dogovoru",
    description: "Opis", details: "Detalji", noPhoto: "Nema foto",
    seller: "Prodavac", privateSeller: "Privatni prodavac",
    callSeller: "Telefoniraj", whatsapp: "Pošalji poruku (WhatsApp)",
    caution: "⚠ Pažnja",
    cautionTip1: "Sretni prodavca lično",
    cautionTip2: "Provjeri proizvod prije plaćanja",
    cautionTip3: "Ne šalji novac unaprijed",
    cautionTip4: "Prijavi ako primijetiš nešto sumnjivo",
    deleteTitle: "Obriši oglas?",
    deleteDesc: "Ova akcija se ne može poništiti. Oglas će biti trajno obrisan.",
    deleteSuccess: "Oglas je uspješno obrisan",
    deleteError: "Greška pri brisanju",
    listingNotFound: "Oglas nije pronađen",
    listingNotFoundSub: "Možda je obrisan ili imate pogrešan link.",
    backToListings: "Nazad na oglase",
    conditionNew: "Nov", conditionGood: "Veoma dobro",
    conditionUsed: "Korišten", conditionDamaged: "Oštećen",
    bodyType: "Tip karoserije",
    chooseBrand: "Izaberite marku",
    noListingsYet: "Nema oglasa još",
    beFirst: "Budi prvi koji objavljuje u ovoj kategoriji!",
    allListings: "Svi oglasi",
    listings: "Oglasi",
    brandsAvail: "marki dostupnih",
    totalLabel: "ukupno",
    postTitle: "Dodaj oglas",
    mainCategory: "Glavna kategorija",
    chooseCategory: "Izaberite kategoriju...",
    subcategory: "Potkategorija",
    bodyTypeLabel: "Tip karoserije",
    chooseType: "Izaberite tip...",
    chooseMark: "Izaberite marku...",
    choose: "Izaberite...",
    chooseYear: "Izaberite godinu...",
    chooseCity: "Izaberite grad...",
    titleField: "Naslov",
    listingTitle: "Naslov oglasa",
    descField: "Opis",
    descPlaceholder: "Opišite detaljno proizvod ili uslugu...",
    priceField: "Cijena",
    priceEur: "Cijena (EUR)",
    agreementToggle: "Po dogovoru (cijena je pregovaračka)",
    conditionField: "Stanje",
    locationSection: "Lokacija",
    contactSection: "Kontakt",
    yourName: "Vaše ime",
    phoneNum: "Br. telefona",
    mainPhotoLabel: "Glavna",
    photosSection: "Fotografije",
    listingPhotos: "Fotografije oglasa",
    addPhoto: "Dodaj foto",
    clickToSelect: "Klikni za odabir fotografije s uređaja",
    uploading: "Učitavanje...",
    waitPlease: "Molimo sačekajte",
    firstPhotoMain: "Prva fotografija će biti glavna na oglasu",
    carDetails: "Detalji vozila",
    houseDetails: "Detalji nekretnine",
    phoneDetails: "Detalji telefona",
    yearField: "Godina proizvodnje",
    mileageField: "Kilometraža",
    fuelField: "Gorivo",
    transmissionField: "Mjenjač",
    colorField: "Boja",
    engineField: "Motor (L)",
    powerField: "Snaga (hp)",
    techCondField: "Tehnička ispravnost",
    areaField: "Površina (m²)",
    floorField: "Kat",
    roomsField: "Broj soba",
    furnishedField: "Namještenost",
    brandField: "Marka",
    modelField: "Model",
    capacityField: "Kapacitet",
    yes: "Da", no: "Ne",
    posting: "Objavljuje se...",
    submitListing: "Dodaj oglas →",
    successPost: "✓ Oglas je uspješno objavljen!",
    postError: "Greška pri objavljivanju",
    tooManyPhotos: "Možete dodati još",
    photosSuffix: "fotografija",
    addAtLeastPhoto: "Dodaj najmanje 1 fotografiju",
    uploadFailed: "Učitavanje nije uspjelo. Pokušajte ponovo.",
    editListingTitle: "Uredi oglas",
    backToListing: "Nazad na oglas",
    imageUrlField: "URL fotografije (opcionalno)",
    promoteLabel: "Promoviši oglas",
    promoteDesc: "Oglas će biti prikazan u promovanom dijelu",
    updateSuccess: "Oglas je uspješno ažuriran!",
    updateError: "Greška pri ažuriranju",
    conditionNewSub: "Nekorišten",
    conditionUsedSub: "Bio u upotrebi",
    conditionDamagedSub: "Sa defektom / u nesreći",
    marketsTagline: "Kosovo · Albanija · Makedonija · Crna Gora",
    marketsBannerLine:
      "Kosovo - Albanija - Makedonija - Crna Gora - Njemačka - Švicarska - Austrija - Francuska - Italija - Engleska - SAD",
    terms: "Uslovi",
    businessRules: "Biznisi",
    privacy: "Privatnost",
    contact: "Kontakt",
    faq: "FAQ",
    aboutUs: "O nama",
    security: "Sigurnost",
    footer_colHelp: "POMOĆ",
    footer_colInfo: "INFORMACIJE",
    footer_colBusiness: "BIZNIS",
    footer_colMarkets: "TRŽIŠTA",
    footer_diaspora: "Dijaspora",
    footer_contactUs: "Kontaktirajte nas",
    footer_onlineSecurity: "Online sigurnost",
    footer_press: "Mediji",
    footer_aboutKetuJemi: "O KetuJemi",
    footer_rules: "Pravila",
    footer_cookies: "Kolačići",
    footer_openShop: "Otvori prodavnicu",
    footer_vipPackages: "VIP paketi",
    footer_advertise: "Reklamirajte",
    footer_partnership: "Partnerstvo",
    footer_operatedBy: "Upravlja REVOLUTION INVEST SH.P.K.",
    featured: "Preporučeni", recent: "Najnoviji oglasi",
    listingsCount: "oglasa", citiesLabel: "glavni gradovi",
    authLogin: "Prijavi se",
    authLogout: "Odjavi se",
    contactRequiresLogin: "Prijavi se da kontaktiraš prodavca",
    listingAccessDenied: "Nemate pristup za uređivanje ovog oglasa",
    loginToViewPhone: "Prijavi se da vidiš broj",
    sendSms: "Pošalji SMS",
    postQuotaExceeded: "Dostigli ste limit besplatnih oglasa za ovu kategoriju.",
    postQuotaRemaining: "Preostalo besplatnih oglasa u ovoj kategoriji: {n}",
  },
};

// ─── Form option arrays per market ────────────────────────────────────────────
export const FORM_OPTIONS: Record<string, Record<string, string[]>> = {
  fuel: {
    ks:  ["Benzinë", "Naftë", "Elektrik", "Hibrid", "Gaz (LPG)", "Tjetër"],
    al:  ["Benzinë", "Naftë", "Elektrik", "Hibrid", "Gaz (LPG)", "Tjetër"],
    mk:  ["Бензин", "Дизел", "Електричен", "Хибрид", "Гас (ТНГ)", "Друго"],
    mne: ["Benzin", "Dizel", "Električni", "Hibrid", "Gas (LPG)", "Ostalo"],
  },
  transmission: {
    ks:  ["Manuale", "Automatike", "Gjysëm-automatike"],
    al:  ["Manuale", "Automatike", "Gjysëm-automatike"],
    mk:  ["Рачен", "Автоматски", "Полу-автоматски"],
    mne: ["Manuelni", "Automatski", "Poluautomatski"],
  },
  bodyType: {
    ks:  ["Sedan", "Hatchback", "SUV / Jeep", "Kombi", "Kabriolet", "Kupe", "Pikap", "Furgon"],
    al:  ["Sedan", "Hatchback", "SUV / Jeep", "Kombi", "Kabriolet", "Kupe", "Pikap", "Furgon"],
    mk:  ["Седан", "Хечбек", "Теренец / Џип", "Комби", "Кабриолет", "Купе", "Пикап", "Фургон"],
    mne: ["Sedan", "Hatchback", "Terenac / Džip", "Kombi", "Kabriolet", "Kupe", "Pikap", "Kombi/Van"],
  },
  color: {
    ks:  ["E zezë", "E bardhë", "Gri / Argjend", "E kaltër", "E kuqe", "E gjelbër", "E verdhë / Gold", "Kafe / Beige", "Portokalli", "Vjollcë", "Tjetër"],
    al:  ["E zezë", "E bardhë", "Gri / Argjend", "E kaltër", "E kuqe", "E gjelbër", "E verdhë / Gold", "Kafe / Beige", "Portokalli", "Vjollcë", "Tjetër"],
    mk:  ["Црна", "Бела", "Сива / Сребрена", "Сина", "Црвена", "Зелена", "Жолта / Злато", "Кафеава / Беж", "Портокалова", "Виолетова", "Друго"],
    mne: ["Crna", "Bijela", "Siva / Srebrna", "Plava", "Crvena", "Zelena", "Žuta / Zlatna", "Smeđa / Bež", "Narandžasta", "Ljubičasta", "Ostalo"],
  },
  techCondition: {
    ks:  ["E shkëlqyer", "Shumë e mirë", "E mirë", "E pranueshme", "Për riparim"],
    al:  ["E shkëlqyer", "Shumë e mirë", "E mirë", "E pranueshme", "Për riparim"],
    mk:  ["Одлична", "Многу добра", "Добра", "Прифатлива", "За поправка"],
    mne: ["Odlično", "Veoma dobra", "Dobra", "Prihvatljivo", "Za popravku"],
  },
  furnished: {
    ks:  ["I mobiluar", "Pjesërisht i mobiluar", "Pa mobilje"],
    al:  ["I mobiluar", "Pjesërisht i mobiluar", "Pa mobilje"],
    mk:  ["Наместено", "Делумно наместено", "Без мебел"],
    mne: ["Namješteno", "Djelimično namješteno", "Bez namještaja"],
  },
};

// ─── Locations per market ─────────────────────────────────────────────────────
export const LOCATIONS: Record<string, string[]> = {
  ks: [
    "Prishtinë","Prizren","Pejë","Mitrovicë","Gjilan","Ferizaj","Gjakovë","Vushtrri","Podujevë",
    "Suharekë","Rahovec","Malishevë","Skenderaj","Klinë","Drenas","Lipjan","Shtime","Kaçanik",
    "Hani i Elezit","Shtërpcë",
  ],
  al: [
    "Tiranë","Durrës","Vlorë","Shkodër","Elbasan","Fier","Korçë","Berat","Lushnjë","Kavajë",
    "Gjirokastër","Sarandë","Pogradec","Laç","Lezhë","Kukës","Peshkopi",
  ],
  mk: [
    "Скопје",
    "Тетово",
    "Гостивар",
    "Охрид",
    "Битола",
    "Куманово",
    "Струмица",
    "Прилеп",
    "Кавадарци",
    "Неготино",
    "Струга",
    "Кичево",
    "Дебар",
    "Кочани",
  ],
  mne: [
    "Podgorica",
    "Ulcinj",
    "Tivat",
    "Budva",
    "Kotor",
    "Herceg Novi",
    "Nikšić",
    "Berane",
    "Plav",
    "Gusinje",
    "Rožaje",
  ],
};

export const ALL_LOCATIONS: string[] = [
  ...LOCATIONS.ks,
  ...LOCATIONS.al,
  ...LOCATIONS.mk,
  ...LOCATIONS.mne,
];

// ─── Context ──────────────────────────────────────────────────────────────────
interface MarketContextType {
  market: Market;
  setMarket: (m: Market) => void;
  uiLang: UiLang;
  setUiLang: (lang: UiLang) => void;
  rates: Record<string, number>;
  t: Record<string, string>;
}

const MarketContext = createContext<MarketContextType>({
  market: MARKETS[0],
  setMarket: () => {},
  uiLang: DEFAULT_UI_LANG,
  setUiLang: () => {},
  rates: { EUR: 1, ALL: 109.5, MKD: 61.5 },
  t: TRANSLATIONS.ks,
});

export function MarketProvider({ children }: { children: ReactNode }) {
  const [market, setMarketState] = useState<Market>(MARKETS[0]);
  const [uiLang, setUiLangState] = useState<UiLang>(DEFAULT_UI_LANG);
  const [rates, setRates] = useState<Record<string, number>>({ EUR: 1, ALL: 109.5, MKD: 61.5 });
  const [extraTranslations, setExtraTranslations] = useState<
    Record<string, Record<string, string>> | null
  >(null);

  useEffect(() => {
    void import("./app-extra-i18n").then((m) => setExtraTranslations(m.EXTRA_TRANSLATIONS));
  }, []);

  useEffect(() => {
    fetchLiveRates().then(setRates);
  }, []);

  useEffect(() => {
    try {
      const saved = localStorage.getItem("vendi_market");
      if (saved) {
        const found = MARKETS.find((m) => m.code === saved);
        if (found) setMarketState(found);
      }
    } catch {}
  }, []);

  useEffect(() => {
    try {
      const saved = localStorage.getItem("vendi_ui_lang");
      if (saved && isUiLang(saved)) setUiLangState(saved);
    } catch {}
  }, []);

  const setMarket = (m: Market) => {
    setMarketState(m);
    try { localStorage.setItem("vendi_market", m.code); } catch {}
  };

  const setUiLang = (lang: UiLang) => {
    setUiLangState(lang);
    try { localStorage.setItem("vendi_ui_lang", lang); } catch {}
  };

  const translationCode = translationKeyForUiLang(uiLang);
  const tMerged = useMemo(
    () => ({
      ...TRANSLATIONS[translationCode],
      ...(extraTranslations?.[translationCode] ?? {}),
    }),
    [translationCode, extraTranslations],
  );

  return (
    <MarketContext.Provider value={{ market, setMarket, uiLang, setUiLang, rates, t: tMerged }}>
      {children}
    </MarketContext.Provider>
  );
}

export function useMarket() {
  return useContext(MarketContext);
}
