/** French UI strings — merged into TRANSLATIONS.fr in market-context.tsx */
export const FR_TRANSLATIONS: Record<string, string> = {
  title: "Annonces",
  search: "Rechercher des annonces...",
  searchBtn: "Rechercher",
  searchTagline: "Cherchez et trouvez vite — ce que vous cherchez, trouvé en secondes !",
  searchShopsSection: "Boutiques",
  filters: "Filtres",
  category: "Catégorie",
  city: "Ville",
  minPrice: "Prix min.",
  maxPrice: "Prix max.",
  apply: "Appliquer",
  clear: "Effacer",
  noResults: "Aucune annonce trouvée",
  noResultsSub: "Modifiez les filtres ou publiez une nouvelle annonce",
  post: "Publier une annonce",
  postFree: "Publier gratuitement",
  shopSuggestBanner:
    "💡 Vous avez une boutique ? Ouvrez votre boutique digitale gratuite et regroupez toutes vos annonces au même endroit !",
  shopSuggestBannerBtn: "Ouvrir une boutique →",
  all: "Tout",
  today: "Aujourd'hui",
  views: "vues",
  total: "annonces au total",
  in: "dans",
  page: "Page",
  of: "sur",
  hero: "KetuJemi",
  heroSub: "Achetez & Vendez tout — gratuit et rapide !",
  categories: "Catégories",
  viewAll: "Tout voir",
  trust1: "Vérification SMS et e-mail",
  trust2: "Publication gratuite",
  trust3: "21 catégories",
  markets: "KetuJemi dans 11 marchés",
  back: "Retour",
  edit: "Modifier",
  delete: "Supprimer",
  cancel: "Annuler",
  saveChanges: "Enregistrer",
  saving: "Enregistrement...",
  promoted: "En vedette",
  agreement: "Négociable",
  description: "Description",
  details: "Détails",
  noPhoto: "Pas de photo",
  seller: "Vendeur",
  privateSeller: "Vendeur particulier",
  callSeller: "Appeler",
  whatsapp: "Message WhatsApp",
  share_sectionTitle: "Partager cette annonce",
  share_motivation:
    "💡 Partagez votre annonce — chaque clic attire de nouveaux clients vers votre boutique gratuitement !",
  share_facebook: "Facebook",
  share_whatsapp: "WhatsApp",
  share_instagram: "Instagram",
  share_tiktok: "TikTok",
  share_instagramCopyTooltip: "Coller dans la story Instagram",
  share_tiktokCopyTooltip: "Copier le lien pour TikTok",
  share_socialPostedTitle: "Annonce publiée sur les réseaux sociaux",
  share_socialPostedHint:
    "Partagez à nouveau avec vos amis — chaque partage augmente les vues de votre annonce.",
  share_socialPostedIgDialogTitle: "Partager sur Instagram",
  share_socialPostedIgDialogBody:
    "Copiez le lien de l'annonce et collez-le dans votre story, reel ou publication Instagram.",
  share_socialPostedIgCopied:
    "✓ Lien copié ! Ouvrez Instagram et partagez-le dans votre story ou publication.",
  share_socialPostedOpenInstagram: "Ouvrir Instagram",
  share_copyLink: "🔗 Copier le lien",
  share_copied: "✓ Lien copié ! Publiez-le sur Instagram ou TikTok pour plus de clients 🚀",
  share_socialApps: "📲 Instagram / TikTok",
  share_toastSocial:
    "✓ Lien copié ! Ouvrez Instagram ou TikTok et publiez-le dans votre story ou fil 📲",
  share_compactLabel: "Partager",
  caution: "⚠ Attention",
  cautionTip1: "Rencontrez le vendeur en personne",
  cautionTip2: "Inspectez l'article avant de payer",
  cautionTip3: "N'envoyez pas d'argent à l'avance",
  cautionTip4: "Signalez tout comportement suspect",
  deleteTitle: "Supprimer l'annonce ?",
  deleteDesc: "Cette action est irréversible. L'annonce sera définitivement supprimée.",
  deleteSuccess: "Annonce supprimée avec succès",
  deleteError: "Erreur lors de la suppression",
  listingNotFound: "Annonce introuvable",
  listingNotFoundSub: "Elle a peut-être été supprimée ou le lien est incorrect.",
  backToListings: "Retour aux annonces",
  conditionNew: "Neuf",
  conditionGood: "Très bon état",
  conditionUsed: "Occasion",
  conditionDamaged: "Endommagé",
  bodyType: "Type de carrosserie",
  chooseBrand: "Choisir la marque",
  noListingsYet: "Aucune annonce pour le moment",
  beFirst: "Soyez le premier à publier dans cette catégorie !",
  kerkojEmptyTitle: "Aucune demande pour le moment",
  kerkojEmptySub:
    "Vous cherchez quelque chose introuvable ailleurs ? Décrivez ce dont vous avez besoin et publiez votre demande ici — les personnes qui ont l'article vous verront et pourront vous contacter rapidement.",
  kerkojEmptyTrust: "Votre annonce s'affiche ici comme toute autre annonce.",
  kerkojEmptyPost: "Publier une demande",
  kerkojHubIntroTitle: "Je cherche à acheter — publiez votre demande",
  kerkojFormBanner:
    "Ceci est une demande d'achat — décrivez ce que vous cherchez. Votre demande est publiée sur la plateforme et parvient aux personnes et boutiques qui traitent cet article, pour trouver plus vite ce dont vous avez besoin.",
  kerkojFormPhotoHint:
    "📸 Ajoutez des photos montrant ce que vous cherchez (modèle, couleur, état…) — les vendeurs vous comprennent mieux et vous contactent plus vite.",
  kerkojFormTitlePh: "ex. Je cherche BMW X5 diesel 2018+, iPhone 14 Pro 256GB, poussette bébé...",
  kerkojFormDescPh:
    "Décrivez en détail : ce que vous cherchez, le modèle, les spécifications, l'état souhaité, le budget (facultatif), d'où vous pouvez le récupérer. Plus la demande est claire, plus vite quelqu'un qui a l'article vous contactera.",
  kerkojFormDescNote:
    "Votre demande parvient directement aux personnes et boutiques qui traitent ce type d'article — pas seulement à la liste publique.",
  kerkojFormPostTitle: "Publier une demande",
  kerkojFormTitleLbl: "Titre de la demande",
  kerkojFormPhotosLbl: "Photos de la demande",
  kerkojFormClickPhoto: "Cliquez pour ajouter des photos — montrez ce que vous cherchez",
  kerkojFormDescSection: "Description de la demande",
  postFromAnywhere: "Vous pouvez publier depuis n'importe où.",
  allListings: "Toutes les annonces",
  listings: "Annonces",
  brandsAvail: "marques disponibles",
  subcategoriesAvail: "sous-catégories disponibles",
  totalLabel: "total",
  postTitle: "Publier une annonce",
  mainCategory: "Catégorie principale",
  chooseCategory: "Choisir une catégorie...",
  subcategory: "Sous-catégorie",
  fj_guide_includes: "Ce que comprend cette catégorie",
  fj_guide_conditions: "Comment décrire l'état dans votre annonce",
  fj_guide_col_state: "État",
  fj_guide_col_meaning: "Que écrire",
  bodyTypeLabel: "Type de carrosserie",
  chooseType: "Choisir le type...",
  chooseMark: "Choisir la marque...",
  chooseSubcategory: "Choisir la sous-catégorie...",
  subcategoryTitleMinHint:
    "Saisissez un titre (min. 5 caractères) — puis choisissez ou la sous-catégorie sera définie automatiquement.",
  subcategoryAutoSetting: "Définition de la sous-catégorie…",
  titlePlaceholderExample: "ex. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
  postErrTitleForSubcategory:
    "Saisissez un titre (au moins 5 caractères) pour que le système définisse la sous-catégorie.",
  postErrChooseSubcategory:
    "Choisissez une sous-catégorie dans la liste, ou attendez un instant après avoir saisi le titre.",
  postErrChooseBrand: "Choisissez la marque / le modèle du produit.",
  photoAnalyzeFailed: "Remplissage automatique impossible",
  photoAnalyzeFailedHint:
    "Continuez manuellement avec catégorie, titre et description — ou essayez une photo plus nette.",
  photoAnalyzeLoginRequired: "Vous devez être connecté",
  photoAnalyzeLoginRequiredHint: "Connectez-vous et réessayez d'envoyer la photo.",
  photoAnalyzeUnavailable: "L'analyse photo est temporairement indisponible",
  photoAnalyzeUnavailableHint: "Remplissez manuellement la catégorie, le titre et la description.",
  choose: "Choisir...",
  chooseYear: "Choisir l'année...",
  chooseCity: "Choisir la ville...",
  zodParentCategory: "Choisissez une catégorie principale.",
  zodTitleMin: "Le titre doit contenir au moins 5 caractères.",
  zodDescriptionMin: "La description doit contenir au moins 15 caractères.",
  zodLocation: "Choisissez une ville.",
  zodPhoneMin: "Le téléphone doit contenir au moins 5 chiffres.",
  zodSellerName: "Saisissez le nom du vendeur.",
  formInvalidSummary:
    "Remplissez tous les champs obligatoires (catégorie, titre min. 5, description min. 15, photo, prix, ville).",
  videoInvalidFormatTitle: "Format non valide",
  videoInvalidFormatDesc: "Seuls MP4, MOV et AVI sont acceptés.",
  videoPreparingTitle: "Préparation de la vidéo...",
  videoPreparingHint:
    "La vidéo est optimisée pour votre annonce (max. 100 Mo). Ne fermez pas cette page.",
  videoAnalyzeFrameHint:
    "Impossible de lire une image de la vidéo. Essayez un clip plus court avec une bonne lumière, ou ajoutez une photo.",
  similarListingsHeading: "Vous aimerez peut-être aussi",
  titleField: "Titre",
  listingTitle: "Titre de l'annonce",
  descField: "Description",
  descPlaceholder: "Décrivez votre produit ou service en détail...",
  priceField: "Prix",
  priceEur: "Prix (EUR)",
  agreementToggle: "Négociable (prix ouvert aux offres)",
  conditionField: "État",
  locationSection: "Localisation",
  contactSection: "Contact",
  yourName: "Votre nom",
  phoneNum: "Numéro de téléphone",
  mainPhotoLabel: "Principale",
  photosSection: "Photos",
  listingPhotos: "Photos de l'annonce",
  listingPhotosMinHint: "(min. 1)",
  addPhoto: "Ajouter une photo",
  photoCameraBtn: "Prendre une photo avec l'appareil",
  videoCameraBtn: "Enregistrer une vidéo avec l'appareil",
  clickToSelect: "Appuyez pour choisir des photos sur votre appareil",
  uploading: "Envoi en cours...",
  waitPlease: "Veuillez patienter",
  analyzingPhoto: "Analyse de la photo par notre système...",
  analyzingPhotoHint: "Catégorie, titre et description sont remplis automatiquement.",
  firstPhotoAiHint:
    "📸 Envoyez votre première photo et notre système remplira automatiquement la catégorie, le titre et la description — gain de temps et publication plus simple !",
  firstPhotoAiHintShop:
    "📸 Envoyez une photo produit — notre système remplira automatiquement la catégorie, le titre et la description pour votre boutique. Vendez plus vite !",
  systemHelpBtn: "Aide de notre système",
  descriptionHelperAccept: "Accepter",
  descriptionHelperIgnore: "Ignorer",
  postingSuggestionsTitle: "Suggestions de notre système",
  postingSuggestionsLoading: "Analyse de votre annonce…",
  firstPhotoMain: "La première photo sera l'image principale de l'annonce",
  carDetails: "Détails du véhicule",
  houseDetails: "Détails du bien",
  phoneDetails: "Détails du téléphone",
  yearField: "Année",
  mileageField: "Kilométrage",
  fuelField: "Carburant",
  transmissionField: "Boîte de vitesses",
  colorField: "Couleur",
  engineField: "Moteur (L)",
  powerField: "Puissance (ch)",
  techCondField: "État technique",
  areaField: "Surface (m²)",
  floorField: "Étage",
  roomsField: "Pièces",
  furnishedField: "Ameublement",
  brandField: "Marque",
  modelField: "Modèle",
  capacityField: "Capacité",
  yes: "Oui",
  no: "Non",
  posting: "Publication...",
  submitListing: "Publier l'annonce →",
  successPost: "✓ Annonce publiée avec succès !",
  postError: "Erreur lors de la publication",
  postRefusedTitle: "Non publiée",
  tooManyPhotos: "Vous pouvez ajouter",
  photosSuffix: "photos de plus",
  addAtLeastPhoto: "Ajoutez au moins 1 photo",
  uploadFailed: "Échec de l'envoi. Réessayez.",
  editListingTitle: "Modifier l'annonce",
  editAnalyzePhotoBtn: "Analyser la photo avec l'IA",
  editUploadPhotoBtn: "Envoyer une photo",
  editPhotoAnalyzeOk: "Titre et description mis à jour à partir de la photo.",
  backToListing: "Retour à l'annonce",
  imageUrlField: "URL de la photo (facultatif)",
  promoteLabel: "Mettre en avant",
  promoteDesc: "L'annonce apparaîtra dans la section mise en avant",
  updateSuccess: "Annonce mise à jour avec succès !",
  updateError: "Erreur lors de la mise à jour",
  conditionNewSub: "Jamais utilisé",
  conditionUsedSub: "Déjà utilisé",
  conditionDamagedSub: "Défectueux / accident",
  marketsTagline: "Kosovo · Albanie · Macédoine du Nord · Monténégro",
  marketsBannerLine:
    "Kosovo - Albanie - Macédoine du Nord - Monténégro - Allemagne - Suisse - Autriche - France - Italie - Royaume-Uni - États-Unis",
  terms: "Conditions",
  businessRules: "Entreprises",
  privacy: "Confidentialité",
  contact: "Contact",
  faq: "FAQ",
  aboutUs: "À propos",
  security: "Sécurité",
  footer_colHelp: "AIDE",
  footer_colInfo: "INFO",
  footer_colBusiness: "ENTREPRISE",
  footer_colMarkets: "MARCHÉS",
  footer_diaspora: "Diaspora",
  footer_contactUs: "Nous contacter",
  footer_onlineSecurity: "Sécurité en ligne",
  footer_press: "Presse",
  footer_aboutKetuJemi: "À propos de KetuJemi",
  footer_rules: "Règles",
  footer_cookies: "Cookies",
  footer_openShop: "Ouvrir une boutique",
  footer_vipPackages: "Forfaits VIP",
  footer_advertise: "Publicité",
  footer_partnership: "Partenariat",
  footer_operatedBy: "Exploité par REVOLUTION INVEST SH.P.K.",
  featured: "En vedette",
  recent: "Annonces récentes",
  listingsCount: "annonces",
  citiesLabel: "villes principales",
  authLogin: "Connexion",
  authLogout: "Déconnexion",
  contactRequiresLogin: "Connectez-vous pour contacter le vendeur",
  listingAccessDenied: "Vous n'avez pas la permission de modifier cette annonce",
  loginToViewPhone: "Connectez-vous pour voir le numéro de téléphone",
  sendSms: "Envoyer un SMS",
  postQuotaExceeded: "Vous avez atteint la limite de publications gratuites pour cette catégorie.",
  postQuotaRemaining: "Publications gratuites restantes dans cette catégorie : {n}",
};
