/** Italian UI strings — merged into TRANSLATIONS.it in market-context.tsx */
export const IT_TRANSLATIONS: Record<string, string> = {
  title: "Annunci",
  search: "Cerca annunci...",
  searchBtn: "Cerca",
  searchShopsSection: "Negozi",
  filters: "Filtri",
  category: "Categoria",
  city: "Città",
  minPrice: "Prezzo min.",
  maxPrice: "Prezzo max.",
  apply: "Applica",
  clear: "Cancella",
  noResults: "Nessun annuncio trovato",
  noResultsSub: "Modifica i filtri o pubblica un nuovo annuncio",
  post: "Pubblica annuncio",
  postFree: "Pubblica gratis",
  shopSuggestBanner: "💡 Have a shop? Open your free digital shop and showcase all your listings in one place!",
  shopSuggestBannerBtn: "Open shop →",
  all: "Tutto",
  today: "Today",
  views: "views",
  total: "listings total",
  in: "in",
  page: "Page",
  of: "of",
  hero: "KetuJemi — Compra e vendi",
  heroSub: "Buy & sell across the Balkans — piattaforma di annunci gratuita",
  categories: "Categorie",
  viewAll: "Vedi tutto",
  trust1: "SMS & email verification",
  trust2: "Pubblica gratis",
  trust3: "21 categories",
  markets: "KetuJemi in 11 mercati",
  back: "Indietro",
  edit: "Modifica",
  delete: "Elimina",
  cancel: "Annulla",
  saveChanges: "Salva",
  saving: "Salvataggio...",
  promoted: "Promoted",
  agreement: "Trattabile",
  description: "Descrizione",
  details: "Dettagli",
  noPhoto: "No photo",
  seller: "Venditore",
  privateSeller: "Venditore privato",
  callSeller: "Chiama",
  whatsapp: "Message on WhatsApp",
  share_sectionTitle: "Condividi this listing",
  share_motivation: "💡 Condividi your listing — every click brings new customers to your shop for free!",
  share_facebook: "Facebook",
  share_whatsapp: "WhatsApp",
  share_instagram: "Instagram",
  share_tiktok: "TikTok",
  share_instagramCopyTooltip: "Paste to Instagram Story",
  share_tiktokCopyTooltip: "Copy link for TikTok",
  share_socialPostedTitle: "Listing published on social media",
  share_socialPostedHint: "Condividi again with friends — every share brings more views to your listing.",
  share_socialPostedIgDialogTitle: "Condividi on Instagram",
  share_socialPostedIgDialogBody: "Copy the listing link and paste it to your story, reels, or feed on Instagram.",
  share_socialPostedIgCopied: "✓ Link copied! Open Instagram and share it to your story or post.",
  share_socialPostedOpenInstagram: "Open Instagram",
  share_copyLink: "🔗 Copy link",
  share_copied: "✓ Link copied! Post it on Instagram or TikTok for more customers 🚀",
  share_socialApps: "📲 Instagram / TikTok",
  share_toastSocial: "✓ Link copied! Open Instagram or TikTok and post it to your story or feed 📲",
  share_compactLabel: "Condividi",
  caution: "⚠ Caution",
  cautionTip1: "Meet the seller in person",
  cautionTip2: "Inspect the item before paying",
  cautionTip3: "Do not send money in advance",
  cautionTip4: "Report anything suspicious",
  deleteTitle: "Eliminare l'annuncio?",
  deleteDesc: "Questa azione è irreversibile. L'annuncio verrà rimosso definitivamente.",
  deleteSuccess: "Listing deleted successfully",
  deleteError: "Error while deleting",
  listingNotFound: "Listing not found",
  listingNotFoundSub: "It may have been removed or the link is incorrect.",
  backToListings: "Indietro to listings",
  conditionNew: "New",
  conditionGood: "Very good",
  conditionUsed: "Used",
  conditionDamaged: "Damaged",
  bodyType: "Body type",
  chooseBrand: "Scegli marca",
  noListingsYet: "No listings yet",
  beFirst: "Sii il primo a pubblicare in questa categoria!",
  kerkojEmptyTitle: "No requests yet",
  kerkojEmptySub: `Looking for something you cannot find? Post your request here — people who have the item will see it and can contact you quickly.`,
  kerkojEmptyTrust: "Your listing appears here like any other listing.",
  kerkojEmptyPost: "Post request",
  kerkojHubIntroTitle: "Looking to buy — post your request",
  kerkojFormBanner: `This is a buying request — describe what you are looking for. Your request is published on the platform and reaches people and shops who deal with that item, so you can find what you need faster.`,
  kerkojFormPhotoHint: `📸 Add photos that show what you are looking for (model, colour, condition…) — sellers understand you more easily and contact you faster.`,
  kerkojFormTitlePh: "e.g. Looking for BMW X5 diesel 2018+, iPhone 14 Pro 256GB, baby stroller...",
  kerkojFormDescPh: `Describe in detail: what you need, model, specs, preferred condition, budget (optional), where you can pick it up. The clearer the request, the faster someone who has the item will contact you.`,
  kerkojFormDescNote: `Your request goes directly to people and shops who deal with this type of item — not only the public listing.`,
  kerkojFormPostTitle: "Post request",
  kerkojFormTitleLbl: "Request title",
  kerkojFormPhotosLbl: "Request photos",
  kerkojFormClickPhoto: "Tap to add photos — show what you are looking for",
  kerkojFormDescSection: "Request description",
  postFromAnywhere: "You can post from anywhere.",
  allListings: "Tutto listings",
  listings: "Annunci",
  brandsAvail: "marchi disponibili",
  subcategoriesAvail: "sottocategorie disponibili",
  totalLabel: "total",
  postTitle: "Pubblica annuncio",
  mainCategory: "Categoria principale",
  chooseCategory: "Scegli categoria...",
  subcategory: "Subcategory",
  fj_guide_includes: "What this category includes",
  fj_guide_conditions: "How to describe condition in your listing",
  fj_guide_col_state: "Condition",
  fj_guide_col_meaning: "What to write",
  bodyTypeLabel: "Body type",
  chooseType: "Choose type...",
  chooseMark: "Scegli marca...",
  chooseSubcategory: "Choose subcategory...",
  subcategoryTitleMinHint: "Enter a title (min. 5 characters) — then pick or the subcategory will be set automatically.",
  subcategoryAutoSetting: "Setting subcategory…",
  titlePlaceholderExample: "e.g. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
  postErrTitleForSubcategory: "Enter a title (at least 5 characters) so the system can set the subcategory.",
  postErrChooseSubcategory: "Choose a subcategory from the list, or wait a moment after entering the title.",
  postErrChooseBrand: "Choose the product brand / model.",
  photoAnalyzeFailed: "Could not fill in automatically",
  photoAnalyzeFailedHint: "Continue manually with category, title, and description — or try a clearer photo.",
  photoAnalyzeLoginRequired: "You need to be logged in",
  photoAnalyzeLoginRequiredHint: "Sign in and try uploading the photo again.",
  photoAnalyzeUnavailable: "Photo analysis is temporarily unavailable",
  photoAnalyzeUnavailableHint: "Fill in category, title, and description manually.",
  choose: "Choose...",
  chooseYear: "Scegli anno...",
  chooseCity: "Scegli città...",
  zodParentCategory: "Choose a main category.",
  zodTitleMin: "Title must be at least 5 characters.",
  zodDescriptionMin: "Descrizione must be at least 15 characters.",
  zodLocation: "Choose a city.",
  zodPhoneMin: "Phone must have at least 5 digits.",
  zodSellerName: "Enter the seller name.",
  formInvalidSummary: "Fill in all required fields (category, title min. 5, description min. 15, photo, price, city).",
  videoInvalidFormatTitle: "Invalid format",
  videoInvalidFormatDesc: "Only MP4, MOV, and AVI are allowed.",
  videoPreparingTitle: "Preparing video...",
  videoPreparingHint: "Video is being optimized for your listing (max 100 MB). Do not close this page.",
  videoAnalyzeFrameHint: "Could not read a frame from the video. Try a shorter clip with good lighting, or add a photo.",
  similarListingsHeading: "You may also like",
  titleField: "Title",
  listingTitle: "Listing title",
  descField: "Descrizione",
  descPlaceholder: "Describe your product or service in detail...",
  priceField: "Price",
  priceEur: "Price (EUR)",
  agreementToggle: "Trattabile (price is open to offers)",
  conditionField: "Condition",
  locationSection: "Posizione",
  contactSection: "Contatto",
  yourName: "Your name",
  phoneNum: "Numero di telefono",
  mainPhotoLabel: "Main",
  photosSection: "Photos",
  listingPhotos: "Listing photos",
  addPhoto: "Add photo",
  photoCameraBtn: "Take photo with camera",
  videoCameraBtn: "Record video with camera",
  clickToSelect: "Tap to choose photos from your device",
  uploading: "Uploading...",
  waitPlease: "Please wait",
  analyzingPhoto: "Analyzing photo with our system...",
  analyzingPhotoHint: "Categoria, title, and description are filled in automatically.",
  firstPhotoAiHint: `📸 Upload your first photo and our system will automatically fill in the category, title and description for you — saves time and makes listing easier!`,
  firstPhotoAiHintShop: `📸 Upload a product photo — our system will automatically fill in the category, title and description for your shop listing. Saves time and makes selling easier!`,
  systemHelpBtn: "Aiuto dal nostro sistema",
  descriptionHelperAccept: "Accept",
  descriptionHelperIgnore: "Ignore",
  postingSuggestionsTitle: "Suggestions from our system",
  postingSuggestionsLoading: "Analyzing your listing…",
  firstPhotoMain: "The first photo will be the main listing image",
  carDetails: "Vehicle details",
  houseDetails: "Property details",
  phoneDetails: "Phone details",
  yearField: "Year",
  mileageField: "Mileage",
  fuelField: "Fuel",
  transmissionField: "Transmission",
  colorField: "Color",
  engineField: "Engine (L)",
  powerField: "Power (hp)",
  techCondField: "Tecnico condition",
  areaField: "Area (m²)",
  floorField: "Floor",
  roomsField: "Rooms",
  furnishedField: "Furnishing",
  brandField: "Brand",
  modelField: "Model",
  capacityField: "Capacity",
  yes: "Sì",
  no: "No",
  posting: "Pubblicazione...",
  submitListing: "Pubblica annuncio →",
  successPost: "✓ Annuncio pubblicato con successo!",
  postError: "Error while posting",
  postRefusedTitle: "Not posted",
  tooManyPhotos: "You can add",
  photosSuffix: "more photos",
  addAtLeastPhoto: "Add at least 1 photo",
  uploadFailed: "Upload failed. Try again.",
  editListingTitle: "Modifica listing",
  editAnalyzePhotoBtn: "Analyze photo with AI",
  editUploadPhotoBtn: "Upload photo",
  editPhotoAnalyzeOk: "Title and description updated from the photo.",
  backToListing: "Indietro to listing",
  imageUrlField: "Photo URL (optional)",
  promoteLabel: "Promote listing",
  promoteDesc: "Listing will appear in the promoted section",
  updateSuccess: "Listing updated successfully!",
  updateError: "Error while updating",
  conditionNewSub: "Unused",
  conditionUsedSub: "Previously used",
  conditionDamagedSub: "Defective / accident",
  marketsTagline: "Kosovo · Albania · Macedonia del Nord · Montenegro",
  marketsBannerLine: `Kosovo - Albania - Macedonia del Nord - Montenegro - Germania - Svizzera - Austria - Francia - Italia - UK - USA`,
  terms: "Termini",
  businessRules: "Business",
  privacy: "Privacy",
  contact: "Contatto",
  faq: "FAQ",
  aboutUs: "Chi siamo",
  security: "Sicurezza",
  footer_colHelp: "HELP",
  footer_colInfo: "INFO",
  footer_colBusiness: "BUSINESS",
  footer_colMarkets: "MARKETS",
  footer_diaspora: "Diaspora",
  footer_contactUs: "Contattaci",
  footer_onlineSecurity: "Sicurezza online",
  footer_press: "Press",
  footer_aboutKetuJemi: "About KetuJemi",
  footer_rules: "Rules",
  footer_cookies: "Cookies",
  footer_openShop: "Open a shop",
  footer_vipPackages: "VIP packages",
  footer_advertise: "Advertise",
  footer_partnership: "Partnership",
  footer_operatedBy: "Operated by REVOLUTION INVEST SH.P.K.",
  featured: "Featured",
  recent: "Recent listings",
  listingsCount: "listings",
  citiesLabel: "main cities",
  authLogin: "Accedi",
  authLogout: "Log out",
  contactRequiresLogin: "Accedi to contact the seller",
  listingAccessDenied: "You do not have permission to edit this listing",
  loginToViewPhone: "Accedi to see the phone number",
  sendSms: "Send SMS",
  postQuotaExceeded: "You have reached the free posting limit for this category.",
  postQuotaRemaining: "Free posts remaining in this category: {n}",
};
