import { createContext, useContext, useState, useEffect, useMemo, type ReactNode } from "react";
import { fetchWithTimeout } from "@/lib/fetch-with-timeout";
import {
  DEFAULT_UI_LANG,
  isUiLang,
  translationKeyForUiLang,
  type UiLang,
} from "./ui-languages";

export const MARKETS = [
  { code: "ks",  flag: "🇽🇰", name: "Kosovë",             currency: "EUR", symbol: "€",   prefix: "+383" },
  { code: "al",  flag: "🇦🇱", name: "Shqipëri",           currency: "ALL", symbol: "L",   prefix: "+355" },
  { code: "mk",  flag: "🇲🇰", name: "Maqedoni e Veriut",  currency: "MKD", symbol: "ден", prefix: "+389" },
  { code: "mne", flag: "🇲🇪", name: "Mal i Zi",           currency: "EUR", symbol: "€",   prefix: "+382" },
  { code: "de",  flag: "🇩🇪", name: "Gjermani",           currency: "EUR", symbol: "€",   prefix: "+49" },
  { code: "at",  flag: "🇦🇹", name: "Austri",             currency: "EUR", symbol: "€",   prefix: "+43" },
  { code: "ch",  flag: "🇨🇭", name: "Zvicër",             currency: "CHF", symbol: "CHF", prefix: "+41" },
  { code: "it",  flag: "🇮🇹", name: "Itali",              currency: "EUR", symbol: "€",   prefix: "+39" },
  { code: "fr",  flag: "🇫🇷", name: "Francë",             currency: "EUR", symbol: "€",   prefix: "+33" },
  { code: "gb",  flag: "🇬🇧", name: "Angli",              currency: "GBP", symbol: "£",   prefix: "+44" },
  { code: "us",  flag: "🇺🇸", name: "SHBA",               currency: "USD", symbol: "$",   prefix: "+1" },
] as const;

export type Market = (typeof MARKETS)[number];

let _ratesCache: Record<string, number> = { EUR: 1, ALL: 109.5, MKD: 61.5 };
let _ratesFetched = false;

export async function fetchLiveRates(): Promise<Record<string, number>> {
  if (_ratesFetched) return _ratesCache;
  try {
    const res = await fetchWithTimeout("/api/exchange-rates");
    if (res.ok) { _ratesCache = await res.json(); }
  } catch {}
  _ratesFetched = true;
  return _ratesCache;
}

export function convertPrice(eurPrice: number, market: Market, rates: Record<string, number>): string {
  if (market.currency === "EUR") return `${eurPrice.toLocaleString()} ${market.symbol}`;
  const rate = rates[market.currency] ?? 1;
  return `${Math.round(eurPrice * rate).toLocaleString()} ${market.symbol}`;
}

// ─── Translations ─────────────────────────────────────────────────────────────
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  ks: {
    // Listings / filter
    title: "Shpalljet", search: "Kërko shpallje...", searchBtn: "Kërko",
    searchShopsSection: "Dyqanet",
    filters: "Filtrat", category: "Kategoria", city: "Qyteti",
    minPrice: "Çmimi min", maxPrice: "Çmimi max", apply: "Zbato",
    clear: "Pastro", noResults: "Nuk u gjet asnjë shpallje",
    noResultsSub: "Provo të ndryshosh filtrat ose posto shpallje të re",
    post: "Posto Shpallje", postFree: "Posto Falas",
    shopSuggestBanner: "💡 Hai dyqanin tënd? Hap dyqanin dixhital falas dhe shfaq të gjitha shpalljet në një vend!",
    shopSuggestBannerBtn: "Hap Dyqanin →",
    all: "Të gjitha", today: "Sot",
    views: "shikime", total: "shpallje gjithsej", in: "në",
    page: "Faqja", of: "nga",
    // Home
    hero: "KetuJemi — Bli & Shit",
    heroSub: "Bli & shit në Kosovë — platforma e shpalljeve falas",
    categories: "Kategoritë", viewAll: "Shiko të gjitha",
    trust1: "Verifikim SMS & Email", trust2: "Posto falas", trust3: "21 kategori",
    markets: "KetuJemi në 11 tregje",
    // Common actions
    back: "Kthehu", edit: "Edito", delete: "Fshi", cancel: "Anulo",
    saveChanges: "Ruaj ndryshimet", saving: "Duke ruajtur...",
    promoted: "Promovuar", agreement: "Me marrëveshje",
    // Listing detail
    description: "Përshkrimi", details: "Detajet", noPhoto: "Nuk ka foto",
    seller: "Shitësi", privateSeller: "Shitës privat",
    callSeller: "Telefono", whatsapp: "Dërgo Mesazh (WhatsApp)",
    share_sectionTitle: "Shpërndaje këtë shpallje",
    share_motivation: "💡 Shpërndaje shpalljen tënde — çdo klik sjell klientë të rinj te dyqani yt falas!",
    share_facebook: "Facebook",
    share_whatsapp: "WhatsApp",
    share_instagram: "Instagram",
    share_tiktok: "TikTok",
    share_instagramCopyTooltip: "Ngjit në Instagram Story",
    share_tiktokCopyTooltip: "Kopjo linkun për TikTok",
    share_socialPostedTitle: "Shpallja u publikua në rrjetet sociale",
    share_socialPostedHint: "Shpërndaje përsëri te miqtë e tu — çdo ndarje sjell më shumë shikues te shpallja.",
    share_socialPostedIgDialogTitle: "Shpërndaje në Instagram",
    share_socialPostedIgDialogBody: "Kopjo linkun e shpalljes dhe ngjite te historia, reels ose postimi yt në Instagram.",
    share_socialPostedIgCopied: "✓ Linku u kopjua! Hape Instagram dhe shpërndaje te historia ose postimi yt.",
    share_socialPostedOpenInstagram: "Hape Instagram",
    share_copyLink: "Kopjo linkun",
    share_copied: "✓ Linku u kopjua! Ngarkoje në Instagram ose TikTok për më shumë klientë 🚀",
    share_socialApps: "📲 Instagram / TikTok",
    share_toastSocial: "✓ Linku u kopjua! Hape Instagram ose TikTok dhe ngarkoje te historia ose postimi yt 📲",
    share_compactLabel: "Shpërndaje",
    caution: "⚠ Kujdes",
    cautionTip1: "Takohu me shitësin personalisht",
    cautionTip2: "Kontrolloje produktin para pagesës",
    cautionTip3: "Mos dërgo para paraprakisht",
    cautionTip4: "Raporto nëse vëren diçka të dyshimtë",
    deleteTitle: "Fshi shpalljen?",
    deleteDesc: "Kjo veprim nuk mund të zhbehet. Shpallja do të fshihet përgjithmonë.",
    deleteSuccess: "Shpallja u fshi me sukses",
    deleteError: "Gabim gjatë fshirjes",
    listingNotFound: "Shpallja nuk u gjet",
    listingNotFoundSub: "Mund të jetë fshirë ose mund të kesh një link të gabuar.",
    backToListings: "Kthehu te shpalljet",
    conditionNew: "I ri", conditionGood: "Shumë mirë",
    conditionUsed: "I përdorur", conditionDamaged: "I dëmtuar",
    // Category page
    bodyType: "Lloji i karocerisë",
    chooseBrand: "Zgjidh markën",
    noListingsYet: "Nuk ka njoftime ende",
    beFirst: "Bëhu i pari që posto në këtë kategori!",
    postFromAnywhere: "Mund të postoni nga kudo.",
    allListings: "Të gjitha njoftimet",
    listings: "Njoftimet",
    brandsAvail: "marka të disponueshme",
    subcategoriesAvail: "nënkategori të disponueshme",
    totalLabel: "gjithsej",
    // Post / Edit form
    postTitle: "Posto Shpallje",
    mainCategory: "Kategoria kryesore",
    chooseCategory: "Zgjidh kategorinë...",
    subcategory: "Nënkategoria",
    fj_guide_includes: "Çfarë përfshin kjo kategori",
    fj_guide_conditions: "Si ta përshkruani gjendjen në shpallje",
    fj_guide_col_state: "Gjendja",
    fj_guide_col_meaning: "Çfarë të shkruani",
    bodyTypeLabel: "Tipi i karocerisë",
    chooseType: "Zgjidh tipin...",
    chooseMark: "Zgjidh markën...",
    chooseSubcategory: "Zgjidh nënkategorinë...",
    subcategoryTitleMinHint:
      "Shkruani titullin (min. 5 karaktere) — pastaj zgjidhni ose caktohet nënkategoria.",
    subcategoryAutoSetting: "Duke caktuar nënkategorinë…",
    titlePlaceholderExample: "p.sh. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
    postErrTitleForSubcategory:
      "Shkruani titullin (të paktën 5 shkronja) që sistemi të caktojë nënkategorinë.",
    postErrChooseSubcategory:
      "Zgjidhni nënkategorinë nga lista, ose prisni një sekondë pas titullit.",
    postErrChooseBrand: "Zgjidhni markën / modelin e produktit.",
    choose: "Zgjidh...",
    chooseYear: "Zgjidh vitin...",
    chooseCity: "Zgjidh qytetin...",
    zodParentCategory: "Zgjidhni kategorinë kryesore.",
    zodTitleMin: "Titulli duhet të ketë të paktën 5 karaktere.",
    zodDescriptionMin: "Përshkrimi duhet të ketë të paktën 15 karaktere.",
    zodLocation: "Zgjidhni qytetin.",
    zodPhoneMin: "Telefoni duhet të ketë të paktën 5 shifra.",
    zodSellerName: "Shkruani emrin e shitësit.",
    formInvalidSummary:
      "Plotësoni të gjitha fushat e detyrueshme (kategori, titull min. 5, përshkrim min. 15, foto, çmim, qytet).",
    videoInvalidFormatTitle: "Format i pavlefshëm",
    videoInvalidFormatDesc: "Lejohen vetëm MP4, MOV dhe AVI.",
    videoPreparingTitle: "Duke përgatitur videon...",
    videoPreparingHint:
      "Video optimizohet automatikisht për shpallje (max 100 MB). Mos e mbyll faqen.",
    videoAnalyzeFrameHint:
      "Nuk u lexua korniza e videos. Provoni video më të shkurtër me dritë të mirë, ose shtoni një foto.",
    similarListingsHeading: "Mund të të interesojë gjithashtu",
    titleField: "Titulli",
    listingTitle: "Titulli i shpalljes",
    descField: "Përshkrimi",
    descPlaceholder: "Pershkruani në detaje produktin ose shërbimin tuaj...",
    priceField: "Çmimi",
    priceEur: "Çmimi (EUR)",
    agreementToggle: "Me marrëveshje (çmimi është i negociueshëm)",
    conditionField: "Gjendja",
    locationSection: "Vendndodhja",
    contactSection: "Kontakti",
    yourName: "Emri juaj",
    phoneNum: "Nr. telefonit",
    mainPhotoLabel: "Kryesore",
    photosSection: "Fotot",
    listingPhotos: "Fotot e shpalljes",
    addPhoto: "Shto foto",
    photoCameraBtn: "Foto me kamerë",
    videoCameraBtn: "Video me kamerë",
    clickToSelect: "Kliko për të zgjedhur foto nga pajisja jote",
    uploading: "Duke ngarkuar...",
    waitPlease: "Ju lutemi prisni",
    analyzingPhoto: "Duke analizuar foton me sistemin tonë...",
    analyzingPhotoHint: "Kategoria, titulli dhe përshkrimi plotësohen automatikisht.",
    photoAnalyzeFailed: "Nuk u plotësua automatikisht",
    photoAnalyzeFailedHint:
      "Vazhdoni manualisht me kategorinë, titullin dhe përshkrimin — ose provoni një foto më të qartë.",
    photoAnalyzeLoginRequired: "Duhet të jesh i kyçur",
    photoAnalyzeLoginRequiredHint:
      "Hyni në llogari dhe provoni përsëri ngarkimin e fotos.",
    photoAnalyzeUnavailable: "Analiza e fotos nuk është e disponueshme për momentin",
    photoAnalyzeUnavailableHint:
      "Plotësoni manualisht kategorinë, titullin dhe përshkrimin.",
    firstPhotoAiHint:
      "📸 Ngarko foton e parë dhe sistemi jonë do të plotësojë automatikisht kategorinë, titullin dhe përshkrimin për ty — kursen kohë dhe e bën shpalljen më të lehtë!",
    firstPhotoAiHintShop:
      "📸 Ngarko foton e produktit — sistemi jonë do të plotësojë automatikisht kategorinë, titullin dhe përshkrimin për shpalljen e dyqanit tënd. Kursen kohë dhe e bën shitjen më të lehtë!",
    systemHelpBtn: "Ndihmë nga sistemi jonë",
    descriptionHelperAccept: "Prano",
    descriptionHelperIgnore: "Injoro",
    postingSuggestionsTitle: "Sugjerime nga sistemi jonë",
    postingSuggestionsLoading: "Duke analizuar njoftimin…",
    firstPhotoMain: "Foto e parë do të jetë foto kryesore e shpalljes",
    carDetails: "Detajet e automjetit",
    houseDetails: "Detajet e pronës",
    phoneDetails: "Detajet e telefonit",
    yearField: "Viti i prodhimit",
    mileageField: "Kilometrazha",
    fuelField: "Karburanti",
    transmissionField: "Transmisioni",
    colorField: "Ngjyra",
    engineField: "Motori (L)",
    powerField: "Fuqia (hp)",
    techCondField: "Gjendja teknike",
    areaField: "Sipërfaqja (m²)",
    floorField: "Kati",
    roomsField: "Numri dhomave",
    furnishedField: "Mobilimi",
    brandField: "Marka",
    modelField: "Modeli",
    capacityField: "Kapaciteti",
    yes: "Po", no: "Jo",
    posting: "Duke postuar...",
    submitListing: "Posto Shpalljen →",
    successPost: "✓ Shpallja u postua me sukses!",
    postError: "Gabim gjatë postimit",
    postRefusedTitle: "Nuk u postua",
    tooManyPhotos: "Mund të shtosh edhe",
    photosSuffix: "foto",
    addAtLeastPhoto: "Shto të paktën 1 foto",
    uploadFailed: "Ngarkimi dështoi. Provo sërish.",
    editListingTitle: "Edito Shpalljen",
    backToListing: "Kthehu te shpallja",
    imageUrlField: "URL e fotos (opsionale)",
    promoteLabel: "Promovo shpalljen",
    promoteDesc: "Shpallja do të shfaqet në seksionin e promovuar",
    updateSuccess: "Shpallja u perditesua me sukses!",
    updateError: "Gabim gjate perditesimit",
    conditionNewSub: "Papërdorur",
    conditionUsedSub: "Ka qenë në përdorim",
    conditionDamagedSub: "Me defekt / aksident",
    marketsTagline: "Kosovë · Shqipëri · Maqedoni · Mal i Zi",
    marketsBannerLine:
      "Kosovë - Shqipëri - Maqedoni - Mal i Zi - Gjermani - Zvicër - Austri - Francë - Itali - Angli - SHBA",
    terms: "Kushtet",
    businessRules: "Bizneset",
    privacy: "Privatësia",
    contact: "Kontakti",
    faq: "FAQ",
    aboutUs: "Rreth Nesh",
    security: "Siguria",
    footer_colHelp: "NDIHMË",
    footer_colInfo: "INFORMATA",
    footer_colBusiness: "BIZNESE",
    footer_colMarkets: "TREGJET",
    footer_diaspora: "Diaspora",
    footer_contactUs: "Na kontaktoni",
    footer_onlineSecurity: "Siguria online",
    footer_press: "Shtypi",
    footer_aboutKetuJemi: "Rreth KetuJemi",
    footer_rules: "Rregullat",
    footer_cookies: "Cookies",
    footer_openShop: "Hap shitore",
    footer_vipPackages: "Paketa VIP",
    footer_advertise: "Reklamoni",
    footer_partnership: "Partneritet",
    footer_operatedBy: "Operohet nga REVOLUTION INVEST SH.P.K.",
    featured: "Të rekomanduara", recent: "Njoftimet e fundit",
    listingsCount: "shpallje", citiesLabel: "qytetet kryesore",
    authLogin: "Hyr",
    authLogout: "Dil",
    contactRequiresLogin: "Hyr për të kontaktuar shitësin",
    listingAccessDenied: "Nuk keni akses për ta ndryshuar këtë shpallje",
    loginToViewPhone: "Kyçu për të parë numrin",
    sendSms: "Dërgo SMS",
    postQuotaExceeded: "Ke arritur limitin e postimeve falas për këtë kategori.",
    postQuotaRemaining: "Postime falas të mbetura në këtë kategori: {n}",
  },
  al: {
    title: "Njoftimet", search: "Kërko njoftim...", searchBtn: "Kërko",
    searchShopsSection: "Dyqanet",
    filters: "Filtrat", category: "Kategoria", city: "Qyteti",
    minPrice: "Çmimi min", maxPrice: "Çmimi max", apply: "Zbato",
    clear: "Pastro", noResults: "Nuk u gjet asnjë njoftim",
    noResultsSub: "Provo të ndryshosh filtrat ose posto njoftim të ri",
    post: "Posto Njoftim", postFree: "Posto Falas",
    shopSuggestBanner: "💡 Hai dyqanin tënd? Hap dyqanin dixhital falas dhe shfaq të gjitha njoftimet në një vend!",
    shopSuggestBannerBtn: "Hap Dyqanin →",
    all: "Të gjitha", today: "Sot",
    views: "shikime", total: "njoftime gjithsej", in: "në",
    page: "Faqja", of: "nga",
    hero: "KetuJemi — Bli & Shit",
    heroSub: "Bli & shit në Shqipëri — platforma e njoftimeve falas",
    categories: "Kategoritë", viewAll: "Shiko të gjitha",
    trust1: "Verifikim SMS & Email", trust2: "Posto falas", trust3: "21 kategori",
    markets: "KetuJemi në 11 tregje",
    back: "Kthehu", edit: "Edito", delete: "Fshi", cancel: "Anulo",
    saveChanges: "Ruaj ndryshimet", saving: "Duke ruajtur...",
    promoted: "Promovuar", agreement: "Me marrëveshje",
    description: "Përshkrimi", details: "Detajet", noPhoto: "Nuk ka foto",
    seller: "Shitësi", privateSeller: "Shitës privat",
    callSeller: "Telefono", whatsapp: "Dërgo Mesazh (WhatsApp)",
    share_sectionTitle: "Shpërndaje këtë shpallje",
    share_motivation: "💡 Shpërndaje shpalljen tënde — çdo klik sjell klientë të rinj te dyqani yt falas!",
    share_facebook: "Facebook",
    share_whatsapp: "WhatsApp",
    share_instagram: "Instagram",
    share_tiktok: "TikTok",
    share_instagramCopyTooltip: "Ngjit në Instagram Story",
    share_tiktokCopyTooltip: "Kopjo linkun për TikTok",
    share_socialPostedTitle: "Shpallja u publikua në rrjetet sociale",
    share_socialPostedHint: "Shpërndaje përsëri te miqtë e tu — çdo ndarje sjell më shumë shikues te shpallja.",
    share_socialPostedIgDialogTitle: "Shpërndaje në Instagram",
    share_socialPostedIgDialogBody: "Kopjo linkun e shpalljes dhe ngjite te historia, reels ose postimi yt në Instagram.",
    share_socialPostedIgCopied: "✓ Linku u kopjua! Hape Instagram dhe shpërndaje te historia ose postimi yt.",
    share_socialPostedOpenInstagram: "Hape Instagram",
    share_copyLink: "Kopjo linkun",
    share_copied: "✓ Linku u kopjua! Ngarkoje në Instagram ose TikTok për më shumë klientë 🚀",
    share_socialApps: "📲 Instagram / TikTok",
    share_toastSocial: "✓ Linku u kopjua! Hape Instagram ose TikTok dhe ngarkoje te historia ose postimi yt 📲",
    share_compactLabel: "Shpërndaje",
    caution: "⚠ Kujdes",
    cautionTip1: "Takohu me shitësin personalisht",
    cautionTip2: "Kontrolloje produktin para pagesës",
    cautionTip3: "Mos dërgo para paraprakisht",
    cautionTip4: "Raporto nëse vëren diçka të dyshimtë",
    deleteTitle: "Fshi njoftimin?",
    deleteDesc: "Kjo veprim nuk mund të zhbehet. Njoftimi do të fshihet përgjithmonë.",
    deleteSuccess: "Njoftimi u fshi me sukses",
    deleteError: "Gabim gjatë fshirjes",
    listingNotFound: "Njoftimi nuk u gjet",
    listingNotFoundSub: "Mund të jetë fshirë ose mund të kesh një link të gabuar.",
    backToListings: "Kthehu te njoftimet",
    conditionNew: "I ri", conditionGood: "Shumë mirë",
    conditionUsed: "I përdorur", conditionDamaged: "I dëmtuar",
    bodyType: "Lloji i karocerisë",
    chooseBrand: "Zgjidh markën",
    noListingsYet: "Nuk ka njoftime ende",
    beFirst: "Bëhu i pari që posto në këtë kategori!",
    postFromAnywhere: "Mund të postoni nga kudo.",
    allListings: "Të gjitha njoftimet",
    listings: "Njoftimet",
    brandsAvail: "marka të disponueshme",
    subcategoriesAvail: "nënkategori të disponueshme",
    totalLabel: "gjithsej",
    postTitle: "Posto Njoftim",
    mainCategory: "Kategoria kryesore",
    chooseCategory: "Zgjidh kategorinë...",
    subcategory: "Nënkategoria",
    fj_guide_includes: "Çfarë përfshin kjo kategori",
    fj_guide_conditions: "Si ta përshkruani gjendjen në shpallje",
    fj_guide_col_state: "Gjendja",
    fj_guide_col_meaning: "Çfarë të shkruani",
    bodyTypeLabel: "Tipi i karocerisë",
    chooseType: "Zgjidh tipin...",
    chooseMark: "Zgjidh markën...",
    chooseSubcategory: "Zgjidh nënkategorinë...",
    subcategoryTitleMinHint:
      "Shkruani titullin (min. 5 karaktere) — pastaj zgjidhni ose caktohet nënkategoria.",
    subcategoryAutoSetting: "Duke caktuar nënkategorinë…",
    titlePlaceholderExample: "p.sh. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
    postErrTitleForSubcategory:
      "Shkruani titullin (të paktën 5 shkronja) që sistemi të caktojë nënkategorinë.",
    postErrChooseSubcategory:
      "Zgjidhni nënkategorinë nga lista, ose prisni një sekondë pas titullit.",
    postErrChooseBrand: "Zgjidhni markën / modelin e produktit.",
    choose: "Zgjidh...",
    chooseYear: "Zgjidh vitin...",
    chooseCity: "Zgjidh qytetin...",
    zodParentCategory: "Zgjidhni kategorinë kryesore.",
    zodTitleMin: "Titulli duhet të ketë të paktën 5 karaktere.",
    zodDescriptionMin: "Përshkrimi duhet të ketë të paktën 15 karaktere.",
    zodLocation: "Zgjidhni qytetin.",
    zodPhoneMin: "Telefoni duhet të ketë të paktën 5 shifra.",
    zodSellerName: "Shkruani emrin e shitësit.",
    formInvalidSummary:
      "Plotësoni të gjitha fushat e detyrueshme (kategori, titull min. 5, përshkrim min. 15, foto, çmim, qytet).",
    videoInvalidFormatTitle: "Format i pavlefshëm",
    videoInvalidFormatDesc: "Lejohen vetëm MP4, MOV dhe AVI.",
    videoPreparingTitle: "Duke përgatitur videon...",
    videoPreparingHint:
      "Video optimizohet automatikisht për shpallje (max 100 MB). Mos e mbyll faqen.",
    videoAnalyzeFrameHint:
      "Nuk u lexua korniza e videos. Provoni video më të shkurtër me dritë të mirë, ose shtoni një foto.",
    similarListingsHeading: "Mund të të interesojë gjithashtu",
    titleField: "Titulli",
    listingTitle: "Titulli i njoftimit",
    descField: "Përshkrimi",
    descPlaceholder: "Pershkruani në detaje produktin ose shërbimin tuaj...",
    priceField: "Çmimi",
    priceEur: "Çmimi",
    agreementToggle: "Me marrëveshje (çmimi është i negociueshëm)",
    conditionField: "Gjendja",
    locationSection: "Vendndodhja",
    contactSection: "Kontakti",
    yourName: "Emri juaj",
    phoneNum: "Nr. telefonit",
    mainPhotoLabel: "Kryesore",
    photosSection: "Fotot",
    listingPhotos: "Fotot e njoftimit",
    addPhoto: "Shto foto",
    photoCameraBtn: "Foto me kamerë",
    videoCameraBtn: "Video me kamerë",
    clickToSelect: "Kliko për të zgjedhur foto nga pajisja jote",
    uploading: "Duke ngarkuar...",
    waitPlease: "Ju lutemi prisni",
    analyzingPhoto: "Duke analizuar foton me sistemin tonë...",
    analyzingPhotoHint: "Kategoria, titulli dhe përshkrimi plotësohen automatikisht.",
    photoAnalyzeFailed: "Nuk u plotësua automatikisht",
    photoAnalyzeFailedHint:
      "Vazhdoni manualisht me kategorinë, titullin dhe përshkrimin — ose provoni një foto më të qartë.",
    photoAnalyzeLoginRequired: "Duhet të jesh i kyçur",
    photoAnalyzeLoginRequiredHint:
      "Hyni në llogari dhe provoni përsëri ngarkimin e fotos.",
    photoAnalyzeUnavailable: "Analiza e fotos nuk është e disponueshme për momentin",
    photoAnalyzeUnavailableHint:
      "Plotësoni manualisht kategorinë, titullin dhe përshkrimin.",
    firstPhotoAiHint:
      "📸 Ngarko foton e parë dhe sistemi jonë do të plotësojë automatikisht kategorinë, titullin dhe përshkrimin për ty — kursen kohë dhe e bën shpalljen më të lehtë!",
    firstPhotoAiHintShop:
      "📸 Ngarko foton e produktit — sistemi jonë do të plotësojë automatikisht kategorinë, titullin dhe përshkrimin për shpalljen e dyqanit tënd. Kursen kohë dhe e bën shitjen më të lehtë!",
    systemHelpBtn: "Ndihmë nga sistemi jonë",
    descriptionHelperAccept: "Prano",
    descriptionHelperIgnore: "Injoro",
    postingSuggestionsTitle: "Sugjerime nga sistemi jonë",
    postingSuggestionsLoading: "Duke analizuar njoftimin…",
    firstPhotoMain: "Foto e parë do të jetë foto kryesore e njoftimit",
    carDetails: "Detajet e automjetit",
    houseDetails: "Detajet e pronës",
    phoneDetails: "Detajet e telefonit",
    yearField: "Viti i prodhimit",
    mileageField: "Kilometrazha",
    fuelField: "Karburanti",
    transmissionField: "Transmisioni",
    colorField: "Ngjyra",
    engineField: "Motori (L)",
    powerField: "Fuqia (hp)",
    techCondField: "Gjendja teknike",
    areaField: "Sipërfaqja (m²)",
    floorField: "Kati",
    roomsField: "Numri dhomave",
    furnishedField: "Mobilimi",
    brandField: "Marka",
    modelField: "Modeli",
    capacityField: "Kapaciteti",
    yes: "Po", no: "Jo",
    posting: "Duke postuar...",
    submitListing: "Posto Njoftimin →",
    successPost: "✓ Njoftimi u postua me sukses!",
    postError: "Gabim gjatë postimit",
    postRefusedTitle: "Nuk u postua",
    tooManyPhotos: "Mund të shtosh edhe",
    photosSuffix: "foto",
    addAtLeastPhoto: "Shto të paktën 1 foto",
    uploadFailed: "Ngarkimi dështoi. Provo sërish.",
    editListingTitle: "Edito Njoftimin",
    backToListing: "Kthehu te njoftimi",
    imageUrlField: "URL e fotos (opsionale)",
    promoteLabel: "Promovo njoftimin",
    promoteDesc: "Njoftimi do të shfaqet në seksionin e promovuar",
    updateSuccess: "Njoftimi u perditesua me sukses!",
    updateError: "Gabim gjate perditesimit",
    conditionNewSub: "Papërdorur",
    conditionUsedSub: "Ka qenë në përdorim",
    conditionDamagedSub: "Me defekt / aksident",
    marketsTagline: "Kosovë · Shqipëri · Maqedoni · Mal i Zi",
    marketsBannerLine:
      "Kosovë - Shqipëri - Maqedoni - Mal i Zi - Gjermani - Zvicër - Austri - Francë - Itali - Angli - SHBA",
    terms: "Kushtet",
    businessRules: "Bizneset",
    privacy: "Privatësia",
    contact: "Kontakti",
    faq: "FAQ",
    aboutUs: "Rreth Nesh",
    security: "Siguria",
    footer_colHelp: "NDIHMË",
    footer_colInfo: "INFORMATA",
    footer_colBusiness: "BIZNESE",
    footer_colMarkets: "TREGJET",
    footer_diaspora: "Diaspora",
    footer_contactUs: "Na kontaktoni",
    footer_onlineSecurity: "Siguria online",
    footer_press: "Shtypi",
    footer_aboutKetuJemi: "Rreth KetuJemi",
    footer_rules: "Rregullat",
    footer_cookies: "Cookies",
    footer_openShop: "Hap shitore",
    footer_vipPackages: "Paketa VIP",
    footer_advertise: "Reklamoni",
    footer_partnership: "Partneritet",
    footer_operatedBy: "Operohet nga REVOLUTION INVEST SH.P.K.",
    featured: "Të rekomanduara", recent: "Njoftimet e fundit",
    listingsCount: "njoftime", citiesLabel: "qytetet kryesore",
    authLogin: "Hyr",
    authLogout: "Dil",
    contactRequiresLogin: "Hyr për të kontaktuar shitësin",
    listingAccessDenied: "Nuk keni akses për ta ndryshuar këtë njoftim",
    loginToViewPhone: "Kyçu për të parë numrin",
    sendSms: "Dërgo SMS",
    postQuotaExceeded: "Ke arritur limitin e postimeve falas për këtë kategori.",
    postQuotaRemaining: "Postime falas të mbetura në këtë kategori: {n}",
  },
  mk: {
    title: "Огласи", search: "Барај оглас...", searchBtn: "Барај",
    searchShopsSection: "Продавници",
    filters: "Филтри", category: "Категорија", city: "Град",
    minPrice: "Цена МИН", maxPrice: "Цена МАКС", apply: "Примени",
    clear: "Исчисти", noResults: "Не се најдени огласи",
    noResultsSub: "Обидете се да ги промените филтрите или додајте нов оглас",
    post: "Додај оглас", postFree: "Објави бесплатно",
    shopSuggestBanner: "💡 Имате продавница? Отворете дигитална продавница бесплатно и прикажете ги сите огласи на едно место!",
    shopSuggestBannerBtn: "Отвори продавница →",
    all: "Сите", today: "Денес",
    views: "прегледи", total: "огласи вкупно", in: "во",
    page: "Страна", of: "од",
    hero: "KetuJemi — Купи & Продај",
    heroSub: "Купи & продавај во Македонија — бесплатни огласи",
    categories: "Категории", viewAll: "Види ги сите",
    trust1: "СМС и е-пошта верификација", trust2: "Бесплатно огласување", trust3: "21 категории",
    markets: "КетуЈеми на 11 пазари",
    back: "Назад", edit: "Уреди", delete: "Избриши", cancel: "Откажи",
    saveChanges: "Зачувај промени", saving: "Се зачувува...",
    promoted: "Промовиран", agreement: "По договор",
    description: "Опис", details: "Детали", noPhoto: "Нема фото",
    seller: "Продавач", privateSeller: "Приватен продавач",
    callSeller: "Телефонирај", whatsapp: "Испрати порака (WhatsApp)",
    share_sectionTitle: "Сподели го овој оглас",
    share_motivation: "💡 Сподели ја твојата објава — секој клик носи нови клиенти во твојата продавница бесплатно!",
    share_facebook: "Facebook",
    share_whatsapp: "WhatsApp",
    share_instagram: "Instagram",
    share_tiktok: "TikTok",
    share_instagramCopyTooltip: "Залепи на Instagram Story",
    share_tiktokCopyTooltip: "Копирај го линкот за TikTok",
    share_socialPostedTitle: "Огласот е објавен на социјалните мрежи",
    share_socialPostedHint: "Сподели повторно со пријателите — секое споделување носи повеќе прегледи.",
    share_socialPostedIgDialogTitle: "Сподели на Instagram",
    share_socialPostedIgDialogBody: "Копирај го линкот на огласот и залепи го на приказна, reels или објава на Instagram.",
    share_socialPostedIgCopied: "✓ Линкот е копиран! Отвори Instagram и сподели го на приказната или објавата.",
    share_socialPostedOpenInstagram: "Отвори Instagram",
    share_copyLink: "🔗 Копирај го линкот",
    share_copied: "✓ Линкот е копиран! Објави го на Instagram или TikTok за повеќе клиенти 🚀",
    share_socialApps: "📲 Instagram / TikTok",
    share_toastSocial: "✓ Линкот е копиран! Отвори Instagram или TikTok и објави го на приказната или објавата 📲",
    share_compactLabel: "Сподели",
    caution: "⚠ Внимание",
    cautionTip1: "Сретни го продавачот лично",
    cautionTip2: "Провери го производот пред плаќање",
    cautionTip3: "Не испраќај пари однапред",
    cautionTip4: "Пријави ако забележиш нешто сомнително",
    deleteTitle: "Избриши оглас?",
    deleteDesc: "Оваа акција не може да се поврати. Огласот ќе биде трајно избришан.",
    deleteSuccess: "Огласот е успешно избришан",
    deleteError: "Грешка при бришење",
    listingNotFound: "Огласот не е најден",
    listingNotFoundSub: "Можеби е избришан или имате погрешен линк.",
    backToListings: "Назад кон огласите",
    conditionNew: "Нов", conditionGood: "Многу добро",
    conditionUsed: "Користен", conditionDamaged: "Оштетен",
    bodyType: "Тип на каросерија",
    chooseBrand: "Изберете марка",
    noListingsYet: "Нема огласи уште",
    beFirst: "Биди прв кој ќе огласи во оваа категорија!",
    postFromAnywhere: "Можете да објавувате од каде било.",
    allListings: "Сите огласи",
    listings: "Огласи",
    brandsAvail: "марки достапни",
    subcategoriesAvail: "подкатегории достапни",
    totalLabel: "вкупно",
    postTitle: "Додај оглас",
    mainCategory: "Главна категорија",
    chooseCategory: "Изберете категорија...",
    subcategory: "Подкатегорија",
    fj_guide_includes: "Што опфаќа оваа категорија",
    fj_guide_conditions: "Како да ја наведете состојбата во огласот",
    fj_guide_col_state: "Состојба",
    fj_guide_col_meaning: "Што да напишете",
    bodyTypeLabel: "Тип на каросерија",
    chooseType: "Изберете тип...",
    chooseMark: "Изберете марка...",
    chooseSubcategory: "Изберете поткатегорија...",
    subcategoryTitleMinHint:
      "Внесете наслов (мин. 5 знаци) — потоа изберете или ќе се постави поткатегоријата.",
    subcategoryAutoSetting: "Се поставува поткатегоријата…",
    titlePlaceholderExample: "пр. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
    postErrTitleForSubcategory:
      "Внесете наслов (најмалку 5 знаци) за системот да ја постави поткатегоријата.",
    postErrChooseSubcategory:
      "Изберете поткатегорија од листата или почекајте една секунда по насловот.",
    postErrChooseBrand: "Изберете марка / модел на производот.",
    choose: "Изберете...",
    chooseYear: "Изберете година...",
    chooseCity: "Изберете град...",
    zodParentCategory: "Изберете главна категорија.",
    zodTitleMin: "Насловот мора да има најмалку 5 знаци.",
    zodDescriptionMin: "Описот мора да има најмалку 15 знаци.",
    zodLocation: "Изберете град.",
    zodPhoneMin: "Телефонот мора да има најмалку 5 цифри.",
    zodSellerName: "Внесете име на продавачот.",
    formInvalidSummary:
      "Пополнете ги сите задолжителни полиња (категорија, наслов мин. 5, опис мин. 15, фото, цена, град).",
    videoInvalidFormatTitle: "Невалиден формат",
    videoInvalidFormatDesc: "Дозволени се само MP4, MOV и AVI.",
    videoPreparingTitle: "Се подготвува видеото...",
    videoPreparingHint:
      "Видеото се оптимизира автоматски за оглас (макс. 100 MB). Не ја затворајте страницата.",
    videoAnalyzeFrameHint:
      "Кадарот од видеото не се прочита. Обидете се со пократко видео со добра светлина или додајте фотографија.",
    similarListingsHeading: "Може да ве интересира исто така",
    titleField: "Наслов",
    listingTitle: "Наслов на оглас",
    descField: "Опис",
    descPlaceholder: "Опишете го производот или услугата детално...",
    priceField: "Цена",
    priceEur: "Цена (EUR)",
    agreementToggle: "По договор (цената е преговарачка)",
    conditionField: "Состојба",
    locationSection: "Локација",
    contactSection: "Контакт",
    yourName: "Вашето име",
    phoneNum: "Бр. телефон",
    mainPhotoLabel: "Главна",
    photosSection: "Фотографии",
    listingPhotos: "Фотографии на огласот",
    addPhoto: "Додај фото",
    photoCameraBtn: "Фото со камера",
    videoCameraBtn: "Видео со камера",
    clickToSelect: "Кликни за да изберете фото од уредот",
    uploading: "Се прикачува...",
    waitPlease: "Ве молиме почекајте",
    analyzingPhoto: "Се анализира фотографијата со нашиот систем...",
    analyzingPhotoHint: "Категоријата, насловот и описот се пополнуваат автоматски.",
    photoAnalyzeFailed: "Не се пополни автоматски",
    photoAnalyzeFailedHint:
      "Продолжете рачно со категорија, наслов и опис — или обидете се со појасна фотографија.",
    photoAnalyzeLoginRequired: "Мора да сте најавени",
    photoAnalyzeLoginRequiredHint:
      "Најавете се и обидете повторно да ја прикачите фотографијата.",
    photoAnalyzeUnavailable: "Анализата на фотографијата моментално не е достапна",
    photoAnalyzeUnavailableHint:
      "Пополнете рачно категорија, наслов и опис.",
    firstPhotoAiHint:
      "📸 Прикачи ја првата фотографија и нашиот систем автоматски ќе ги пополни категоријата, насловот и описот — заштеди време и олесни го огласувањето!",
    firstPhotoAiHintShop:
      "📸 Прикачи ја фотографијата на производот — нашиот систем автоматски ќе ја пополни категоријата, насловот и описот за огласот на твојот продавница. Заштеди време и олесни ја продажбата!",
    systemHelpBtn: "Помош од нашиот систем",
    descriptionHelperAccept: "Прифати",
    descriptionHelperIgnore: "Игнорирај",
    postingSuggestionsTitle: "Предлози од нашиот систем",
    postingSuggestionsLoading: "Се анализира огласот…",
    firstPhotoMain: "Првата фотографија ќе биде главна на огласот",
    carDetails: "Детали за возилото",
    houseDetails: "Детали за имотот",
    phoneDetails: "Детали за телефонот",
    yearField: "Година на производство",
    mileageField: "Километража",
    fuelField: "Гориво",
    transmissionField: "Менувач",
    colorField: "Боја",
    engineField: "Мотор (L)",
    powerField: "Снага (hp)",
    techCondField: "Техничка состојба",
    areaField: "Површина (m²)",
    floorField: "Кат",
    roomsField: "Број на соби",
    furnishedField: "Наместеност",
    brandField: "Марка",
    modelField: "Модел",
    capacityField: "Капацитет",
    yes: "Да", no: "Не",
    posting: "Се објавува...",
    submitListing: "Додај оглас →",
    successPost: "✓ Огласот е успешно објавен!",
    postError: "Грешка при објавување",
    postRefusedTitle: "Не беше објавено",
    tooManyPhotos: "Можете да додадете уште",
    photosSuffix: "фотографии",
    addAtLeastPhoto: "Додај барем 1 фотографија",
    uploadFailed: "Прикачувањето не успеа. Обидете се повторно.",
    editListingTitle: "Уреди оглас",
    backToListing: "Назад кон огласот",
    imageUrlField: "URL на фото (опционално)",
    promoteLabel: "Промовирај оглас",
    promoteDesc: "Огласот ќе биде прикажан во промовиран дел",
    updateSuccess: "Огласот е успешно ажуриран!",
    updateError: "Грешка при ажурирање",
    conditionNewSub: "Неупотребуван",
    conditionUsedSub: "Бил во употреба",
    conditionDamagedSub: "Со дефект / акцидент",
    marketsTagline: "Косово · Албанија · Македонија · Црна Гора",
    marketsBannerLine:
      "Косово - Албанија - Македонија - Црна Гора - Германија - Швајцарија - Австрија - Франција - Италија - Англија - САД",
    terms: "Услови",
    businessRules: "Бизнис",
    privacy: "Приватност",
    contact: "Контакт",
    faq: "FAQ",
    aboutUs: "За нас",
    security: "Безбедност",
    footer_colHelp: "ПОМОШ",
    footer_colInfo: "ИНФОРМАЦИИ",
    footer_colBusiness: "БИЗНИС",
    footer_colMarkets: "ПАЗАРИ",
    footer_diaspora: "Дијаспора",
    footer_contactUs: "Контактирајте нè",
    footer_onlineSecurity: "Онлајн безбедност",
    footer_press: "Медиуми",
    footer_aboutKetuJemi: "За KetuJemi",
    footer_rules: "Правила",
    footer_cookies: "Колачиња",
    footer_openShop: "Отвори продавница",
    footer_vipPackages: "VIP пакети",
    footer_advertise: "Рекламирај",
    footer_partnership: "Партнерство",
    footer_operatedBy: "Оперира REVOLUTION INVEST SH.P.K.",
    featured: "Препорачани", recent: "Последни огласи",
    listingsCount: "огласи", citiesLabel: "главни градови",
    authLogin: "Најави се",
    authLogout: "Одјави се",
    contactRequiresLogin: "Најави се за да го контактираш продавачот",
    listingAccessDenied: "Немате пристап за уредување на овој оглас",
    loginToViewPhone: "Најави се за да го видиш бројот",
    sendSms: "Испрати SMS",
    postQuotaExceeded: "Го достигнавте лимитот на бесплатни огласи за оваа категорија.",
    postQuotaRemaining: "Преостанати бесплатни огласи во оваа категорија: {n}",
  },
  mne: {
    title: "Oglasi", search: "Traži oglas...", searchBtn: "Traži",
    searchShopsSection: "Prodavnice",
    filters: "Filtri", category: "Kategorija", city: "Grad",
    minPrice: "Cijena MIN", maxPrice: "Cijena MAX", apply: "Primijeni",
    clear: "Očisti", noResults: "Nisu pronađeni oglasi",
    noResultsSub: "Pokušajte promijeniti filtere ili dodajte novi oglas",
    post: "Dodaj oglas", postFree: "Objavi besplatno",
    shopSuggestBanner: "💡 Imate prodavnicu? Otvorite digitalnu prodavnicu besplatno i prikažite sve oglase na jednom mjestu!",
    shopSuggestBannerBtn: "Otvori prodavnicu →",
    all: "Sve", today: "Danas",
    views: "pregleda", total: "oglasa ukupno", in: "u",
    page: "Stranica", of: "od",
    hero: "KetuJemi — Kupuj & Prodaj",
    heroSub: "Kupuj & prodaj u Crnoj Gori — besplatni oglasi",
    categories: "Kategorije", viewAll: "Vidi sve",
    trust1: "SMS i email verifikacija", trust2: "Besplatno oglašavanje", trust3: "21 kategorija",
    markets: "KetuJemi na 11 tržišta",
    back: "Nazad", edit: "Uredi", delete: "Obriši", cancel: "Otkaži",
    saveChanges: "Sačuvaj promjene", saving: "Čuvanje...",
    promoted: "Promovisan", agreement: "Po dogovoru",
    description: "Opis", details: "Detalji", noPhoto: "Nema foto",
    seller: "Prodavac", privateSeller: "Privatni prodavac",
    callSeller: "Telefoniraj", whatsapp: "Pošalji poruku (WhatsApp)",
    share_sectionTitle: "Podijeli ovaj oglas",
    share_motivation: "💡 Podijeli svoj oglas — svaki klik donosi nove klijente u tvoju prodavnicu besplatno!",
    share_facebook: "Facebook",
    share_whatsapp: "WhatsApp",
    share_instagram: "Instagram",
    share_tiktok: "TikTok",
    share_instagramCopyTooltip: "Zalijepi na Instagram Story",
    share_tiktokCopyTooltip: "Kopiraj link za TikTok",
    share_socialPostedTitle: "Oglas je objavljen na društvenim mrežama",
    share_socialPostedHint: "Podijeli ponovo s prijateljima — svako dijeljenje donosi više pregleda.",
    share_socialPostedIgDialogTitle: "Podijeli na Instagramu",
    share_socialPostedIgDialogBody: "Kopiraj link oglasa i zalijepi ga u priču, reels ili objavu na Instagramu.",
    share_socialPostedIgCopied: "✓ Link je kopiran! Otvori Instagram i podijeli ga u priči ili objavi.",
    share_socialPostedOpenInstagram: "Otvori Instagram",
    share_copyLink: "🔗 Kopiraj link",
    share_copied: "✓ Link je kopiran! Objavi ga na Instagramu ili TikToku za više klijenata 🚀",
    share_socialApps: "📲 Instagram / TikTok",
    share_toastSocial: "✓ Link je kopiran! Otvori Instagram ili TikTok i objavi ga na priči ili objavi 📲",
    share_compactLabel: "Podijeli",
    caution: "⚠ Pažnja",
    cautionTip1: "Sretni prodavca lično",
    cautionTip2: "Provjeri proizvod prije plaćanja",
    cautionTip3: "Ne šalji novac unaprijed",
    cautionTip4: "Prijavi ako primijetiš nešto sumnjivo",
    deleteTitle: "Obriši oglas?",
    deleteDesc: "Ova akcija se ne može poništiti. Oglas će biti trajno obrisan.",
    deleteSuccess: "Oglas je uspješno obrisan",
    deleteError: "Greška pri brisanju",
    listingNotFound: "Oglas nije pronađen",
    listingNotFoundSub: "Možda je obrisan ili imate pogrešan link.",
    backToListings: "Nazad na oglase",
    conditionNew: "Nov", conditionGood: "Veoma dobro",
    conditionUsed: "Korišten", conditionDamaged: "Oštećen",
    bodyType: "Tip karoserije",
    chooseBrand: "Izaberite marku",
    noListingsYet: "Nema oglasa još",
    beFirst: "Budi prvi koji objavljuje u ovoj kategoriji!",
    postFromAnywhere: "Možete objaviti odakle god.",
    allListings: "Svi oglasi",
    listings: "Oglasi",
    brandsAvail: "marki dostupnih",
    subcategoriesAvail: "potkategorija dostupnih",
    totalLabel: "ukupno",
    postTitle: "Dodaj oglas",
    mainCategory: "Glavna kategorija",
    chooseCategory: "Izaberite kategoriju...",
    subcategory: "Potkategorija",
    fj_guide_includes: "Šta ova kategorija obuhvata",
    fj_guide_conditions: "Kako navesti stanje u oglasu",
    fj_guide_col_state: "Stanje",
    fj_guide_col_meaning: "Šta da napišete",
    bodyTypeLabel: "Tip karoserije",
    chooseType: "Izaberite tip...",
    chooseMark: "Izaberite marku...",
    chooseSubcategory: "Izaberite potkategoriju...",
    subcategoryTitleMinHint:
      "Unesite naslov (min. 5 znakova) — zatim izaberite ili će se postaviti potkategorija.",
    subcategoryAutoSetting: "Postavlja se potkategorija…",
    titlePlaceholderExample: "npr. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
    postErrTitleForSubcategory:
      "Unesite naslov (najmanje 5 znakova) da sistem postavi potkategoriju.",
    postErrChooseSubcategory:
      "Izaberite potkategoriju sa liste ili sačekajte sekundu nakon naslova.",
    postErrChooseBrand: "Izaberite marku / model proizvoda.",
    choose: "Izaberite...",
    chooseYear: "Izaberite godinu...",
    chooseCity: "Izaberite grad...",
    zodParentCategory: "Izaberite glavnu kategoriju.",
    zodTitleMin: "Naslov mora imati najmanje 5 znakova.",
    zodDescriptionMin: "Opis mora imati najmanje 15 znakova.",
    zodLocation: "Izaberite grad.",
    zodPhoneMin: "Telefon mora imati najmanje 5 cifara.",
    zodSellerName: "Unesite ime prodavca.",
    formInvalidSummary:
      "Popunite sva obavezna polja (kategorija, naslov min. 5, opis min. 15, foto, cijena, grad).",
    videoInvalidFormatTitle: "Nevažeći format",
    videoInvalidFormatDesc: "Dozvoljeni su samo MP4, MOV i AVI.",
    videoPreparingTitle: "Priprema se video...",
    videoPreparingHint:
      "Video se automatski optimizuje za oglas (max 100 MB). Ne zatvarajte stranicu.",
    videoAnalyzeFrameHint:
      "Kadar iz videa nije pročitan. Probajte kraći video uz dobro svjetlo ili dodajte fotografiju.",
    similarListingsHeading: "Možda vas zanima i ovo",
    titleField: "Naslov",
    listingTitle: "Naslov oglasa",
    descField: "Opis",
    descPlaceholder: "Opišite detaljno proizvod ili uslugu...",
    priceField: "Cijena",
    priceEur: "Cijena (EUR)",
    agreementToggle: "Po dogovoru (cijena je pregovaračka)",
    conditionField: "Stanje",
    locationSection: "Lokacija",
    contactSection: "Kontakt",
    yourName: "Vaše ime",
    phoneNum: "Br. telefona",
    mainPhotoLabel: "Glavna",
    photosSection: "Fotografije",
    listingPhotos: "Fotografije oglasa",
    addPhoto: "Dodaj foto",
    photoCameraBtn: "Foto kamerom",
    videoCameraBtn: "Video kamerom",
    clickToSelect: "Klikni za odabir fotografije s uređaja",
    uploading: "Učitavanje...",
    waitPlease: "Molimo sačekajte",
    analyzingPhoto: "Analizira se fotografija pomoću našeg sistema...",
    analyzingPhotoHint: "Kategorija, naslov i opis popunjavaju se automatski.",
    photoAnalyzeFailed: "Nije popunjeno automatski",
    photoAnalyzeFailedHint:
      "Nastavite ručno s kategorijom, naslovom i opisom — ili pokušajte s jasnijom fotografijom.",
    photoAnalyzeLoginRequired: "Morate biti prijavljeni",
    photoAnalyzeLoginRequiredHint:
      "Prijavite se i ponovo pokušajte učitati fotografiju.",
    photoAnalyzeUnavailable: "Analiza fotografije trenutno nije dostupna",
    photoAnalyzeUnavailableHint:
      "Ručno popunite kategoriju, naslov i opis.",
    firstPhotoAiHint:
      "📸 Učitaj prvu fotografiju i naš sistem će automatski popuniti kategoriju, naslov i opis — uštedi vrijeme i olakšaj oglašavanje!",
    firstPhotoAiHintShop:
      "📸 Učitaj fotografiju proizvoda — naš sistem će automatski popuniti kategoriju, naslov i opis za oglas tvoje prodavnice. Uštedi vrijeme i olakšaj prodaju!",
    systemHelpBtn: "Pomoć našeg sistema",
    descriptionHelperAccept: "Prihvati",
    descriptionHelperIgnore: "Ignoriši",
    postingSuggestionsTitle: "Prijedlozi našeg sistema",
    postingSuggestionsLoading: "Analizira se oglas…",
    firstPhotoMain: "Prva fotografija će biti glavna na oglasu",
    carDetails: "Detalji vozila",
    houseDetails: "Detalji nekretnine",
    phoneDetails: "Detalji telefona",
    yearField: "Godina proizvodnje",
    mileageField: "Kilometraža",
    fuelField: "Gorivo",
    transmissionField: "Mjenjač",
    colorField: "Boja",
    engineField: "Motor (L)",
    powerField: "Snaga (hp)",
    techCondField: "Tehnička ispravnost",
    areaField: "Površina (m²)",
    floorField: "Kat",
    roomsField: "Broj soba",
    furnishedField: "Namještenost",
    brandField: "Marka",
    modelField: "Model",
    capacityField: "Kapacitet",
    yes: "Da", no: "Ne",
    posting: "Objavljuje se...",
    submitListing: "Dodaj oglas →",
    successPost: "✓ Oglas je uspješno objavljen!",
    postError: "Greška pri objavljivanju",
    postRefusedTitle: "Nije objavljeno",
    tooManyPhotos: "Možete dodati još",
    photosSuffix: "fotografija",
    addAtLeastPhoto: "Dodaj najmanje 1 fotografiju",
    uploadFailed: "Učitavanje nije uspjelo. Pokušajte ponovo.",
    editListingTitle: "Uredi oglas",
    backToListing: "Nazad na oglas",
    imageUrlField: "URL fotografije (opcionalno)",
    promoteLabel: "Promoviši oglas",
    promoteDesc: "Oglas će biti prikazan u promovanom dijelu",
    updateSuccess: "Oglas je uspješno ažuriran!",
    updateError: "Greška pri ažuriranju",
    conditionNewSub: "Nekorišten",
    conditionUsedSub: "Bio u upotrebi",
    conditionDamagedSub: "Sa defektom / u nesreći",
    marketsTagline: "Kosovo · Albanija · Makedonija · Crna Gora",
    marketsBannerLine:
      "Kosovo - Albanija - Makedonija - Crna Gora - Njemačka - Švicarska - Austrija - Francuska - Italija - Engleska - SAD",
    terms: "Uslovi",
    businessRules: "Biznisi",
    privacy: "Privatnost",
    contact: "Kontakt",
    faq: "FAQ",
    aboutUs: "O nama",
    security: "Sigurnost",
    footer_colHelp: "POMOĆ",
    footer_colInfo: "INFORMACIJE",
    footer_colBusiness: "BIZNIS",
    footer_colMarkets: "TRŽIŠTA",
    footer_diaspora: "Dijaspora",
    footer_contactUs: "Kontaktirajte nas",
    footer_onlineSecurity: "Online sigurnost",
    footer_press: "Mediji",
    footer_aboutKetuJemi: "O KetuJemi",
    footer_rules: "Pravila",
    footer_cookies: "Kolačići",
    footer_openShop: "Otvori prodavnicu",
    footer_vipPackages: "VIP paketi",
    footer_advertise: "Reklamirajte",
    footer_partnership: "Partnerstvo",
    footer_operatedBy: "Upravlja REVOLUTION INVEST SH.P.K.",
    featured: "Preporučeni", recent: "Najnoviji oglasi",
    listingsCount: "oglasa", citiesLabel: "glavni gradovi",
    authLogin: "Prijavi se",
    authLogout: "Odjavi se",
    contactRequiresLogin: "Prijavi se da kontaktiraš prodavca",
    listingAccessDenied: "Nemate pristup za uređivanje ovog oglasa",
    loginToViewPhone: "Prijavi se da vidiš broj",
    sendSms: "Pošalji SMS",
    postQuotaExceeded: "Dostigli ste limit besplatnih oglasa za ovu kategoriju.",
    postQuotaRemaining: "Preostalo besplatnih oglasa u ovoj kategoriji: {n}",
  },
  en: {
    title: "Listings", search: "Search listings...", searchBtn: "Search",
    searchShopsSection: "Shops",
    filters: "Filters", category: "Category", city: "City",
    minPrice: "Min price", maxPrice: "Max price", apply: "Apply",
    clear: "Clear", noResults: "No listings found",
    noResultsSub: "Try changing filters or post a new listing",
    post: "Post listing", postFree: "Post for free",
    shopSuggestBanner: "💡 Have a shop? Open your free digital shop and showcase all your listings in one place!",
    shopSuggestBannerBtn: "Open shop →",
    all: "All", today: "Today",
    views: "views", total: "listings total", in: "in",
    page: "Page", of: "of",
    hero: "KetuJemi — Buy & Sell",
    heroSub: "Buy & sell across the Balkans — free classifieds platform",
    categories: "Categories", viewAll: "View all",
    trust1: "SMS & email verification", trust2: "Post for free", trust3: "21 categories",
    markets: "KetuJemi in 11 markets",
    back: "Back", edit: "Edit", delete: "Delete", cancel: "Cancel",
    saveChanges: "Save changes", saving: "Saving...",
    promoted: "Promoted", agreement: "Negotiable",
    description: "Description", details: "Details", noPhoto: "No photo",
    seller: "Seller", privateSeller: "Private seller",
    callSeller: "Call", whatsapp: "Message on WhatsApp",
    share_sectionTitle: "Share this listing",
    share_motivation: "💡 Share your listing — every click brings new customers to your shop for free!",
    share_facebook: "Facebook",
    share_whatsapp: "WhatsApp",
    share_instagram: "Instagram",
    share_tiktok: "TikTok",
    share_instagramCopyTooltip: "Paste to Instagram Story",
    share_tiktokCopyTooltip: "Copy link for TikTok",
    share_socialPostedTitle: "Listing published on social media",
    share_socialPostedHint: "Share again with friends — every share brings more views to your listing.",
    share_socialPostedIgDialogTitle: "Share on Instagram",
    share_socialPostedIgDialogBody: "Copy the listing link and paste it to your story, reels, or feed on Instagram.",
    share_socialPostedIgCopied: "✓ Link copied! Open Instagram and share it to your story or post.",
    share_socialPostedOpenInstagram: "Open Instagram",
    share_copyLink: "🔗 Copy link",
    share_copied: "✓ Link copied! Post it on Instagram or TikTok for more customers 🚀",
    share_socialApps: "📲 Instagram / TikTok",
    share_toastSocial: "✓ Link copied! Open Instagram or TikTok and post it to your story or feed 📲",
    share_compactLabel: "Share",
    caution: "⚠ Caution",
    cautionTip1: "Meet the seller in person",
    cautionTip2: "Inspect the item before paying",
    cautionTip3: "Do not send money in advance",
    cautionTip4: "Report anything suspicious",
    deleteTitle: "Delete listing?",
    deleteDesc: "This cannot be undone. The listing will be permanently removed.",
    deleteSuccess: "Listing deleted successfully",
    deleteError: "Error while deleting",
    listingNotFound: "Listing not found",
    listingNotFoundSub: "It may have been removed or the link is incorrect.",
    backToListings: "Back to listings",
    conditionNew: "New", conditionGood: "Very good",
    conditionUsed: "Used", conditionDamaged: "Damaged",
    bodyType: "Body type",
    chooseBrand: "Choose brand",
    noListingsYet: "No listings yet",
    beFirst: "Be the first to post in this category!",
    postFromAnywhere: "You can post from anywhere.",
    allListings: "All listings",
    listings: "Listings",
    brandsAvail: "brands available",
    subcategoriesAvail: "subcategories available",
    totalLabel: "total",
    postTitle: "Post listing",
    mainCategory: "Main category",
    chooseCategory: "Choose category...",
    subcategory: "Subcategory",
    fj_guide_includes: "What this category includes",
    fj_guide_conditions: "How to describe condition in your listing",
    fj_guide_col_state: "Condition",
    fj_guide_col_meaning: "What to write",
    bodyTypeLabel: "Body type",
    chooseType: "Choose type...",
    chooseMark: "Choose brand...",
    chooseSubcategory: "Choose subcategory...",
    subcategoryTitleMinHint:
      "Enter a title (min. 5 characters) — then pick or the subcategory will be set automatically.",
    subcategoryAutoSetting: "Setting subcategory…",
    titlePlaceholderExample: "e.g. BMW X5 2020, JBL 500, iPhone 14 Pro Max...",
    postErrTitleForSubcategory:
      "Enter a title (at least 5 characters) so the system can set the subcategory.",
    postErrChooseSubcategory:
      "Choose a subcategory from the list, or wait a moment after entering the title.",
    postErrChooseBrand: "Choose the product brand / model.",
    photoAnalyzeFailed: "Could not fill in automatically",
    photoAnalyzeFailedHint:
      "Continue manually with category, title, and description — or try a clearer photo.",
    photoAnalyzeLoginRequired: "You need to be logged in",
    photoAnalyzeLoginRequiredHint:
      "Sign in and try uploading the photo again.",
    photoAnalyzeUnavailable: "Photo analysis is temporarily unavailable",
    photoAnalyzeUnavailableHint:
      "Fill in category, title, and description manually.",
    choose: "Choose...",
    chooseYear: "Choose year...",
    chooseCity: "Choose city...",
    zodParentCategory: "Choose a main category.",
    zodTitleMin: "Title must be at least 5 characters.",
    zodDescriptionMin: "Description must be at least 15 characters.",
    zodLocation: "Choose a city.",
    zodPhoneMin: "Phone must have at least 5 digits.",
    zodSellerName: "Enter the seller name.",
    formInvalidSummary:
      "Fill in all required fields (category, title min. 5, description min. 15, photo, price, city).",
    videoInvalidFormatTitle: "Invalid format",
    videoInvalidFormatDesc: "Only MP4, MOV, and AVI are allowed.",
    videoPreparingTitle: "Preparing video...",
    videoPreparingHint:
      "Video is being optimized for your listing (max 100 MB). Do not close this page.",
    videoAnalyzeFrameHint:
      "Could not read a frame from the video. Try a shorter clip with good lighting, or add a photo.",
    similarListingsHeading: "You may also like",
    titleField: "Title",
    listingTitle: "Listing title",
    descField: "Description",
    descPlaceholder: "Describe your product or service in detail...",
    priceField: "Price",
    priceEur: "Price (EUR)",
    agreementToggle: "Negotiable (price is open to offers)",
    conditionField: "Condition",
    locationSection: "Location",
    contactSection: "Contact",
    yourName: "Your name",
    phoneNum: "Phone number",
    mainPhotoLabel: "Main",
    photosSection: "Photos",
    listingPhotos: "Listing photos",
    addPhoto: "Add photo",
    photoCameraBtn: "Take photo with camera",
    videoCameraBtn: "Record video with camera",
    clickToSelect: "Tap to choose photos from your device",
    uploading: "Uploading...",
    waitPlease: "Please wait",
    analyzingPhoto: "Analyzing photo with our system...",
    analyzingPhotoHint: "Category, title, and description are filled in automatically.",
    firstPhotoAiHint:
      "📸 Upload your first photo and our system will automatically fill in the category, title and description for you — saves time and makes listing easier!",
    firstPhotoAiHintShop:
      "📸 Upload a product photo — our system will automatically fill in the category, title and description for your shop listing. Saves time and makes selling easier!",
    systemHelpBtn: "Help from our system",
    descriptionHelperAccept: "Accept",
    descriptionHelperIgnore: "Ignore",
    postingSuggestionsTitle: "Suggestions from our system",
    postingSuggestionsLoading: "Analyzing your listing…",
    firstPhotoMain: "The first photo will be the main listing image",
    carDetails: "Vehicle details",
    houseDetails: "Property details",
    phoneDetails: "Phone details",
    yearField: "Year",
    mileageField: "Mileage",
    fuelField: "Fuel",
    transmissionField: "Transmission",
    colorField: "Color",
    engineField: "Engine (L)",
    powerField: "Power (hp)",
    techCondField: "Technical condition",
    areaField: "Area (m²)",
    floorField: "Floor",
    roomsField: "Rooms",
    furnishedField: "Furnishing",
    brandField: "Brand",
    modelField: "Model",
    capacityField: "Capacity",
    yes: "Yes", no: "No",
    posting: "Posting...",
    submitListing: "Post listing →",
    successPost: "✓ Listing posted successfully!",
    postError: "Error while posting",
    postRefusedTitle: "Not posted",
    tooManyPhotos: "You can add",
    photosSuffix: "more photos",
    addAtLeastPhoto: "Add at least 1 photo",
    uploadFailed: "Upload failed. Try again.",
    editListingTitle: "Edit listing",
    backToListing: "Back to listing",
    imageUrlField: "Photo URL (optional)",
    promoteLabel: "Promote listing",
    promoteDesc: "Listing will appear in the promoted section",
    updateSuccess: "Listing updated successfully!",
    updateError: "Error while updating",
    conditionNewSub: "Unused",
    conditionUsedSub: "Previously used",
    conditionDamagedSub: "Defective / accident",
    marketsTagline: "Kosovo · Albania · North Macedonia · Montenegro",
    marketsBannerLine:
      "Kosovo - Albania - North Macedonia - Montenegro - Germany - Switzerland - Austria - France - Italy - UK - USA",
    terms: "Terms",
    businessRules: "Business",
    privacy: "Privacy",
    contact: "Contact",
    faq: "FAQ",
    aboutUs: "About us",
    security: "Security",
    footer_colHelp: "HELP",
    footer_colInfo: "INFO",
    footer_colBusiness: "BUSINESS",
    footer_colMarkets: "MARKETS",
    footer_diaspora: "Diaspora",
    footer_contactUs: "Contact us",
    footer_onlineSecurity: "Online security",
    footer_press: "Press",
    footer_aboutKetuJemi: "About KetuJemi",
    footer_rules: "Rules",
    footer_cookies: "Cookies",
    footer_openShop: "Open a shop",
    footer_vipPackages: "VIP packages",
    footer_advertise: "Advertise",
    footer_partnership: "Partnership",
    footer_operatedBy: "Operated by REVOLUTION INVEST SH.P.K.",
    featured: "Featured", recent: "Recent listings",
    listingsCount: "listings", citiesLabel: "main cities",
    authLogin: "Log in",
    authLogout: "Log out",
    contactRequiresLogin: "Log in to contact the seller",
    listingAccessDenied: "You do not have permission to edit this listing",
    loginToViewPhone: "Log in to see the phone number",
    sendSms: "Send SMS",
    postQuotaExceeded: "You have reached the free posting limit for this category.",
    postQuotaRemaining: "Free posts remaining in this category: {n}",
  },
};

// ─── Form option arrays per market ────────────────────────────────────────────
export const FORM_OPTIONS: Record<string, Record<string, string[]>> = {
  fuel: {
    ks:  ["Benzinë", "Naftë", "Elektrik", "Hibrid", "Gaz (LPG)", "Tjetër"],
    al:  ["Benzinë", "Naftë", "Elektrik", "Hibrid", "Gaz (LPG)", "Tjetër"],
    mk:  ["Бензин", "Дизел", "Електричен", "Хибрид", "Гас (ТНГ)", "Друго"],
    mne: ["Benzin", "Dizel", "Električni", "Hibrid", "Gas (LPG)", "Ostalo"],
    en:  ["Petrol", "Diesel", "Electric", "Hybrid", "LPG", "Other"],
  },
  transmission: {
    ks:  ["Manuale", "Automatike", "Gjysëm-automatike"],
    al:  ["Manuale", "Automatike", "Gjysëm-automatike"],
    mk:  ["Рачен", "Автоматски", "Полу-автоматски"],
    mne: ["Manuelni", "Automatski", "Poluautomatski"],
    en:  ["Manual", "Automatic", "Semi-automatic"],
  },
  bodyType: {
    ks:  ["Sedan", "Hatchback", "SUV / Jeep", "Kombi", "Kabriolet", "Kupe", "Pikap", "Furgon"],
    al:  ["Sedan", "Hatchback", "SUV / Jeep", "Kombi", "Kabriolet", "Kupe", "Pikap", "Furgon"],
    mk:  ["Седан", "Хечбек", "Теренец / Џип", "Комби", "Кабриолет", "Купе", "Пикап", "Фургон"],
    mne: ["Sedan", "Hatchback", "Terenac / Džip", "Kombi", "Kabriolet", "Kupe", "Pikap", "Kombi/Van"],
    en:  ["Sedan", "Hatchback", "SUV / Jeep", "Estate", "Convertible", "Coupe", "Pickup", "Van"],
  },
  color: {
    ks:  ["E zezë", "E bardhë", "Gri / Argjend", "E kaltër", "E kuqe", "E gjelbër", "E verdhë / Gold", "Kafe / Beige", "Portokalli", "Vjollcë", "Tjetër"],
    al:  ["E zezë", "E bardhë", "Gri / Argjend", "E kaltër", "E kuqe", "E gjelbër", "E verdhë / Gold", "Kafe / Beige", "Portokalli", "Vjollcë", "Tjetër"],
    mk:  ["Црна", "Бела", "Сива / Сребрена", "Сина", "Црвена", "Зелена", "Жолта / Злато", "Кафеава / Беж", "Портокалова", "Виолетова", "Друго"],
    mne: ["Crna", "Bijela", "Siva / Srebrna", "Plava", "Crvena", "Zelena", "Žuta / Zlatna", "Smeđa / Bež", "Narandžasta", "Ljubičasta", "Ostalo"],
    en:  ["Black", "White", "Grey / Silver", "Blue", "Red", "Green", "Yellow / Gold", "Brown / Beige", "Orange", "Purple", "Other"],
  },
  techCondition: {
    ks:  ["E shkëlqyer", "Shumë e mirë", "E mirë", "E pranueshme", "Për riparim"],
    al:  ["E shkëlqyer", "Shumë e mirë", "E mirë", "E pranueshme", "Për riparim"],
    mk:  ["Одлична", "Многу добра", "Добра", "Прифатлива", "За поправка"],
    mne: ["Odlično", "Veoma dobra", "Dobra", "Prihvatljivo", "Za popravku"],
    en:  ["Excellent", "Very good", "Good", "Acceptable", "For repair"],
  },
  furnished: {
    ks:  ["I mobiluar", "Pjesërisht i mobiluar", "Pa mobilje"],
    al:  ["I mobiluar", "Pjesërisht i mobiluar", "Pa mobilje"],
    mk:  ["Наместено", "Делумно наместено", "Без мебел"],
    mne: ["Namješteno", "Djelimično namješteno", "Bez namještaja"],
    en:  ["Furnished", "Partly furnished", "Unfurnished"],
  },
};

/** Listing-form option labels for the active UI language (falls back to ks). */
export function formOptionsForUiLang(
  field: keyof typeof FORM_OPTIONS,
  uiLang: string,
): string[] {
  const opts = FORM_OPTIONS[field];
  if (uiLang === "en" && opts.en?.length) return opts.en;
  return opts.ks;
}

// ─── Locations per market ─────────────────────────────────────────────────────
export const LOCATIONS: Record<string, string[]> = {
  ks: [
    "Prishtinë","Prizren","Pejë","Mitrovicë","Gjilan","Ferizaj","Gjakovë","Vushtrri","Podujevë",
    "Suharekë","Rahovec","Malishevë","Skenderaj","Klinë","Drenas","Lipjan","Shtime","Kaçanik",
    "Hani i Elezit","Shtërpcë",
  ],
  al: [
    "Tiranë","Durrës","Vlorë","Shkodër","Elbasan","Fier","Korçë","Berat","Lushnjë","Kavajë",
    "Gjirokastër","Sarandë","Pogradec","Laç","Lezhë","Kukës","Peshkopi",
  ],
  mk: [
    "Скопје",
    "Тетово",
    "Гостивар",
    "Охрид",
    "Битола",
    "Куманово",
    "Струмица",
    "Прилеп",
    "Кавадарци",
    "Неготино",
    "Струга",
    "Кичево",
    "Дебар",
    "Кочани",
  ],
  mne: [
    "Podgorica",
    "Ulcinj",
    "Tivat",
    "Budva",
    "Kotor",
    "Herceg Novi",
    "Nikšić",
    "Berane",
    "Plav",
    "Gusinje",
    "Rožaje",
  ],
  de: ["Berlin", "München", "Hamburg", "Frankfurt", "Köln", "Stuttgart", "Düsseldorf", "Dortmund"],
  ch: ["Zürich", "Genève", "Basel", "Bern", "Lausanne", "Luzern"],
  at: ["Wien", "Graz", "Linz", "Salzburg", "Innsbruck"],
  fr: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Strasbourg"],
  it: ["Milano", "Roma", "Torino", "Bologna", "Firenze", "Verona"],
  gb: ["London", "Manchester", "Birmingham", "Leeds", "Glasgow", "Liverpool"],
  us: ["New York", "Chicago", "Los Angeles", "Houston", "Boston", "Miami"],
};

export const ALL_LOCATIONS: string[] = [
  ...LOCATIONS.ks,
  ...LOCATIONS.al,
  ...LOCATIONS.mk,
  ...LOCATIONS.mne,
  ...LOCATIONS.de,
  ...LOCATIONS.ch,
  ...LOCATIONS.at,
  ...LOCATIONS.fr,
  ...LOCATIONS.it,
  ...LOCATIONS.gb,
  ...LOCATIONS.us,
];

/** Balkan home markets with dedicated city lists on listing forms. */
export const HOME_MARKET_CODES = ["ks", "al", "mk"] as const;
export type HomeMarketCode = (typeof HOME_MARKET_CODES)[number];

/** Diaspora markets on listing forms (Mal i Zi included here, not in home row). */
export const DIASPORA_MARKET_CODES = ["de", "ch", "at", "fr", "it", "gb", "us", "mne"] as const;
export type DiasporaMarketCode = (typeof DIASPORA_MARKET_CODES)[number];

export const LISTING_MARKET_CODES = [...HOME_MARKET_CODES, ...DIASPORA_MARKET_CODES] as const;
export type ListingMarketCode = (typeof LISTING_MARKET_CODES)[number];

export const HOME_MARKET_ISO: Record<HomeMarketCode, string> = {
  ks: "XK",
  al: "AL",
  mk: "MK",
};

export function isHomeMarketCode(code: string): code is HomeMarketCode {
  return (HOME_MARKET_CODES as readonly string[]).includes(code);
}

export function isDiasporaMarketCode(code: string): code is DiasporaMarketCode {
  return (DIASPORA_MARKET_CODES as readonly string[]).includes(code);
}

export function isListingMarketCode(code: string): code is ListingMarketCode {
  return (LISTING_MARKET_CODES as readonly string[]).includes(code);
}

/** Map header market to listing country tile (home or diaspora). */
export function defaultListingMarketFromMarket(code: string): ListingMarketCode {
  return isListingMarketCode(code) ? code : "ks";
}

/** @deprecated Use {@link defaultListingMarketFromMarket} */
export function homeMarketCodeFromMarket(code: string): HomeMarketCode {
  return isHomeMarketCode(code) ? code : "ks";
}

export function locationsForListingMarket(code: string): string[] {
  if (!isListingMarketCode(code)) return [];
  return LOCATIONS[code] ?? [];
}

export function locationsForHomeMarket(code: string): string[] {
  return locationsForListingMarket(code);
}

// ─── Context ──────────────────────────────────────────────────────────────────
interface MarketContextType {
  market: Market;
  setMarket: (m: Market) => void;
  uiLang: UiLang;
  setUiLang: (lang: UiLang) => void;
  rates: Record<string, number>;
  t: Record<string, string>;
}

const MarketContext = createContext<MarketContextType>({
  market: MARKETS[0],
  setMarket: () => {},
  uiLang: DEFAULT_UI_LANG,
  setUiLang: () => {},
  rates: { EUR: 1, ALL: 109.5, MKD: 61.5 },
  t: TRANSLATIONS.ks,
});

export function MarketProvider({ children }: { children: ReactNode }) {
  const [market, setMarketState] = useState<Market>(MARKETS[0]);
  const [uiLang, setUiLangState] = useState<UiLang>(DEFAULT_UI_LANG);
  const [rates, setRates] = useState<Record<string, number>>({ EUR: 1, ALL: 109.5, MKD: 61.5 });
  const [extraTranslations, setExtraTranslations] = useState<
    Record<string, Record<string, string>> | null
  >(null);

  useEffect(() => {
    void import("./app-extra-i18n").then((m) => setExtraTranslations(m.EXTRA_TRANSLATIONS));
  }, []);

  useEffect(() => {
    fetchLiveRates().then(setRates);
  }, []);

  useEffect(() => {
    try {
      const saved = localStorage.getItem("vendi_market");
      if (saved) {
        const found = MARKETS.find((m) => m.code === saved);
        if (found) setMarketState(found);
      }
    } catch {}
  }, []);

  useEffect(() => {
    try {
      const saved = localStorage.getItem("vendi_ui_lang");
      if (saved && isUiLang(saved)) setUiLangState(saved);
    } catch {}
  }, []);

  const setMarket = (m: Market) => {
    setMarketState(m);
    try { localStorage.setItem("vendi_market", m.code); } catch {}
  };

  const setUiLang = (lang: UiLang) => {
    setUiLangState(lang);
    try { localStorage.setItem("vendi_ui_lang", lang); } catch {}
  };

  const translationCode = translationKeyForUiLang(uiLang);
  const tMerged = useMemo(
    () => ({
      ...TRANSLATIONS[translationCode],
      ...(extraTranslations?.[translationCode] ?? {}),
    }),
    [translationCode, extraTranslations],
  );

  return (
    <MarketContext.Provider value={{ market, setMarket, uiLang, setUiLang, rates, t: tMerged }}>
      {children}
    </MarketContext.Provider>
  );
}

export function useMarket() {
  return useContext(MarketContext);
}
